// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package loadtestwritetargetcap

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities/consensus/ocr3/ocr3cap"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg Config) New(w *sdk.WorkflowSpecFactory, id string, ref string, input WritetargetActionInput) OutputCap {

	def := sdk.StepDefinition{
		ID: id, Ref: ref,
		Inputs: input.ToSteps(),
		Config: map[string]any{
			"ResultsPath": cfg.ResultsPath,
		},
		CapabilityType: capabilities.CapabilityTypeAction,
	}

	step := sdk.Step[Output]{Definition: def}
	raw := step.AddTo(w)
	return OutputWrapper(raw)
}

// OutputWrapper allows access to field from an sdk.CapDefinition[Output]
func OutputWrapper(raw sdk.CapDefinition[Output]) OutputCap {
	wrapped, ok := raw.(OutputCap)
	if ok {
		return wrapped
	}
	return &outputCap{CapDefinition: raw}
}

type OutputCap interface {
	sdk.CapDefinition[Output]
	Message() sdk.CapDefinition[string]
	private()
}

type outputCap struct {
	sdk.CapDefinition[Output]
}

func (*outputCap) private() {}
func (c *outputCap) Message() sdk.CapDefinition[string] {
	return sdk.AccessField[Output, string](c.CapDefinition, "Message")
}

func ConstantOutput(value Output) OutputCap {
	return &outputCap{CapDefinition: sdk.ConstantDefinition(value)}
}

func NewOutputFromFields(
	message sdk.CapDefinition[string]) OutputCap {
	return &simpleOutput{
		CapDefinition: sdk.ComponentCapDefinition[Output]{
			"Message": message.Ref(),
		},
		message: message,
	}
}

type simpleOutput struct {
	sdk.CapDefinition[Output]
	message sdk.CapDefinition[string]
}

func (c *simpleOutput) Message() sdk.CapDefinition[string] {
	return c.message
}

func (c *simpleOutput) private() {}

type WritetargetActionInput struct {
	ScheduledStartTime sdk.CapDefinition[string]
	SignedReport       sdk.CapDefinition[ocr3cap.SignedReport]
	StartTime          sdk.CapDefinition[string]
}

func (input WritetargetActionInput) ToSteps() sdk.StepInputs {
	return sdk.StepInputs{
		Mapping: map[string]any{
			"ScheduledStartTime": input.ScheduledStartTime.Ref(),
			"SignedReport":       input.SignedReport.Ref(),
			"StartTime":          input.StartTime.Ref(),
		},
	}
}
