// Code generated by github.com/smartcontractkit/capabilities/libs/standalone/protohelpers/protoc, DO NOT EDIT.

package protos

import (
	"context"
	"fmt"

	"google.golang.org/protobuf/types/known/emptypb"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	caperrors "github.com/smartcontractkit/chainlink-common/pkg/capabilities/errors"
)

// Avoid unused imports if there is configuration type
var _ = emptypb.Empty{}

// CronCapability is what a capability implements to be served as cron-trigger@1.0.0.
//
// It carries no Initialise: a capability is given what it needs when it is
// built, and everything a host does to it - registering it, serving it,
// announcing it, taking it back out - belongs to the bootstrapper that hosts it
// rather than to the capability or to this server.
type CronCapability interface {
	RegisterTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *Config) (<-chan capabilities.TriggerAndId[*Payload], caperrors.Error)
	UnregisterTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *Config) caperrors.Error

	RegisterLegacyTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *Config) (<-chan capabilities.TriggerAndId[*LegacyPayload], caperrors.Error)
	UnregisterLegacyTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *Config) caperrors.Error
	AckEvent(ctx context.Context, triggerId string, eventId string, method string) caperrors.Error

	Start(ctx context.Context) error
	Close() error
	HealthReport() map[string]error
	Name() string
	Description() string
	Ready() error
}

func NewCronServer(capability CronCapability) *CronServer {
	stopCh := make(chan struct{})
	return &CronServer{
		cronCapability: cronCapability{CronCapability: capability, stopCh: stopCh},
		stopCh:         stopCh,
	}
}

// CronServer serves the capability: it turns the untyped requests a host
// delivers into calls on the typed methods above, and is itself the
// capabilities.ExecutableAndTriggerCapability a host registers and serves.
type CronServer struct {
	cronCapability
	stopCh chan struct{}
}

// Close stops answering registered triggers, then closes the capability.
//
// Nothing is deregistered here. What put this capability in a registry, and
// announced it to a node, is the host - so taking it back out is the host's too,
// and doing it from both would race a shutdown against itself.
func (c *CronServer) Close() error {
	if c.stopCh != nil {
		close(c.stopCh)
	}

	return c.cronCapability.Close()
}

type cronCapability struct {
	CronCapability
	stopCh chan struct{}
}

func (c *cronCapability) Info(ctx context.Context) (capabilities.CapabilityInfo, error) {
	return capabilities.NewCapabilityInfo("cron-trigger@1.0.0", capabilities.CapabilityTypeCombined, c.CronCapability.Description())
}

var _ capabilities.ExecutableAndTriggerCapability = (*cronCapability)(nil)

const CronID = "cron-trigger@1.0.0"

// Service is the proto service this server was generated from.
//
// Taken from the file descriptor rather than rebuilt, so it is the same
// descriptor the messages were generated against: whatever reads it sees the
// methods, and their input and output types, exactly as the proto declares them.
func (c *cronCapability) Service() protoreflect.ServiceDescriptor {
	return File_capabilities_scheduler_cron_v1_trigger_proto.Services().ByName("Cron")
}

func (c *cronCapability) RegisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) (<-chan capabilities.TriggerResponse, error) {
	ctx = request.Metadata.ContextWithCRE(ctx)
	switch request.Method {
	case "Trigger":
		input := &Config{}
		return capabilities.RegisterTrigger(ctx, c.stopCh, "cron-trigger@1.0.0", request, input, c.CronCapability.RegisterTrigger)
	case "":
		input := &Config{}
		return capabilities.RegisterTrigger(ctx, c.stopCh, "cron-trigger@1.0.0", request, input, c.CronCapability.RegisterLegacyTrigger)
	default:
		return nil, fmt.Errorf("trigger %s not found", request.Method)
	}
}

func (c *cronCapability) UnregisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) error {
	ctx = request.Metadata.ContextWithCRE(ctx)
	switch request.Method {
	case "Trigger":
		input := &Config{}
		_, err := capabilities.FromValueOrAny(request.Config, request.Payload, input)
		if err != nil {
			return err
		}
		return c.CronCapability.UnregisterTrigger(ctx, request.TriggerID, request.Metadata, input)
	case "":
		input := &Config{}
		_, err := capabilities.FromValueOrAny(request.Config, request.Payload, input)
		if err != nil {
			return err
		}
		return c.CronCapability.UnregisterLegacyTrigger(ctx, request.TriggerID, request.Metadata, input)
	default:
		return fmt.Errorf("method %s not found", request.Method)
	}
}

func (c *cronCapability) AckEvent(ctx context.Context, triggerId string, eventId string, method string) error {
	switch method {
	case "Trigger":
		return c.CronCapability.AckEvent(ctx, triggerId, eventId, method)
	case "":
		return c.CronCapability.AckEvent(ctx, triggerId, eventId, method)
	default:
		return fmt.Errorf("trigger %s not found", method)
	}
}

func (c *cronCapability) RegisterToWorkflow(ctx context.Context, request capabilities.RegisterToWorkflowRequest) error {
	return nil
}

func (c *cronCapability) UnregisterFromWorkflow(ctx context.Context, request capabilities.UnregisterFromWorkflowRequest) error {
	return nil
}

func (c *cronCapability) Execute(ctx context.Context, request capabilities.CapabilityRequest) (capabilities.CapabilityResponse, error) {
	return capabilities.CapabilityResponse{}, fmt.Errorf("method %s not found", request.Method)
}
