// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: value_consensus_types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMetaData struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RequestId                string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowExecutionId      string                 `protobuf:"bytes,2,opt,name=workflow_execution_id,json=workflowExecutionId,proto3" json:"workflow_execution_id,omitempty"`
	WorkflowStepReference    string                 `protobuf:"bytes,3,opt,name=workflow_step_reference,json=workflowStepReference,proto3" json:"workflow_step_reference,omitempty"`
	WorkflowId               string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowOwner            string                 `protobuf:"bytes,5,opt,name=workflow_owner,json=workflowOwner,proto3" json:"workflow_owner,omitempty"`
	WorkflowName             string                 `protobuf:"bytes,6,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	WorkflowDonId            uint32                 `protobuf:"varint,7,opt,name=workflow_don_id,json=workflowDonId,proto3" json:"workflow_don_id,omitempty"`
	WorkflowDonConfigVersion uint32                 `protobuf:"varint,8,opt,name=workflow_don_config_version,json=workflowDonConfigVersion,proto3" json:"workflow_don_config_version,omitempty"`
	ReportId                 string                 `protobuf:"bytes,9,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	KeyBundleId              string                 `protobuf:"bytes,10,opt,name=keyBundleId,proto3" json:"keyBundleId,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RequestMetaData) Reset() {
	*x = RequestMetaData{}
	mi := &file_value_consensus_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetaData) ProtoMessage() {}

func (x *RequestMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetaData.ProtoReflect.Descriptor instead.
func (*RequestMetaData) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetaData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowExecutionId() string {
	if x != nil {
		return x.WorkflowExecutionId
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowStepReference() string {
	if x != nil {
		return x.WorkflowStepReference
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowOwner() string {
	if x != nil {
		return x.WorkflowOwner
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowDonId() uint32 {
	if x != nil {
		return x.WorkflowDonId
	}
	return 0
}

func (x *RequestMetaData) GetWorkflowDonConfigVersion() uint32 {
	if x != nil {
		return x.WorkflowDonConfigVersion
	}
	return 0
}

func (x *RequestMetaData) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RequestMetaData) GetKeyBundleId() string {
	if x != nil {
		return x.KeyBundleId
	}
	return ""
}

type Request struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Metadata                   *RequestMetaData       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestConsensusDescriptor []byte                 `protobuf:"bytes,2,opt,name=request_consensus_descriptor,json=requestConsensusDescriptor,proto3" json:"request_consensus_descriptor,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_value_consensus_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetMetadata() *RequestMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetRequestConsensusDescriptor() []byte {
	if x != nil {
		return x.RequestConsensusDescriptor
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*Request             `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_value_consensus_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RequestObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetaData       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Observation   []byte                 `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestObservation) Reset() {
	*x = RequestObservation{}
	mi := &file_value_consensus_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestObservation) ProtoMessage() {}

func (x *RequestObservation) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestObservation.ProtoReflect.Descriptor instead.
func (*RequestObservation) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{3}
}

func (x *RequestObservation) GetMetadata() *RequestMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestObservation) GetObservation() []byte {
	if x != nil {
		return x.Observation
	}
	return nil
}

type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*RequestObservation  `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_value_consensus_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{4}
}

func (x *Observation) GetObservations() []*RequestObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

type RequestOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetaData       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Outcome       []byte                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOutcome) Reset() {
	*x = RequestOutcome{}
	mi := &file_value_consensus_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOutcome) ProtoMessage() {}

func (x *RequestOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOutcome.ProtoReflect.Descriptor instead.
func (*RequestOutcome) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{5}
}

func (x *RequestOutcome) GetMetadata() *RequestMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestOutcome) GetOutcome() []byte {
	if x != nil {
		return x.Outcome
	}
	return nil
}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcomes      []*RequestOutcome      `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_value_consensus_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{6}
}

func (x *Outcome) GetOutcomes() []*RequestOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

var File_value_consensus_types_proto protoreflect.FileDescriptor

const file_value_consensus_types_proto_rawDesc = "" +
	"\n" +
	"\x1bvalue_consensus_types.proto\x12\x15value_consensus_types\"\xaf\x03\n" +
	"\x0fRequestMetaData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\x15workflow_execution_id\x18\x02 \x01(\tR\x13workflowExecutionId\x126\n" +
	"\x17workflow_step_reference\x18\x03 \x01(\tR\x15workflowStepReference\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12%\n" +
	"\x0eworkflow_owner\x18\x05 \x01(\tR\rworkflowOwner\x12#\n" +
	"\rworkflow_name\x18\x06 \x01(\tR\fworkflowName\x12&\n" +
	"\x0fworkflow_don_id\x18\a \x01(\rR\rworkflowDonId\x12=\n" +
	"\x1bworkflow_don_config_version\x18\b \x01(\rR\x18workflowDonConfigVersion\x12\x1b\n" +
	"\treport_id\x18\t \x01(\tR\breportId\x12 \n" +
	"\vkeyBundleId\x18\n" +
	" \x01(\tR\vkeyBundleId\"\x8f\x01\n" +
	"\aRequest\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.value_consensus_types.RequestMetaDataR\bmetadata\x12@\n" +
	"\x1crequest_consensus_descriptor\x18\x02 \x01(\fR\x1arequestConsensusDescriptor\"C\n" +
	"\x05Query\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.value_consensus_types.RequestR\brequests\"z\n" +
	"\x12RequestObservation\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.value_consensus_types.RequestMetaDataR\bmetadata\x12 \n" +
	"\vobservation\x18\x02 \x01(\fR\vobservation\"\\\n" +
	"\vObservation\x12M\n" +
	"\fobservations\x18\x01 \x03(\v2).value_consensus_types.RequestObservationR\fobservations\"n\n" +
	"\x0eRequestOutcome\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.value_consensus_types.RequestMetaDataR\bmetadata\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\fR\aoutcome\"L\n" +
	"\aOutcome\x12A\n" +
	"\boutcomes\x18\x01 \x03(\v2%.value_consensus_types.RequestOutcomeR\boutcomesB\x18Z\x16consensus/oracle/typesb\x06proto3"

var (
	file_value_consensus_types_proto_rawDescOnce sync.Once
	file_value_consensus_types_proto_rawDescData []byte
)

func file_value_consensus_types_proto_rawDescGZIP() []byte {
	file_value_consensus_types_proto_rawDescOnce.Do(func() {
		file_value_consensus_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_value_consensus_types_proto_rawDesc), len(file_value_consensus_types_proto_rawDesc)))
	})
	return file_value_consensus_types_proto_rawDescData
}

var file_value_consensus_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_value_consensus_types_proto_goTypes = []any{
	(*RequestMetaData)(nil),    // 0: value_consensus_types.RequestMetaData
	(*Request)(nil),            // 1: value_consensus_types.Request
	(*Query)(nil),              // 2: value_consensus_types.Query
	(*RequestObservation)(nil), // 3: value_consensus_types.RequestObservation
	(*Observation)(nil),        // 4: value_consensus_types.Observation
	(*RequestOutcome)(nil),     // 5: value_consensus_types.RequestOutcome
	(*Outcome)(nil),            // 6: value_consensus_types.Outcome
}
var file_value_consensus_types_proto_depIdxs = []int32{
	0, // 0: value_consensus_types.Request.metadata:type_name -> value_consensus_types.RequestMetaData
	1, // 1: value_consensus_types.Query.requests:type_name -> value_consensus_types.Request
	0, // 2: value_consensus_types.RequestObservation.metadata:type_name -> value_consensus_types.RequestMetaData
	3, // 3: value_consensus_types.Observation.observations:type_name -> value_consensus_types.RequestObservation
	0, // 4: value_consensus_types.RequestOutcome.metadata:type_name -> value_consensus_types.RequestMetaData
	5, // 5: value_consensus_types.Outcome.outcomes:type_name -> value_consensus_types.RequestOutcome
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_value_consensus_types_proto_init() }
func file_value_consensus_types_proto_init() {
	if File_value_consensus_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_value_consensus_types_proto_rawDesc), len(file_value_consensus_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_consensus_types_proto_goTypes,
		DependencyIndexes: file_value_consensus_types_proto_depIdxs,
		MessageInfos:      file_value_consensus_types_proto_msgTypes,
	}.Build()
	File_value_consensus_types_proto = out.File
	file_value_consensus_types_proto_goTypes = nil
	file_value_consensus_types_proto_depIdxs = nil
}
