// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: value_consensus_types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_VALUE_CONSENSUS   RequestType = 0
	RequestType_REPORT_GENERATION RequestType = 1
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "VALUE_CONSENSUS",
		1: "REPORT_GENERATION",
	}
	RequestType_value = map[string]int32{
		"VALUE_CONSENSUS":   0,
		"REPORT_GENERATION": 1,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_value_consensus_types_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_value_consensus_types_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{0}
}

// TODO as part of https://smartcontract-it.atlassian.net/browse/CAPPL-1076 add additional statuses  (errored, failed etc.....):
type RequestStatus int32

const (
	RequestStatus_REQUEST_STATUS_CONSENSUS_SUCCESS RequestStatus = 0
	RequestStatus_REQUEST_STATUS_CONSENSUS_PENDING RequestStatus = 1
)

// Enum value maps for RequestStatus.
var (
	RequestStatus_name = map[int32]string{
		0: "REQUEST_STATUS_CONSENSUS_SUCCESS",
		1: "REQUEST_STATUS_CONSENSUS_PENDING",
	}
	RequestStatus_value = map[string]int32{
		"REQUEST_STATUS_CONSENSUS_SUCCESS": 0,
		"REQUEST_STATUS_CONSENSUS_PENDING": 1,
	}
)

func (x RequestStatus) Enum() *RequestStatus {
	p := new(RequestStatus)
	*p = x
	return p
}

func (x RequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_value_consensus_types_proto_enumTypes[1].Descriptor()
}

func (RequestStatus) Type() protoreflect.EnumType {
	return &file_value_consensus_types_proto_enumTypes[1]
}

func (x RequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestStatus.Descriptor instead.
func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{1}
}

type RequestMetaData struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RequestId                string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	WorkflowExecutionId      string                 `protobuf:"bytes,2,opt,name=workflow_execution_id,json=workflowExecutionId,proto3" json:"workflow_execution_id,omitempty"`
	WorkflowStepReference    string                 `protobuf:"bytes,3,opt,name=workflow_step_reference,json=workflowStepReference,proto3" json:"workflow_step_reference,omitempty"`
	WorkflowId               string                 `protobuf:"bytes,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowOwner            string                 `protobuf:"bytes,5,opt,name=workflow_owner,json=workflowOwner,proto3" json:"workflow_owner,omitempty"`
	WorkflowName             string                 `protobuf:"bytes,6,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	WorkflowDonId            uint32                 `protobuf:"varint,7,opt,name=workflow_don_id,json=workflowDonId,proto3" json:"workflow_don_id,omitempty"`
	WorkflowDonConfigVersion uint32                 `protobuf:"varint,8,opt,name=workflow_don_config_version,json=workflowDonConfigVersion,proto3" json:"workflow_don_config_version,omitempty"`
	ReportId                 string                 `protobuf:"bytes,9,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	KeyBundleId              string                 `protobuf:"bytes,10,opt,name=keyBundleId,proto3" json:"keyBundleId,omitempty"`
	RequestType              RequestType            `protobuf:"varint,11,opt,name=request_type,json=requestType,proto3,enum=value_consensus_types.RequestType" json:"request_type,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RequestMetaData) Reset() {
	*x = RequestMetaData{}
	mi := &file_value_consensus_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMetaData) ProtoMessage() {}

func (x *RequestMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMetaData.ProtoReflect.Descriptor instead.
func (*RequestMetaData) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMetaData) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowExecutionId() string {
	if x != nil {
		return x.WorkflowExecutionId
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowStepReference() string {
	if x != nil {
		return x.WorkflowStepReference
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowOwner() string {
	if x != nil {
		return x.WorkflowOwner
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RequestMetaData) GetWorkflowDonId() uint32 {
	if x != nil {
		return x.WorkflowDonId
	}
	return 0
}

func (x *RequestMetaData) GetWorkflowDonConfigVersion() uint32 {
	if x != nil {
		return x.WorkflowDonConfigVersion
	}
	return 0
}

func (x *RequestMetaData) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *RequestMetaData) GetKeyBundleId() string {
	if x != nil {
		return x.KeyBundleId
	}
	return ""
}

func (x *RequestMetaData) GetRequestType() RequestType {
	if x != nil {
		return x.RequestType
	}
	return RequestType_VALUE_CONSENSUS
}

type Request struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Metadata                   *RequestMetaData       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RequestConsensusDescriptor []byte                 `protobuf:"bytes,2,opt,name=request_consensus_descriptor,json=requestConsensusDescriptor,proto3" json:"request_consensus_descriptor,omitempty"`
	RequestDefault             []byte                 `protobuf:"bytes,3,opt,name=request_default,json=requestDefault,proto3" json:"request_default,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_value_consensus_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetMetadata() *RequestMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetRequestConsensusDescriptor() []byte {
	if x != nil {
		return x.RequestConsensusDescriptor
	}
	return nil
}

func (x *Request) GetRequestDefault() []byte {
	if x != nil {
		return x.RequestDefault
	}
	return nil
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*Request             `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_value_consensus_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{2}
}

func (x *Query) GetRequests() []*Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RequestObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetaData       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Observation   []byte                 `protobuf:"bytes,2,opt,name=observation,proto3" json:"observation,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestObservation) Reset() {
	*x = RequestObservation{}
	mi := &file_value_consensus_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestObservation) ProtoMessage() {}

func (x *RequestObservation) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestObservation.ProtoReflect.Descriptor instead.
func (*RequestObservation) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{3}
}

func (x *RequestObservation) GetMetadata() *RequestMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestObservation) GetObservation() []byte {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *RequestObservation) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type Observation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observations  []*RequestObservation  `protobuf:"bytes,1,rep,name=observations,proto3" json:"observations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_value_consensus_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{4}
}

func (x *Observation) GetObservations() []*RequestObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

type RequestOutcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *RequestMetaData       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Outcome       []byte                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        RequestStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=value_consensus_types.RequestStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOutcome) Reset() {
	*x = RequestOutcome{}
	mi := &file_value_consensus_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOutcome) ProtoMessage() {}

func (x *RequestOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOutcome.ProtoReflect.Descriptor instead.
func (*RequestOutcome) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{5}
}

func (x *RequestOutcome) GetMetadata() *RequestMetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestOutcome) GetOutcome() []byte {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *RequestOutcome) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RequestOutcome) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_CONSENSUS_SUCCESS
}

type HistoricalRequestOutcome struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status           RequestStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=value_consensus_types.RequestStatus" json:"status,omitempty"`
	FirstSeenAtSeqNr uint64                 `protobuf:"varint,3,opt,name=first_seen_at_seq_nr,json=firstSeenAtSeqNr,proto3" json:"first_seen_at_seq_nr,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HistoricalRequestOutcome) Reset() {
	*x = HistoricalRequestOutcome{}
	mi := &file_value_consensus_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricalRequestOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricalRequestOutcome) ProtoMessage() {}

func (x *HistoricalRequestOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricalRequestOutcome.ProtoReflect.Descriptor instead.
func (*HistoricalRequestOutcome) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{6}
}

func (x *HistoricalRequestOutcome) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HistoricalRequestOutcome) GetStatus() RequestStatus {
	if x != nil {
		return x.Status
	}
	return RequestStatus_REQUEST_STATUS_CONSENSUS_SUCCESS
}

func (x *HistoricalRequestOutcome) GetFirstSeenAtSeqNr() uint64 {
	if x != nil {
		return x.FirstSeenAtSeqNr
	}
	return 0
}

type Outcome struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Outcomes []*RequestOutcome      `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	// A record of recent historical request outcomes, expired based on the sequence number of the consensus round in which they were first seen.
	// It does not include the actual outcome data to save space in the plugin outcome.  (Note, this prevents it from being used by nodes to recover from
	// missed outcomes, but that is not a use case we currently support and there are different options to address this use case, i.e. a decentralised store)
	HistoricalOutcomes []*HistoricalRequestOutcome `protobuf:"bytes,2,rep,name=historical_outcomes,json=historicalOutcomes,proto3" json:"historical_outcomes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_value_consensus_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_value_consensus_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_value_consensus_types_proto_rawDescGZIP(), []int{7}
}

func (x *Outcome) GetOutcomes() []*RequestOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

func (x *Outcome) GetHistoricalOutcomes() []*HistoricalRequestOutcome {
	if x != nil {
		return x.HistoricalOutcomes
	}
	return nil
}

var File_value_consensus_types_proto protoreflect.FileDescriptor

const file_value_consensus_types_proto_rawDesc = "" +
	"\n" +
	"\x1bvalue_consensus_types.proto\x12\x15value_consensus_types\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x03\n" +
	"\x0fRequestMetaData\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\x15workflow_execution_id\x18\x02 \x01(\tR\x13workflowExecutionId\x126\n" +
	"\x17workflow_step_reference\x18\x03 \x01(\tR\x15workflowStepReference\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\tR\n" +
	"workflowId\x12%\n" +
	"\x0eworkflow_owner\x18\x05 \x01(\tR\rworkflowOwner\x12#\n" +
	"\rworkflow_name\x18\x06 \x01(\tR\fworkflowName\x12&\n" +
	"\x0fworkflow_don_id\x18\a \x01(\rR\rworkflowDonId\x12=\n" +
	"\x1bworkflow_don_config_version\x18\b \x01(\rR\x18workflowDonConfigVersion\x12\x1b\n" +
	"\treport_id\x18\t \x01(\tR\breportId\x12 \n" +
	"\vkeyBundleId\x18\n" +
	" \x01(\tR\vkeyBundleId\x12E\n" +
	"\frequest_type\x18\v \x01(\x0e2\".value_consensus_types.RequestTypeR\vrequestType\"\xb8\x01\n" +
	"\aRequest\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.value_consensus_types.RequestMetaDataR\bmetadata\x12@\n" +
	"\x1crequest_consensus_descriptor\x18\x02 \x01(\fR\x1arequestConsensusDescriptor\x12'\n" +
	"\x0frequest_default\x18\x03 \x01(\fR\x0erequestDefault\"C\n" +
	"\x05Query\x12:\n" +
	"\brequests\x18\x01 \x03(\v2\x1e.value_consensus_types.RequestR\brequests\"\xb7\x01\n" +
	"\x12RequestObservation\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.value_consensus_types.RequestMetaDataR\bmetadata\x12 \n" +
	"\vobservation\x18\x02 \x01(\fR\vobservation\x12;\n" +
	"\vreceived_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"\\\n" +
	"\vObservation\x12M\n" +
	"\fobservations\x18\x01 \x03(\v2).value_consensus_types.RequestObservationR\fobservations\"\xe6\x01\n" +
	"\x0eRequestOutcome\x12B\n" +
	"\bmetadata\x18\x01 \x01(\v2&.value_consensus_types.RequestMetaDataR\bmetadata\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\fR\aoutcome\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12<\n" +
	"\x06status\x18\x04 \x01(\x0e2$.value_consensus_types.RequestStatusR\x06status\"\xa7\x01\n" +
	"\x18HistoricalRequestOutcome\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12<\n" +
	"\x06status\x18\x02 \x01(\x0e2$.value_consensus_types.RequestStatusR\x06status\x12.\n" +
	"\x14first_seen_at_seq_nr\x18\x03 \x01(\x04R\x10firstSeenAtSeqNr\"\xae\x01\n" +
	"\aOutcome\x12A\n" +
	"\boutcomes\x18\x01 \x03(\v2%.value_consensus_types.RequestOutcomeR\boutcomes\x12`\n" +
	"\x13historical_outcomes\x18\x02 \x03(\v2/.value_consensus_types.HistoricalRequestOutcomeR\x12historicalOutcomes*9\n" +
	"\vRequestType\x12\x13\n" +
	"\x0fVALUE_CONSENSUS\x10\x00\x12\x15\n" +
	"\x11REPORT_GENERATION\x10\x01*[\n" +
	"\rRequestStatus\x12$\n" +
	" REQUEST_STATUS_CONSENSUS_SUCCESS\x10\x00\x12$\n" +
	" REQUEST_STATUS_CONSENSUS_PENDING\x10\x01B\x18Z\x16consensus/oracle/typesb\x06proto3"

var (
	file_value_consensus_types_proto_rawDescOnce sync.Once
	file_value_consensus_types_proto_rawDescData []byte
)

func file_value_consensus_types_proto_rawDescGZIP() []byte {
	file_value_consensus_types_proto_rawDescOnce.Do(func() {
		file_value_consensus_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_value_consensus_types_proto_rawDesc), len(file_value_consensus_types_proto_rawDesc)))
	})
	return file_value_consensus_types_proto_rawDescData
}

var file_value_consensus_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_value_consensus_types_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_value_consensus_types_proto_goTypes = []any{
	(RequestType)(0),                 // 0: value_consensus_types.RequestType
	(RequestStatus)(0),               // 1: value_consensus_types.RequestStatus
	(*RequestMetaData)(nil),          // 2: value_consensus_types.RequestMetaData
	(*Request)(nil),                  // 3: value_consensus_types.Request
	(*Query)(nil),                    // 4: value_consensus_types.Query
	(*RequestObservation)(nil),       // 5: value_consensus_types.RequestObservation
	(*Observation)(nil),              // 6: value_consensus_types.Observation
	(*RequestOutcome)(nil),           // 7: value_consensus_types.RequestOutcome
	(*HistoricalRequestOutcome)(nil), // 8: value_consensus_types.HistoricalRequestOutcome
	(*Outcome)(nil),                  // 9: value_consensus_types.Outcome
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
}
var file_value_consensus_types_proto_depIdxs = []int32{
	0,  // 0: value_consensus_types.RequestMetaData.request_type:type_name -> value_consensus_types.RequestType
	2,  // 1: value_consensus_types.Request.metadata:type_name -> value_consensus_types.RequestMetaData
	3,  // 2: value_consensus_types.Query.requests:type_name -> value_consensus_types.Request
	2,  // 3: value_consensus_types.RequestObservation.metadata:type_name -> value_consensus_types.RequestMetaData
	10, // 4: value_consensus_types.RequestObservation.received_at:type_name -> google.protobuf.Timestamp
	5,  // 5: value_consensus_types.Observation.observations:type_name -> value_consensus_types.RequestObservation
	2,  // 6: value_consensus_types.RequestOutcome.metadata:type_name -> value_consensus_types.RequestMetaData
	10, // 7: value_consensus_types.RequestOutcome.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 8: value_consensus_types.RequestOutcome.status:type_name -> value_consensus_types.RequestStatus
	1,  // 9: value_consensus_types.HistoricalRequestOutcome.status:type_name -> value_consensus_types.RequestStatus
	7,  // 10: value_consensus_types.Outcome.outcomes:type_name -> value_consensus_types.RequestOutcome
	8,  // 11: value_consensus_types.Outcome.historical_outcomes:type_name -> value_consensus_types.HistoricalRequestOutcome
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_value_consensus_types_proto_init() }
func file_value_consensus_types_proto_init() {
	if File_value_consensus_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_value_consensus_types_proto_rawDesc), len(file_value_consensus_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_value_consensus_types_proto_goTypes,
		DependencyIndexes: file_value_consensus_types_proto_depIdxs,
		EnumInfos:         file_value_consensus_types_proto_enumTypes,
		MessageInfos:      file_value_consensus_types_proto_msgTypes,
	}.Build()
	File_value_consensus_types_proto = out.File
	file_value_consensus_types_proto_goTypes = nil
	file_value_consensus_types_proto_depIdxs = nil
}
