// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package confidential_http_actiontest

import (
	"github.com/smartcontractkit/capabilities/confidential_http_action"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/testutils"
)

// HttpAction registers a new capability mock with the runner
// if another mock is registered for the same capability with for a step, it will take priority for that step.
func HttpAction(runner *testutils.Runner, fn func(input confidential_http_action.Input) (Output, error)) *testutils.Mock[confidential_http_action.Input, Output] {
	mock := testutils.MockCapability[confidential_http_action.Input, Output]("confidential-http-action@1.0.0", fn)
	runner.MockCapability("confidential-http-action@1.0.0", nil, mock)
	return mock
}

// HttpActionForStep registers a new capability mock with the runner, but only for a given step.
// if another mock was registered for the same capability without a step, this mock will take priority for that step.
func HttpActionForStep(runner *testutils.Runner, step string, mockFn func(input confidential_http_action.Input) (Output, error)) *testutils.Mock[confidential_http_action.Input, Output] {
	fn := mockFn
	mock := testutils.MockCapability[confidential_http_action.Input, Output]("confidential-http-action@1.0.0", fn)
	runner.MockCapability("confidential-http-action@1.0.0", &step, mock)
	return mock
}
