// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package signcap

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg ActionConfig) New(w *sdk.WorkflowSpecFactory, ref string, input ActionInput) OutputsCap {

	def := sdk.StepDefinition{
		ID: "sign-action@1.0.0", Ref: ref,
		Inputs: input.ToSteps(),
		Config: map[string]any{
			"privateKey": cfg.PrivateKey,
		},
		CapabilityType: capabilities.CapabilityTypeAction,
	}

	step := sdk.Step[Outputs]{Definition: def}
	return OutputsCapFromStep(w, step)
}

type OutputsCap interface {
	sdk.CapDefinition[Outputs]
	Sig() sdk.CapDefinition[[]uint8]
	private()
}

// OutputsCapFromStep should only be called from generated code to assure type safety
func OutputsCapFromStep(w *sdk.WorkflowSpecFactory, step sdk.Step[Outputs]) OutputsCap {
	raw := step.AddTo(w)
	return &outputs{CapDefinition: raw}
}

type outputs struct {
	sdk.CapDefinition[Outputs]
}

func (*outputs) private() {}
func (c *outputs) Sig() sdk.CapDefinition[[]uint8] {
	return sdk.AccessField[Outputs, []uint8](c.CapDefinition, "sig")
}

func NewOutputsFromFields(
	sig sdk.CapDefinition[[]uint8]) OutputsCap {
	return &simpleOutputs{
		CapDefinition: sdk.ComponentCapDefinition[Outputs]{
			"sig": sig.Ref(),
		},
		sig: sig,
	}
}

type simpleOutputs struct {
	sdk.CapDefinition[Outputs]
	sig sdk.CapDefinition[[]uint8]
}

func (c *simpleOutputs) Sig() sdk.CapDefinition[[]uint8] {
	return c.sig
}

func (c *simpleOutputs) private() {}

type ActionInput struct {
	Data sdk.CapDefinition[[]uint8]
}

func (input ActionInput) ToSteps() sdk.StepInputs {
	return sdk.StepInputs{
		Mapping: map[string]any{
			"data": input.Data.Ref(),
		},
	}
}
