// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package signcap

import (
	"encoding/json"
	"fmt"
)

// Key-Value Store Target
type Action struct {
	// Provide a private key to sign.
	Config ActionConfig `json:"config" yaml:"config" mapstructure:"config"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs Inputs `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs Outputs `json:"outputs" yaml:"outputs" mapstructure:"outputs"`
}

// Provide a private key to sign.
type ActionConfig struct {
	// PrivateKey corresponds to the JSON schema field "privateKey".
	PrivateKey string `json:"privateKey" yaml:"privateKey" mapstructure:"privateKey"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ActionConfig) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["privateKey"]; raw != nil && !ok {
		return fmt.Errorf("field privateKey in ActionConfig: required")
	}
	type Plain ActionConfig
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ActionConfig(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Action) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["config"]; raw != nil && !ok {
		return fmt.Errorf("field config in Action: required")
	}
	if _, ok := raw["inputs"]; raw != nil && !ok {
		return fmt.Errorf("field inputs in Action: required")
	}
	if _, ok := raw["outputs"]; raw != nil && !ok {
		return fmt.Errorf("field outputs in Action: required")
	}
	type Plain Action
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Action(plain)
	return nil
}

// Input parameters for the signing Action.
type Inputs struct {
	// Data to sign.
	Data []uint8 `json:"data,omitempty" yaml:"data,omitempty" mapstructure:"data,omitempty"`
}

// Output parameters for the Key-Value Store Read Action.
type Outputs struct {
	// Signature.
	Sig []uint8 `json:"sig" yaml:"sig" mapstructure:"sig"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Outputs) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["sig"]; raw != nil && !ok {
		return fmt.Errorf("field sig in Outputs: required")
	}
	type Plain Outputs
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Outputs(plain)
	return nil
}
