name: "Set up project environment"
description: "Sets up Go and NX"

inputs:
  cache-version:
    description: Set this to cache bust
    default: "1"
  go-module-file:
    description: Set where the go module file is located at
    required: true
  project:
    description: Project to set up
    required: true
  task:
    description: Task that will run. Used for caching purposes.
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # 5.0.2
      with:
        go-version: ${{ env.GO_VERSION }}
        # We are doing custom caching, so we don't need the default caching
        cache: false
    - name: Install protoc-gen-go grpc
      shell: bash
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.7
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
    - name: Install protoc
      shell: bash
      run: |
        PROTOC_VERSION=29.3
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
        unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d protoc3
        sudo mv protoc3/bin/* /usr/local/bin/
        sudo mv protoc3/include/* /usr/local/include/
        rm -rf protoc3 protoc-${PROTOC_VERSION}-linux-x86_64.zip
    - name: Cache NX
      uses: actions/cache@v4
      with:
        path: |
          .nx
          ~/.npm
        key: ${{runner.os}}-nx

    - name: Setup nodejs and install nx
      uses: smartcontractkit/.github/actions/setup-nodejs@setup-nodejs/v1

    - name: Set up Go cache keys
      id: init
      shell: bash
      run: |
        npx nx@19.8.2 init
        echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
        echo "gobuildcache=$(go env GOCACHE)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Cache Go modules and outputs
      with:
        path: |
          ${{ steps.init.outputs.gomodcache }}
          ${{ steps.init.outputs.gobuildcache }}
        key: ${{runner.os}}-${{inputs.cache-version}}-${{inputs.project}}-${{inputs.task}}-gomod-${{hashFiles(inputs.go-module-file)}}
        restore-keys: |
          ${{runner.os}}-${{inputs.cache-version}}-${{inputs.project}}-${{inputs.task}}
        save-always: true
