.PHONY: gomods
gomods: ## Install gomods
	go install github.com/jmank88/gomods@v0.1.4

.PHONY: gomodtidy
gomodtidy: gomods
	# didn't work... gomods tidy
	cd capabilities && go mod tidy && cd cron && go mod tidy && cd ../kvstore && go mod tidy && cd ../../libs/types && go mod tidy

.PHONY: generate
generate: gomods
	# didn't work... gomods -w go generate -x ./...
	cd capabilities && go generate -x ./... && cd cron && go generate -x ./... && cd ../kvstore && go generate -x ./... && cd ../../libs/types && go generate -x ./...

.PHONY: rm-generated
rm-generated:
	grep -rl "^// Code generated by "| xargs -r rm
