# projectKey is required (may be found under "Project Information" in Sonar or in project url)
sonar.projectKey=smartcontractkit_capabilities
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Full exclusions from the static analysis
sonar.exclusions=\
**/mocks/**/*,\
**/mock_*.go,\
**/testdata/**/*,\
**/script/**/*,\
**/generated/**/*,\
**/gen.go,\
**/generated_*.go,\
**/*_generated.go,\
**/fixtures/**/*,\
**/docs/**/*,\
**/tools/**/*,\
**/testutils/**/*,\
**/*.pb.go,\
**/*report.xml,\
**/*.sol,\
**/*.txt,\
**/*.abi,\
**/*.bin

# Coverage exclusions
sonar.coverage.exclusions=\
**/devenv/**/*,\
**/test/**/*,\
**/fuzz/**/*,\
**/integration_tests/**/*,\
**/*test/**/*,\
**/*_test.go,\
**/main.go

# Sonar duplications exclusions
# We should not need to deduplicate workflows/**/main.go files
sonar.cpd.exclusions=\
**/workflows/**/main.go,\
**/integration_tests/**/*

# Tests' root folder, inclusions (tests to check and count) and exclusions
sonar.tests=.
sonar.test.inclusions=**/*_test.go
