// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvcap

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	ocr3cap "github.com/smartcontractkit/chainlink-common/pkg/capabilities/consensus/ocr3/ocr3cap"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg WriteTargetConfig) New(w *sdk.WorkflowSpecFactory, input WriteTargetInput) {

	def := sdk.StepDefinition{
		ID:             "kv-store-target@1.0.0",
		Inputs:         input.ToSteps(),
		Config:         map[string]any{},
		CapabilityType: capabilities.CapabilityTypeTarget,
	}

	step := sdk.Step[struct{}]{Definition: def}
	step.AddTo(w)
}

type WriteTargetInput struct {
	SignedReport sdk.CapDefinition[ocr3cap.SignedReport]
}

func (input WriteTargetInput) ToSteps() sdk.StepInputs {
	return sdk.StepInputs{
		Mapping: map[string]any{
			"signedReport": input.SignedReport.Ref(),
		},
	}
}
