// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvreadcaptest

import (
	"github.com/smartcontractkit/capabilities/kvstore/kvreadcap"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/testutils"
)

// ReadAction registers a new capability mock with the runner
// if another mock is registered for the same capability with for a step, it will take priority for that step.
func ReadAction(runner *testutils.Runner, fn func(input kvreadcap.Inputs) (kvreadcap.Outputs, error)) *testutils.Mock[kvreadcap.Inputs, kvreadcap.Outputs] {
	mock := testutils.MockCapability[kvreadcap.Inputs, kvreadcap.Outputs]("kv-store-action@1.0.0", fn)
	runner.MockCapability("kv-store-action@1.0.0", nil, mock)
	return mock
}

// ReadActionForStep registers a new capability mock with the runner, but only for a given step.
// if another mock was registered for the same capability without a step, this mock will take priority for that step.
func ReadActionForStep(runner *testutils.Runner, step string, mockFn func(input kvreadcap.Inputs) (kvreadcap.Outputs, error)) *testutils.Mock[kvreadcap.Inputs, kvreadcap.Outputs] {
	fn := mockFn
	mock := testutils.MockCapability[kvreadcap.Inputs, kvreadcap.Outputs]("kv-store-action@1.0.0", fn)
	runner.MockCapability("kv-store-action@1.0.0", &step, mock)
	return mock
}
