// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: chain_capabilities/solana/monitoring/write_report.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteReportInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportInitiated) Reset() {
	*x = WriteReportInitiated{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportInitiated) ProtoMessage() {}

func (x *WriteReportInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportInitiated.ProtoReflect.Descriptor instead.
func (*WriteReportInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{0}
}

func (x *WriteReportInitiated) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	LogCount         int32                        `protobuf:"varint,2,opt,name=log_count,json=logCount,proto3" json:"log_count,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportSuccess) Reset() {
	*x = WriteReportSuccess{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportSuccess) ProtoMessage() {}

func (x *WriteReportSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportSuccess.ProtoReflect.Descriptor instead.
func (*WriteReportSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{1}
}

func (x *WriteReportSuccess) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportSuccess) GetLogCount() int32 {
	if x != nil {
		return x.LogCount
	}
	return 0
}

func (x *WriteReportSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	IsUserError      bool                         `protobuf:"varint,4,opt,name=isUserError,proto3" json:"isUserError,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportError) Reset() {
	*x = WriteReportError{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportError) ProtoMessage() {}

func (x *WriteReportError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportError.ProtoReflect.Descriptor instead.
func (*WriteReportError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{2}
}

func (x *WriteReportError) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteReportError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteReportError) GetIsUserError() bool {
	if x != nil {
		return x.IsUserError
	}
	return false
}

func (x *WriteReportError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RemainingAccounts []*AccountMeta         `protobuf:"bytes,1,rep,name=remaining_accounts,json=remainingAccounts,proto3" json:"remaining_accounts,omitempty"` // accounts that are required by the receiver to accept the report
	Receiver          []byte                 `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`                                            // 32 bytes receiver
	ComputeConfig     *ComputeConfig         `protobuf:"bytes,3,opt,name=compute_config,json=computeConfig,proto3,oneof" json:"compute_config,omitempty"`
	Report            *ReportResponse        `protobuf:"bytes,4,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WriteReportRequest) Reset() {
	*x = WriteReportRequest{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportRequest) ProtoMessage() {}

func (x *WriteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportRequest.ProtoReflect.Descriptor instead.
func (*WriteReportRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{3}
}

func (x *WriteReportRequest) GetRemainingAccounts() []*AccountMeta {
	if x != nil {
		return x.RemainingAccounts
	}
	return nil
}

func (x *WriteReportRequest) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *WriteReportRequest) GetComputeConfig() *ComputeConfig {
	if x != nil {
		return x.ComputeConfig
	}
	return nil
}

func (x *WriteReportRequest) GetReport() *ReportResponse {
	if x != nil {
		return x.Report
	}
	return nil
}

// All metas are non-signers.
type AccountMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`     // 32 bytes account public key
	IsWritable    bool                   `protobuf:"varint,2,opt,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"` // write flag
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountMeta) Reset() {
	*x = AccountMeta{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMeta) ProtoMessage() {}

func (x *AccountMeta) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMeta.ProtoReflect.Descriptor instead.
func (*AccountMeta) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{4}
}

func (x *AccountMeta) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AccountMeta) GetIsWritable() bool {
	if x != nil {
		return x.IsWritable
	}
	return false
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest  []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	SeqNr         uint64                 `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	ReportContext []byte                 `protobuf:"bytes,3,opt,name=report_context,json=reportContext,proto3" json:"report_context,omitempty"` // combination of seq_nr and config_digest
	RawReport     []byte                 `protobuf:"bytes,4,opt,name=raw_report,json=rawReport,proto3" json:"raw_report,omitempty"`
	Sigs          []*AttributedSignature `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{5}
}

func (x *ReportResponse) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *ReportResponse) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *ReportResponse) GetReportContext() []byte {
	if x != nil {
		return x.ReportContext
	}
	return nil
}

func (x *ReportResponse) GetRawReport() []byte {
	if x != nil {
		return x.RawReport
	}
	return nil
}

func (x *ReportResponse) GetSigs() []*AttributedSignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type ComputeConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ComputeLimit    uint32                 `protobuf:"varint,1,opt,name=compute_limit,json=computeLimit,proto3" json:"compute_limit,omitempty"`            // max CUs (approx per-tx limit)
	ComputeMaxPrice uint64                 `protobuf:"varint,2,opt,name=compute_max_price,json=computeMaxPrice,proto3" json:"compute_max_price,omitempty"` // max lamports per CU
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComputeConfig) Reset() {
	*x = ComputeConfig{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeConfig) ProtoMessage() {}

func (x *ComputeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeConfig.ProtoReflect.Descriptor instead.
func (*ComputeConfig) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{6}
}

func (x *ComputeConfig) GetComputeLimit() uint32 {
	if x != nil {
		return x.ComputeLimit
	}
	return 0
}

func (x *ComputeConfig) GetComputeMaxPrice() uint64 {
	if x != nil {
		return x.ComputeMaxPrice
	}
	return 0
}

type AttributedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	SignerId      uint32                 `protobuf:"varint,2,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedSignature) Reset() {
	*x = AttributedSignature{}
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedSignature) ProtoMessage() {}

func (x *AttributedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedSignature.ProtoReflect.Descriptor instead.
func (*AttributedSignature) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP(), []int{7}
}

func (x *AttributedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AttributedSignature) GetSignerId() uint32 {
	if x != nil {
		return x.SignerId
	}
	return 0
}

var File_chain_capabilities_solana_monitoring_write_report_proto protoreflect.FileDescriptor

const file_chain_capabilities_solana_monitoring_write_report_proto_rawDesc = "" +
	"\n" +
	"7chain_capabilities/solana/monitoring/write_report.proto\x12\x19chain_capabilities.solana\x1a'libs/monitoring/execution_context.proto\"\xa2\x01\n" +
	"\x14WriteReportInitiated\x12?\n" +
	"\x03req\x18\x01 \x01(\v2-.chain_capabilities.solana.WriteReportRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xbd\x01\n" +
	"\x12WriteReportSuccess\x12?\n" +
	"\x03req\x18\x01 \x01(\v2-.chain_capabilities.solana.WriteReportRequestR\x03req\x12\x1b\n" +
	"\tlog_count\x18\x02 \x01(\x05R\blogCount\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xf0\x01\n" +
	"\x10WriteReportError\x12?\n" +
	"\x03req\x18\x01 \x01(\v2-.chain_capabilities.solana.WriteReportRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12 \n" +
	"\visUserError\x18\x04 \x01(\bR\visUserError\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xb3\x02\n" +
	"\x12WriteReportRequest\x12U\n" +
	"\x12remaining_accounts\x18\x01 \x03(\v2&.chain_capabilities.solana.AccountMetaR\x11remainingAccounts\x12\x1a\n" +
	"\breceiver\x18\x02 \x01(\fR\breceiver\x12T\n" +
	"\x0ecompute_config\x18\x03 \x01(\v2(.chain_capabilities.solana.ComputeConfigH\x00R\rcomputeConfig\x88\x01\x01\x12A\n" +
	"\x06report\x18\x04 \x01(\v2).chain_capabilities.solana.ReportResponseR\x06reportB\x11\n" +
	"\x0f_compute_config\"M\n" +
	"\vAccountMeta\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\vis_writable\x18\x02 \x01(\bR\n" +
	"isWritable\"\xd6\x01\n" +
	"\x0eReportResponse\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x04R\x05seqNr\x12%\n" +
	"\x0ereport_context\x18\x03 \x01(\fR\rreportContext\x12\x1d\n" +
	"\n" +
	"raw_report\x18\x04 \x01(\fR\trawReport\x12B\n" +
	"\x04sigs\x18\x05 \x03(\v2..chain_capabilities.solana.AttributedSignatureR\x04sigs\"`\n" +
	"\rComputeConfig\x12#\n" +
	"\rcompute_limit\x18\x01 \x01(\rR\fcomputeLimit\x12*\n" +
	"\x11compute_max_price\x18\x02 \x01(\x04R\x0fcomputeMaxPrice\"P\n" +
	"\x13AttributedSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigner_id\x18\x02 \x01(\rR\bsignerIdBOZMgithub.com/smartcontractkit/capabilities/chain_capabilities/solana;monitoringb\x06proto3"

var (
	file_chain_capabilities_solana_monitoring_write_report_proto_rawDescOnce sync.Once
	file_chain_capabilities_solana_monitoring_write_report_proto_rawDescData []byte
)

func file_chain_capabilities_solana_monitoring_write_report_proto_rawDescGZIP() []byte {
	file_chain_capabilities_solana_monitoring_write_report_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_solana_monitoring_write_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_solana_monitoring_write_report_proto_rawDesc), len(file_chain_capabilities_solana_monitoring_write_report_proto_rawDesc)))
	})
	return file_chain_capabilities_solana_monitoring_write_report_proto_rawDescData
}

var file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_chain_capabilities_solana_monitoring_write_report_proto_goTypes = []any{
	(*WriteReportInitiated)(nil),        // 0: chain_capabilities.solana.WriteReportInitiated
	(*WriteReportSuccess)(nil),          // 1: chain_capabilities.solana.WriteReportSuccess
	(*WriteReportError)(nil),            // 2: chain_capabilities.solana.WriteReportError
	(*WriteReportRequest)(nil),          // 3: chain_capabilities.solana.WriteReportRequest
	(*AccountMeta)(nil),                 // 4: chain_capabilities.solana.AccountMeta
	(*ReportResponse)(nil),              // 5: chain_capabilities.solana.ReportResponse
	(*ComputeConfig)(nil),               // 6: chain_capabilities.solana.ComputeConfig
	(*AttributedSignature)(nil),         // 7: chain_capabilities.solana.AttributedSignature
	(*monitoring.ExecutionContext)(nil), // 8: monitoring.ExecutionContext
}
var file_chain_capabilities_solana_monitoring_write_report_proto_depIdxs = []int32{
	3,  // 0: chain_capabilities.solana.WriteReportInitiated.req:type_name -> chain_capabilities.solana.WriteReportRequest
	8,  // 1: chain_capabilities.solana.WriteReportInitiated.execution_context:type_name -> monitoring.ExecutionContext
	3,  // 2: chain_capabilities.solana.WriteReportSuccess.req:type_name -> chain_capabilities.solana.WriteReportRequest
	8,  // 3: chain_capabilities.solana.WriteReportSuccess.execution_context:type_name -> monitoring.ExecutionContext
	3,  // 4: chain_capabilities.solana.WriteReportError.req:type_name -> chain_capabilities.solana.WriteReportRequest
	8,  // 5: chain_capabilities.solana.WriteReportError.execution_context:type_name -> monitoring.ExecutionContext
	4,  // 6: chain_capabilities.solana.WriteReportRequest.remaining_accounts:type_name -> chain_capabilities.solana.AccountMeta
	6,  // 7: chain_capabilities.solana.WriteReportRequest.compute_config:type_name -> chain_capabilities.solana.ComputeConfig
	5,  // 8: chain_capabilities.solana.WriteReportRequest.report:type_name -> chain_capabilities.solana.ReportResponse
	7,  // 9: chain_capabilities.solana.ReportResponse.sigs:type_name -> chain_capabilities.solana.AttributedSignature
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chain_capabilities_solana_monitoring_write_report_proto_init() }
func file_chain_capabilities_solana_monitoring_write_report_proto_init() {
	if File_chain_capabilities_solana_monitoring_write_report_proto != nil {
		return
	}
	file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_solana_monitoring_write_report_proto_rawDesc), len(file_chain_capabilities_solana_monitoring_write_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_capabilities_solana_monitoring_write_report_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_solana_monitoring_write_report_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_solana_monitoring_write_report_proto_msgTypes,
	}.Build()
	File_chain_capabilities_solana_monitoring_write_report_proto = out.File
	file_chain_capabilities_solana_monitoring_write_report_proto_goTypes = nil
	file_chain_capabilities_solana_monitoring_write_report_proto_depIdxs = nil
}
