// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/smartcontractkit/capabilities/libs/chainconsensus/types"
	mock "github.com/stretchr/testify/mock"
)

// ConsensusMetrics is an autogenerated mock type for the ConsensusMetrics type
type ConsensusMetrics struct {
	mock.Mock
}

type ConsensusMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsensusMetrics) EXPECT() *ConsensusMetrics_Expecter {
	return &ConsensusMetrics_Expecter{mock: &_m.Mock}
}

// RecordIdenticalResponseCount provides a mock function with given fields: ctx, count, observationType
func (_m *ConsensusMetrics) RecordIdenticalResponseCount(ctx context.Context, count int, observationType string) {
	_m.Called(ctx, count, observationType)
}

// ConsensusMetrics_RecordIdenticalResponseCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordIdenticalResponseCount'
type ConsensusMetrics_RecordIdenticalResponseCount_Call struct {
	*mock.Call
}

// RecordIdenticalResponseCount is a helper method to define mock.On call
//   - ctx context.Context
//   - count int
//   - observationType string
func (_e *ConsensusMetrics_Expecter) RecordIdenticalResponseCount(ctx interface{}, count interface{}, observationType interface{}) *ConsensusMetrics_RecordIdenticalResponseCount_Call {
	return &ConsensusMetrics_RecordIdenticalResponseCount_Call{Call: _e.mock.On("RecordIdenticalResponseCount", ctx, count, observationType)}
}

func (_c *ConsensusMetrics_RecordIdenticalResponseCount_Call) Run(run func(ctx context.Context, count int, observationType string)) *ConsensusMetrics_RecordIdenticalResponseCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *ConsensusMetrics_RecordIdenticalResponseCount_Call) Return() *ConsensusMetrics_RecordIdenticalResponseCount_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_RecordIdenticalResponseCount_Call) RunAndReturn(run func(context.Context, int, string)) *ConsensusMetrics_RecordIdenticalResponseCount_Call {
	_c.Run(run)
	return _c
}

// RecordOutcomeChainHeight provides a mock function with given fields: ctx, height
func (_m *ConsensusMetrics) RecordOutcomeChainHeight(ctx context.Context, height *types.ChainHeight) {
	_m.Called(ctx, height)
}

// ConsensusMetrics_RecordOutcomeChainHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordOutcomeChainHeight'
type ConsensusMetrics_RecordOutcomeChainHeight_Call struct {
	*mock.Call
}

// RecordOutcomeChainHeight is a helper method to define mock.On call
//   - ctx context.Context
//   - height *types.ChainHeight
func (_e *ConsensusMetrics_Expecter) RecordOutcomeChainHeight(ctx interface{}, height interface{}) *ConsensusMetrics_RecordOutcomeChainHeight_Call {
	return &ConsensusMetrics_RecordOutcomeChainHeight_Call{Call: _e.mock.On("RecordOutcomeChainHeight", ctx, height)}
}

func (_c *ConsensusMetrics_RecordOutcomeChainHeight_Call) Run(run func(ctx context.Context, height *types.ChainHeight)) *ConsensusMetrics_RecordOutcomeChainHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.ChainHeight))
	})
	return _c
}

func (_c *ConsensusMetrics_RecordOutcomeChainHeight_Call) Return() *ConsensusMetrics_RecordOutcomeChainHeight_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_RecordOutcomeChainHeight_Call) RunAndReturn(run func(context.Context, *types.ChainHeight)) *ConsensusMetrics_RecordOutcomeChainHeight_Call {
	_c.Run(run)
	return _c
}

// RecordQueueSize provides a mock function with given fields: ctx, size
func (_m *ConsensusMetrics) RecordQueueSize(ctx context.Context, size int) {
	_m.Called(ctx, size)
}

// ConsensusMetrics_RecordQueueSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordQueueSize'
type ConsensusMetrics_RecordQueueSize_Call struct {
	*mock.Call
}

// RecordQueueSize is a helper method to define mock.On call
//   - ctx context.Context
//   - size int
func (_e *ConsensusMetrics_Expecter) RecordQueueSize(ctx interface{}, size interface{}) *ConsensusMetrics_RecordQueueSize_Call {
	return &ConsensusMetrics_RecordQueueSize_Call{Call: _e.mock.On("RecordQueueSize", ctx, size)}
}

func (_c *ConsensusMetrics_RecordQueueSize_Call) Run(run func(ctx context.Context, size int)) *ConsensusMetrics_RecordQueueSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ConsensusMetrics_RecordQueueSize_Call) Return() *ConsensusMetrics_RecordQueueSize_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_RecordQueueSize_Call) RunAndReturn(run func(context.Context, int)) *ConsensusMetrics_RecordQueueSize_Call {
	_c.Run(run)
	return _c
}

// RecordRequestObservationSize provides a mock function with given fields: ctx, size
func (_m *ConsensusMetrics) RecordRequestObservationSize(ctx context.Context, size int) {
	_m.Called(ctx, size)
}

// ConsensusMetrics_RecordRequestObservationSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRequestObservationSize'
type ConsensusMetrics_RecordRequestObservationSize_Call struct {
	*mock.Call
}

// RecordRequestObservationSize is a helper method to define mock.On call
//   - ctx context.Context
//   - size int
func (_e *ConsensusMetrics_Expecter) RecordRequestObservationSize(ctx interface{}, size interface{}) *ConsensusMetrics_RecordRequestObservationSize_Call {
	return &ConsensusMetrics_RecordRequestObservationSize_Call{Call: _e.mock.On("RecordRequestObservationSize", ctx, size)}
}

func (_c *ConsensusMetrics_RecordRequestObservationSize_Call) Run(run func(ctx context.Context, size int)) *ConsensusMetrics_RecordRequestObservationSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ConsensusMetrics_RecordRequestObservationSize_Call) Return() *ConsensusMetrics_RecordRequestObservationSize_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_RecordRequestObservationSize_Call) RunAndReturn(run func(context.Context, int)) *ConsensusMetrics_RecordRequestObservationSize_Call {
	_c.Run(run)
	return _c
}

// RecordRetryQueueSize provides a mock function with given fields: ctx, size
func (_m *ConsensusMetrics) RecordRetryQueueSize(ctx context.Context, size int) {
	_m.Called(ctx, size)
}

// ConsensusMetrics_RecordRetryQueueSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRetryQueueSize'
type ConsensusMetrics_RecordRetryQueueSize_Call struct {
	*mock.Call
}

// RecordRetryQueueSize is a helper method to define mock.On call
//   - ctx context.Context
//   - size int
func (_e *ConsensusMetrics_Expecter) RecordRetryQueueSize(ctx interface{}, size interface{}) *ConsensusMetrics_RecordRetryQueueSize_Call {
	return &ConsensusMetrics_RecordRetryQueueSize_Call{Call: _e.mock.On("RecordRetryQueueSize", ctx, size)}
}

func (_c *ConsensusMetrics_RecordRetryQueueSize_Call) Run(run func(ctx context.Context, size int)) *ConsensusMetrics_RecordRetryQueueSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ConsensusMetrics_RecordRetryQueueSize_Call) Return() *ConsensusMetrics_RecordRetryQueueSize_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_RecordRetryQueueSize_Call) RunAndReturn(run func(context.Context, int)) *ConsensusMetrics_RecordRetryQueueSize_Call {
	_c.Run(run)
	return _c
}

// RecordRoundObservationSize provides a mock function with given fields: ctx, size
func (_m *ConsensusMetrics) RecordRoundObservationSize(ctx context.Context, size int) {
	_m.Called(ctx, size)
}

// ConsensusMetrics_RecordRoundObservationSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordRoundObservationSize'
type ConsensusMetrics_RecordRoundObservationSize_Call struct {
	*mock.Call
}

// RecordRoundObservationSize is a helper method to define mock.On call
//   - ctx context.Context
//   - size int
func (_e *ConsensusMetrics_Expecter) RecordRoundObservationSize(ctx interface{}, size interface{}) *ConsensusMetrics_RecordRoundObservationSize_Call {
	return &ConsensusMetrics_RecordRoundObservationSize_Call{Call: _e.mock.On("RecordRoundObservationSize", ctx, size)}
}

func (_c *ConsensusMetrics_RecordRoundObservationSize_Call) Run(run func(ctx context.Context, size int)) *ConsensusMetrics_RecordRoundObservationSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *ConsensusMetrics_RecordRoundObservationSize_Call) Return() *ConsensusMetrics_RecordRoundObservationSize_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_RecordRoundObservationSize_Call) RunAndReturn(run func(context.Context, int)) *ConsensusMetrics_RecordRoundObservationSize_Call {
	_c.Run(run)
	return _c
}

// SetRequestCount provides a mock function with given fields: requestCount
func (_m *ConsensusMetrics) SetRequestCount(requestCount int) {
	_m.Called(requestCount)
}

// ConsensusMetrics_SetRequestCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRequestCount'
type ConsensusMetrics_SetRequestCount_Call struct {
	*mock.Call
}

// SetRequestCount is a helper method to define mock.On call
//   - requestCount int
func (_e *ConsensusMetrics_Expecter) SetRequestCount(requestCount interface{}) *ConsensusMetrics_SetRequestCount_Call {
	return &ConsensusMetrics_SetRequestCount_Call{Call: _e.mock.On("SetRequestCount", requestCount)}
}

func (_c *ConsensusMetrics_SetRequestCount_Call) Run(run func(requestCount int)) *ConsensusMetrics_SetRequestCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *ConsensusMetrics_SetRequestCount_Call) Return() *ConsensusMetrics_SetRequestCount_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConsensusMetrics_SetRequestCount_Call) RunAndReturn(run func(int)) *ConsensusMetrics_SetRequestCount_Call {
	_c.Run(run)
	return _c
}

// NewConsensusMetrics creates a new instance of ConsensusMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsensusMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsensusMetrics {
	mock := &ConsensusMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
