// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvcap

import (
	"encoding/json"
	"fmt"
)

// Key-Value Store Action
type ReadAction struct {
	// Configuration for the Key-Value Store Action. No configuration options are
	// available at this time.
	Config ReadActionConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs ReadInputs `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs *ReadOutputs `json:"outputs,omitempty" yaml:"outputs,omitempty" mapstructure:"outputs,omitempty"`
}

// Configuration for the Key-Value Store Action. No configuration options are
// available at this time.
type ReadActionConfig map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReadAction) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["inputs"]; raw != nil && !ok {
		return fmt.Errorf("field inputs in ReadAction: required")
	}
	type Plain ReadAction
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ReadAction(plain)
	return nil
}

// Input parameters for the Key-Value Store Action.
type ReadInputs struct {
	// Keys to read from the Key-Value Store.
	Keys []string `json:"keys" yaml:"keys" mapstructure:"keys"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReadInputs) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["keys"]; raw != nil && !ok {
		return fmt.Errorf("field keys in ReadInputs: required")
	}
	type Plain ReadInputs
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ReadInputs(plain)
	return nil
}

// Outputs of the Key-Value Store Action.
type ReadOutputs struct {
	// Values read from the Key-Value Store.
	Values [][]uint8 `json:"values" yaml:"values" mapstructure:"values"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ReadOutputs) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["values"]; raw != nil && !ok {
		return fmt.Errorf("field values in ReadOutputs: required")
	}
	type Plain ReadOutputs
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ReadOutputs(plain)
	return nil
}
