// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvcap

import (
	"encoding/json"
	"fmt"

	ocr3cap "github.com/smartcontractkit/chainlink-common/pkg/capabilities/consensus/ocr3/ocr3cap"
)

// Input parameters for the Key-Value Store Target.
type Inputs struct {
	// SignedReport corresponds to the JSON schema field "signedReport".
	SignedReport ocr3cap.SignedReport `json:"signedReport" yaml:"signedReport" mapstructure:"signedReport"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Inputs) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["signedReport"]; raw != nil && !ok {
		return fmt.Errorf("field signedReport in Inputs: required")
	}
	type Plain Inputs
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Inputs(plain)
	return nil
}

// Key-Value Store Target
type WriteTarget struct {
	// Configuration for the Key-Value Store Target. No configuration options are
	// available at this time.
	Config WriteTargetConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs Inputs `json:"inputs" yaml:"inputs" mapstructure:"inputs"`
}

// Configuration for the Key-Value Store Target. No configuration options are
// available at this time.
type WriteTargetConfig map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *WriteTarget) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["inputs"]; raw != nil && !ok {
		return fmt.Errorf("field inputs in WriteTarget: required")
	}
	type Plain WriteTarget
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = WriteTarget(plain)
	return nil
}
