// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvcap

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg ReadActionConfig) New(w *sdk.WorkflowSpecFactory, ref string, input ReadActionInput) ReadOutputsCap {

	def := sdk.StepDefinition{
		ID: "kv-store-action@1.0.0", Ref: ref,
		Inputs:         input.ToSteps(),
		Config:         map[string]any{},
		CapabilityType: capabilities.CapabilityTypeAction,
	}

	step := sdk.Step[ReadOutputs]{Definition: def}
	return ReadOutputsCapFromStep(w, step)
}

type ReadOutputsCap interface {
	sdk.CapDefinition[ReadOutputs]
	Values() sdk.CapDefinition[[][]uint8]
	private()
}

// ReadOutputsCapFromStep should only be called from generated code to assure type safety
func ReadOutputsCapFromStep(w *sdk.WorkflowSpecFactory, step sdk.Step[ReadOutputs]) ReadOutputsCap {
	raw := step.AddTo(w)
	return &readOutputs{CapDefinition: raw}
}

type readOutputs struct {
	sdk.CapDefinition[ReadOutputs]
}

func (*readOutputs) private() {}
func (c *readOutputs) Values() sdk.CapDefinition[[][]uint8] {
	return sdk.AccessField[ReadOutputs, [][]uint8](c.CapDefinition, "values")
}

func NewReadOutputsFromFields(
	values sdk.CapDefinition[[][]uint8]) ReadOutputsCap {
	return &simpleReadOutputs{
		CapDefinition: sdk.ComponentCapDefinition[ReadOutputs]{
			"values": values.Ref(),
		},
		values: values,
	}
}

type simpleReadOutputs struct {
	sdk.CapDefinition[ReadOutputs]
	values sdk.CapDefinition[[][]uint8]
}

func (c *simpleReadOutputs) Values() sdk.CapDefinition[[][]uint8] {
	return c.values
}

func (c *simpleReadOutputs) private() {}

type ReadActionInput struct {
	Keys sdk.CapDefinition[[]string]
}

func (input ReadActionInput) ToSteps() sdk.StepInputs {
	return sdk.StepInputs{
		Mapping: map[string]any{
			"keys": input.Keys.Ref(),
		},
	}
}
