// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvcap

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg ReadActionConfig) New(w *sdk.WorkflowSpecFactory, ref string, input ReadActionInput) ActionOutputsCap {

	def := sdk.StepDefinition{
		ID: "kv-store-action@1.0.0", Ref: ref,
		Inputs:         input.ToSteps(),
		Config:         map[string]any{},
		CapabilityType: capabilities.CapabilityTypeAction,
	}

	step := sdk.Step[ActionOutputs]{Definition: def}
	return ActionOutputsCapFromStep(w, step)
}

type ActionOutputsCap interface {
	sdk.CapDefinition[ActionOutputs]
	Values() sdk.CapDefinition[[][]uint8]
	private()
}

// ActionOutputsCapFromStep should only be called from generated code to assure type safety
func ActionOutputsCapFromStep(w *sdk.WorkflowSpecFactory, step sdk.Step[ActionOutputs]) ActionOutputsCap {
	raw := step.AddTo(w)
	return &actionOutputs{CapDefinition: raw}
}

type actionOutputs struct {
	sdk.CapDefinition[ActionOutputs]
}

func (*actionOutputs) private() {}
func (c *actionOutputs) Values() sdk.CapDefinition[[][]uint8] {
	return sdk.AccessField[ActionOutputs, [][]uint8](c.CapDefinition, "values")
}

func NewActionOutputsFromFields(
	values sdk.CapDefinition[[][]uint8]) ActionOutputsCap {
	return &simpleActionOutputs{
		CapDefinition: sdk.ComponentCapDefinition[ActionOutputs]{
			"values": values.Ref(),
		},
		values: values,
	}
}

type simpleActionOutputs struct {
	sdk.CapDefinition[ActionOutputs]
	values sdk.CapDefinition[[][]uint8]
}

func (c *simpleActionOutputs) Values() sdk.CapDefinition[[][]uint8] {
	return c.values
}

func (c *simpleActionOutputs) private() {}

type ReadActionInput struct {
	Keys sdk.CapDefinition[[]string]
}

func (input ReadActionInput) ToSteps() sdk.StepInputs {
	return sdk.StepInputs{
		Mapping: map[string]any{
			"keys": input.Keys.Ref(),
		},
	}
}
