// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package confidential_http_action

import (
	"encoding/json"
	"fmt"
)

type Config struct {
	// Enclaves corresponds to the JSON schema field "Enclaves".
	Enclaves []Enclave `json:"Enclaves" yaml:"Enclaves" mapstructure:"Enclaves"`

	// VaultDONID corresponds to the JSON schema field "VaultDONID".
	VaultDONID []uint8 `json:"VaultDONID" yaml:"VaultDONID" mapstructure:"VaultDONID"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Config) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["Enclaves"]; raw != nil && !ok {
		return fmt.Errorf("field Enclaves in Config: required")
	}
	if _, ok := raw["VaultDONID"]; raw != nil && !ok {
		return fmt.Errorf("field VaultDONID in Config: required")
	}
	type Plain Config
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Config(plain)
	return nil
}

type Enclave struct {
	// EnclaveType corresponds to the JSON schema field "EnclaveType".
	EnclaveType *string `json:"EnclaveType,omitempty" yaml:"EnclaveType,omitempty" mapstructure:"EnclaveType,omitempty"`

	// ExtraData corresponds to the JSON schema field "ExtraData".
	ExtraData []uint8 `json:"ExtraData" yaml:"ExtraData" mapstructure:"ExtraData"`

	// ID corresponds to the JSON schema field "ID".
	ID []uint8 `json:"ID" yaml:"ID" mapstructure:"ID"`

	// TrustedValues corresponds to the JSON schema field "TrustedValues".
	TrustedValues []uint8 `json:"TrustedValues" yaml:"TrustedValues" mapstructure:"TrustedValues"`

	// URL corresponds to the JSON schema field "URL".
	URL string `json:"URL" yaml:"URL" mapstructure:"URL"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Enclave) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["ExtraData"]; raw != nil && !ok {
		return fmt.Errorf("field ExtraData in Enclave: required")
	}
	if _, ok := raw["ID"]; raw != nil && !ok {
		return fmt.Errorf("field ID in Enclave: required")
	}
	if _, ok := raw["TrustedValues"]; raw != nil && !ok {
		return fmt.Errorf("field TrustedValues in Enclave: required")
	}
	if _, ok := raw["URL"]; raw != nil && !ok {
		return fmt.Errorf("field URL in Enclave: required")
	}
	type Plain Enclave
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Enclave(plain)
	return nil
}

// Confidential HTTP action
type HttpAction struct {
	// Config corresponds to the JSON schema field "config".
	Config Config `json:"config" yaml:"config" mapstructure:"config"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs Input `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs Output `json:"outputs" yaml:"outputs" mapstructure:"outputs"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *HttpAction) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["config"]; raw != nil && !ok {
		return fmt.Errorf("field config in HttpAction: required")
	}
	if _, ok := raw["inputs"]; raw != nil && !ok {
		return fmt.Errorf("field inputs in HttpAction: required")
	}
	if _, ok := raw["outputs"]; raw != nil && !ok {
		return fmt.Errorf("field outputs in HttpAction: required")
	}
	type Plain HttpAction
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = HttpAction(plain)
	return nil
}

type Input struct {
	// Requests corresponds to the JSON schema field "requests".
	Requests []interface{} `json:"requests,omitempty" yaml:"requests,omitempty" mapstructure:"requests,omitempty"`
}

type Output struct {
	// Responses corresponds to the JSON schema field "responses".
	Responses []uint8 `json:"responses,omitempty" yaml:"responses,omitempty" mapstructure:"responses,omitempty"`
}
