// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package confidential_http_action_cap

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg Config) New(w *sdk.WorkflowSpecFactory, ref string, input HttpActionInput) OutputCap {

	def := sdk.StepDefinition{
		ID: "confidential-http-action@1.0.0", Ref: ref,
		Inputs: input.ToSteps(),
		Config: map[string]any{
			"Enclaves":   cfg.Enclaves,
			"VaultDONID": cfg.VaultDONID,
		},
		CapabilityType: capabilities.CapabilityTypeAction,
	}

	step := sdk.Step[Output]{Definition: def}
	raw := step.AddTo(w)
	return OutputWrapper(raw)
}

// EnclaveWrapper allows access to field from an sdk.CapDefinition[Enclave]
func EnclaveWrapper(raw sdk.CapDefinition[Enclave]) EnclaveCap {
	wrapped, ok := raw.(EnclaveCap)
	if ok {
		return wrapped
	}
	return &enclaveCap{CapDefinition: raw}
}

type EnclaveCap interface {
	sdk.CapDefinition[Enclave]
	EnclaveType() sdk.CapDefinition[string]
	ExtraData() sdk.CapDefinition[[]uint8]
	ID() sdk.CapDefinition[[]uint8]
	TrustedValues() sdk.CapDefinition[[]uint8]
	URL() sdk.CapDefinition[string]
	private()
}

type enclaveCap struct {
	sdk.CapDefinition[Enclave]
}

func (*enclaveCap) private() {}
func (c *enclaveCap) EnclaveType() sdk.CapDefinition[string] {
	return sdk.AccessField[Enclave, string](c.CapDefinition, "EnclaveType")
}
func (c *enclaveCap) ExtraData() sdk.CapDefinition[[]uint8] {
	return sdk.AccessField[Enclave, []uint8](c.CapDefinition, "ExtraData")
}
func (c *enclaveCap) ID() sdk.CapDefinition[[]uint8] {
	return sdk.AccessField[Enclave, []uint8](c.CapDefinition, "ID")
}
func (c *enclaveCap) TrustedValues() sdk.CapDefinition[[]uint8] {
	return sdk.AccessField[Enclave, []uint8](c.CapDefinition, "TrustedValues")
}
func (c *enclaveCap) URL() sdk.CapDefinition[string] {
	return sdk.AccessField[Enclave, string](c.CapDefinition, "URL")
}

func ConstantEnclave(value Enclave) EnclaveCap {
	return &enclaveCap{CapDefinition: sdk.ConstantDefinition(value)}
}

func NewEnclaveFromFields(
	enclaveType sdk.CapDefinition[string],
	extraData sdk.CapDefinition[[]uint8],
	iD sdk.CapDefinition[[]uint8],
	trustedValues sdk.CapDefinition[[]uint8],
	uRL sdk.CapDefinition[string]) EnclaveCap {
	return &simpleEnclave{
		CapDefinition: sdk.ComponentCapDefinition[Enclave]{
			"EnclaveType":   enclaveType.Ref(),
			"ExtraData":     extraData.Ref(),
			"ID":            iD.Ref(),
			"TrustedValues": trustedValues.Ref(),
			"URL":           uRL.Ref(),
		},
		enclaveType:   enclaveType,
		extraData:     extraData,
		iD:            iD,
		trustedValues: trustedValues,
		uRL:           uRL,
	}
}

type simpleEnclave struct {
	sdk.CapDefinition[Enclave]
	enclaveType   sdk.CapDefinition[string]
	extraData     sdk.CapDefinition[[]uint8]
	iD            sdk.CapDefinition[[]uint8]
	trustedValues sdk.CapDefinition[[]uint8]
	uRL           sdk.CapDefinition[string]
}

func (c *simpleEnclave) EnclaveType() sdk.CapDefinition[string] {
	return c.enclaveType
}
func (c *simpleEnclave) ExtraData() sdk.CapDefinition[[]uint8] {
	return c.extraData
}
func (c *simpleEnclave) ID() sdk.CapDefinition[[]uint8] {
	return c.iD
}
func (c *simpleEnclave) TrustedValues() sdk.CapDefinition[[]uint8] {
	return c.trustedValues
}
func (c *simpleEnclave) URL() sdk.CapDefinition[string] {
	return c.uRL
}

func (c *simpleEnclave) private() {}

// OutputWrapper allows access to field from an sdk.CapDefinition[Output]
func OutputWrapper(raw sdk.CapDefinition[Output]) OutputCap {
	wrapped, ok := raw.(OutputCap)
	if ok {
		return wrapped
	}
	return &outputCap{CapDefinition: raw}
}

type OutputCap interface {
	sdk.CapDefinition[Output]
	Responses() sdk.CapDefinition[[]OutputResponsesElem]
	private()
}

type outputCap struct {
	sdk.CapDefinition[Output]
}

func (*outputCap) private() {}
func (c *outputCap) Responses() sdk.CapDefinition[[]OutputResponsesElem] {
	return sdk.AccessField[Output, []OutputResponsesElem](c.CapDefinition, "responses")
}

func ConstantOutput(value Output) OutputCap {
	return &outputCap{CapDefinition: sdk.ConstantDefinition(value)}
}

func NewOutputFromFields(
	responses sdk.CapDefinition[[]OutputResponsesElem]) OutputCap {
	return &simpleOutput{
		CapDefinition: sdk.ComponentCapDefinition[Output]{
			"responses": responses.Ref(),
		},
		responses: responses,
	}
}

type simpleOutput struct {
	sdk.CapDefinition[Output]
	responses sdk.CapDefinition[[]OutputResponsesElem]
}

func (c *simpleOutput) Responses() sdk.CapDefinition[[]OutputResponsesElem] {
	return c.responses
}

func (c *simpleOutput) private() {}

// OutputResponsesElemWrapper allows access to field from an sdk.CapDefinition[OutputResponsesElem]
func OutputResponsesElemWrapper(raw sdk.CapDefinition[OutputResponsesElem]) OutputResponsesElemCap {
	wrapped, ok := raw.(OutputResponsesElemCap)
	if ok {
		return wrapped
	}
	return &outputResponsesElemCap{CapDefinition: raw}
}

type OutputResponsesElemCap interface {
	sdk.CapDefinition[OutputResponsesElem]
	Body() sdk.CapDefinition[[]uint8]
	StatusCode() sdk.CapDefinition[int64]
	private()
}

type outputResponsesElemCap struct {
	sdk.CapDefinition[OutputResponsesElem]
}

func (*outputResponsesElemCap) private() {}
func (c *outputResponsesElemCap) Body() sdk.CapDefinition[[]uint8] {
	return sdk.AccessField[OutputResponsesElem, []uint8](c.CapDefinition, "body")
}
func (c *outputResponsesElemCap) StatusCode() sdk.CapDefinition[int64] {
	return sdk.AccessField[OutputResponsesElem, int64](c.CapDefinition, "statusCode")
}

func ConstantOutputResponsesElem(value OutputResponsesElem) OutputResponsesElemCap {
	return &outputResponsesElemCap{CapDefinition: sdk.ConstantDefinition(value)}
}

func NewOutputResponsesElemFromFields(
	body sdk.CapDefinition[[]uint8],
	statusCode sdk.CapDefinition[int64]) OutputResponsesElemCap {
	return &simpleOutputResponsesElem{
		CapDefinition: sdk.ComponentCapDefinition[OutputResponsesElem]{
			"body":       body.Ref(),
			"statusCode": statusCode.Ref(),
		},
		body:       body,
		statusCode: statusCode,
	}
}

type simpleOutputResponsesElem struct {
	sdk.CapDefinition[OutputResponsesElem]
	body       sdk.CapDefinition[[]uint8]
	statusCode sdk.CapDefinition[int64]
}

func (c *simpleOutputResponsesElem) Body() sdk.CapDefinition[[]uint8] {
	return c.body
}
func (c *simpleOutputResponsesElem) StatusCode() sdk.CapDefinition[int64] {
	return c.statusCode
}

func (c *simpleOutputResponsesElem) private() {}

// RequestWrapper allows access to field from an sdk.CapDefinition[Request]
func RequestWrapper(raw sdk.CapDefinition[Request]) RequestCap {
	wrapped, ok := raw.(RequestCap)
	if ok {
		return wrapped
	}
	return &requestCap{CapDefinition: raw}
}

type RequestCap interface {
	sdk.CapDefinition[Request]
	Body() sdk.CapDefinition[string]
	CustomRootCaCertPEM() sdk.CapDefinition[[]uint8]
	Headers() sdk.CapDefinition[[]string]
	Method() sdk.CapDefinition[string]
	PublicTemplateValues() RequestPublicTemplateValuesCap
	Url() sdk.CapDefinition[string]
	private()
}

type requestCap struct {
	sdk.CapDefinition[Request]
}

func (*requestCap) private() {}
func (c *requestCap) Body() sdk.CapDefinition[string] {
	return sdk.AccessField[Request, string](c.CapDefinition, "body")
}
func (c *requestCap) CustomRootCaCertPEM() sdk.CapDefinition[[]uint8] {
	return sdk.AccessField[Request, []uint8](c.CapDefinition, "customRootCaCertPEM")
}
func (c *requestCap) Headers() sdk.CapDefinition[[]string] {
	return sdk.AccessField[Request, []string](c.CapDefinition, "headers")
}
func (c *requestCap) Method() sdk.CapDefinition[string] {
	return sdk.AccessField[Request, string](c.CapDefinition, "method")
}
func (c *requestCap) PublicTemplateValues() RequestPublicTemplateValuesCap {
	return RequestPublicTemplateValuesWrapper(sdk.AccessField[Request, RequestPublicTemplateValues](c.CapDefinition, "publicTemplateValues"))
}
func (c *requestCap) Url() sdk.CapDefinition[string] {
	return sdk.AccessField[Request, string](c.CapDefinition, "url")
}

func ConstantRequest(value Request) RequestCap {
	return &requestCap{CapDefinition: sdk.ConstantDefinition(value)}
}

func NewRequestFromFields(
	body sdk.CapDefinition[string],
	customRootCaCertPEM sdk.CapDefinition[[]uint8],
	headers sdk.CapDefinition[[]string],
	method sdk.CapDefinition[string],
	publicTemplateValues RequestPublicTemplateValuesCap,
	url sdk.CapDefinition[string]) RequestCap {
	return &simpleRequest{
		CapDefinition: sdk.ComponentCapDefinition[Request]{
			"body":                 body.Ref(),
			"customRootCaCertPEM":  customRootCaCertPEM.Ref(),
			"headers":              headers.Ref(),
			"method":               method.Ref(),
			"publicTemplateValues": publicTemplateValues.Ref(),
			"url":                  url.Ref(),
		},
		body:                 body,
		customRootCaCertPEM:  customRootCaCertPEM,
		headers:              headers,
		method:               method,
		publicTemplateValues: publicTemplateValues,
		url:                  url,
	}
}

type simpleRequest struct {
	sdk.CapDefinition[Request]
	body                 sdk.CapDefinition[string]
	customRootCaCertPEM  sdk.CapDefinition[[]uint8]
	headers              sdk.CapDefinition[[]string]
	method               sdk.CapDefinition[string]
	publicTemplateValues RequestPublicTemplateValuesCap
	url                  sdk.CapDefinition[string]
}

func (c *simpleRequest) Body() sdk.CapDefinition[string] {
	return c.body
}
func (c *simpleRequest) CustomRootCaCertPEM() sdk.CapDefinition[[]uint8] {
	return c.customRootCaCertPEM
}
func (c *simpleRequest) Headers() sdk.CapDefinition[[]string] {
	return c.headers
}
func (c *simpleRequest) Method() sdk.CapDefinition[string] {
	return c.method
}
func (c *simpleRequest) PublicTemplateValues() RequestPublicTemplateValuesCap {
	return c.publicTemplateValues
}
func (c *simpleRequest) Url() sdk.CapDefinition[string] {
	return c.url
}

func (c *simpleRequest) private() {}

// RequestPublicTemplateValuesWrapper allows access to field from an sdk.CapDefinition[RequestPublicTemplateValues]
func RequestPublicTemplateValuesWrapper(raw sdk.CapDefinition[RequestPublicTemplateValues]) RequestPublicTemplateValuesCap {
	wrapped, ok := raw.(RequestPublicTemplateValuesCap)
	if ok {
		return wrapped
	}
	return RequestPublicTemplateValuesCap(raw)
}

type RequestPublicTemplateValuesCap sdk.CapDefinition[RequestPublicTemplateValues]

type HttpActionInput struct {
	Requests          sdk.CapDefinition[[]Request]
	VaultDONSecretIds sdk.CapDefinition[[]string]
}

func (input HttpActionInput) ToSteps() sdk.StepInputs {
	return sdk.StepInputs{
		Mapping: map[string]any{
			"requests":          input.Requests.Ref(),
			"vaultDONSecretIds": input.VaultDONSecretIds.Ref(),
		},
	}
}
