// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package confidential_http_action

import (
	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk"
)

func (cfg Config) New(w *sdk.WorkflowSpecFactory, ref string, input HttpActionInput) OutputCap {

	def := sdk.StepDefinition{
		ID: "confidential-http-action@1.0.0", Ref: ref,
		Inputs: input.ToSteps(),
		Config: map[string]any{
			"EnclaveURL": cfg.EnclaveURL,
			"PrivateKey": cfg.PrivateKey,
			"PublicKey":  cfg.PublicKey,
		},
		CapabilityType: capabilities.CapabilityTypeAction,
	}

	step := sdk.Step[Output]{Definition: def}
	raw := step.AddTo(w)
	return OutputWrapper(raw)
}

type HttpActionInput = Input.HttpActionInput
