// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: chain_capabilities/aptos/monitoring/view.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ViewRequest intentionally captures only the small, non-sensitive subset of
// the capability request that is useful for monitoring.
type ViewRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ModuleAddress          []byte                 `protobuf:"bytes,1,opt,name=module_address,json=moduleAddress,proto3" json:"module_address,omitempty"`
	ModuleName             string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Function               string                 `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	RequestedLedgerVersion *uint64                `protobuf:"varint,4,opt,name=requested_ledger_version,json=requestedLedgerVersion,proto3,oneof" json:"requested_ledger_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ViewRequest) Reset() {
	*x = ViewRequest{}
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRequest) ProtoMessage() {}

func (x *ViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRequest.ProtoReflect.Descriptor instead.
func (*ViewRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_view_proto_rawDescGZIP(), []int{0}
}

func (x *ViewRequest) GetModuleAddress() []byte {
	if x != nil {
		return x.ModuleAddress
	}
	return nil
}

func (x *ViewRequest) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *ViewRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *ViewRequest) GetRequestedLedgerVersion() uint64 {
	if x != nil && x.RequestedLedgerVersion != nil {
		return *x.RequestedLedgerVersion
	}
	return 0
}

type ViewInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *ViewRequest                 `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewInitiated) Reset() {
	*x = ViewInitiated{}
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewInitiated) ProtoMessage() {}

func (x *ViewInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewInitiated.ProtoReflect.Descriptor instead.
func (*ViewInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_view_proto_rawDescGZIP(), []int{1}
}

func (x *ViewInitiated) GetReq() *ViewRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *ViewInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type ViewSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *ViewRequest                 `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ResponseLen      uint64                       `protobuf:"varint,2,opt,name=response_len,json=responseLen,proto3" json:"response_len,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewSuccess) Reset() {
	*x = ViewSuccess{}
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewSuccess) ProtoMessage() {}

func (x *ViewSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewSuccess.ProtoReflect.Descriptor instead.
func (*ViewSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_view_proto_rawDescGZIP(), []int{2}
}

func (x *ViewSuccess) GetReq() *ViewRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *ViewSuccess) GetResponseLen() uint64 {
	if x != nil {
		return x.ResponseLen
	}
	return 0
}

func (x *ViewSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type ViewError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *ViewRequest                 `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	IsUserError      bool                         `protobuf:"varint,4,opt,name=is_user_error,json=isUserError,proto3" json:"is_user_error,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ViewError) Reset() {
	*x = ViewError{}
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewError) ProtoMessage() {}

func (x *ViewError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewError.ProtoReflect.Descriptor instead.
func (*ViewError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_view_proto_rawDescGZIP(), []int{3}
}

func (x *ViewError) GetReq() *ViewRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *ViewError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ViewError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *ViewError) GetIsUserError() bool {
	if x != nil {
		return x.IsUserError
	}
	return false
}

func (x *ViewError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_chain_capabilities_aptos_monitoring_view_proto protoreflect.FileDescriptor

const file_chain_capabilities_aptos_monitoring_view_proto_rawDesc = "" +
	"\n" +
	".chain_capabilities/aptos/monitoring/view.proto\x12\x18chain_capabilities.aptos\x1a'libs/monitoring/execution_context.proto\"\xcd\x01\n" +
	"\vViewRequest\x12%\n" +
	"\x0emodule_address\x18\x01 \x01(\fR\rmoduleAddress\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12\x1a\n" +
	"\bfunction\x18\x03 \x01(\tR\bfunction\x12=\n" +
	"\x18requested_ledger_version\x18\x04 \x01(\x04H\x00R\x16requestedLedgerVersion\x88\x01\x01B\x1b\n" +
	"\x19_requested_ledger_version\"\x93\x01\n" +
	"\rViewInitiated\x127\n" +
	"\x03req\x18\x01 \x01(\v2%.chain_capabilities.aptos.ViewRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xb4\x01\n" +
	"\vViewSuccess\x127\n" +
	"\x03req\x18\x01 \x01(\v2%.chain_capabilities.aptos.ViewRequestR\x03req\x12!\n" +
	"\fresponse_len\x18\x02 \x01(\x04R\vresponseLen\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xe3\x01\n" +
	"\tViewError\x127\n" +
	"\x03req\x18\x01 \x01(\v2%.chain_capabilities.aptos.ViewRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12\"\n" +
	"\ris_user_error\x18\x04 \x01(\bR\visUserError\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContextBNZLgithub.com/smartcontractkit/capabilities/chain_capabilities/aptos;monitoringb\x06proto3"

var (
	file_chain_capabilities_aptos_monitoring_view_proto_rawDescOnce sync.Once
	file_chain_capabilities_aptos_monitoring_view_proto_rawDescData []byte
)

func file_chain_capabilities_aptos_monitoring_view_proto_rawDescGZIP() []byte {
	file_chain_capabilities_aptos_monitoring_view_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_aptos_monitoring_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_aptos_monitoring_view_proto_rawDesc), len(file_chain_capabilities_aptos_monitoring_view_proto_rawDesc)))
	})
	return file_chain_capabilities_aptos_monitoring_view_proto_rawDescData
}

var file_chain_capabilities_aptos_monitoring_view_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chain_capabilities_aptos_monitoring_view_proto_goTypes = []any{
	(*ViewRequest)(nil),                 // 0: chain_capabilities.aptos.ViewRequest
	(*ViewInitiated)(nil),               // 1: chain_capabilities.aptos.ViewInitiated
	(*ViewSuccess)(nil),                 // 2: chain_capabilities.aptos.ViewSuccess
	(*ViewError)(nil),                   // 3: chain_capabilities.aptos.ViewError
	(*monitoring.ExecutionContext)(nil), // 4: monitoring.ExecutionContext
}
var file_chain_capabilities_aptos_monitoring_view_proto_depIdxs = []int32{
	0, // 0: chain_capabilities.aptos.ViewInitiated.req:type_name -> chain_capabilities.aptos.ViewRequest
	4, // 1: chain_capabilities.aptos.ViewInitiated.execution_context:type_name -> monitoring.ExecutionContext
	0, // 2: chain_capabilities.aptos.ViewSuccess.req:type_name -> chain_capabilities.aptos.ViewRequest
	4, // 3: chain_capabilities.aptos.ViewSuccess.execution_context:type_name -> monitoring.ExecutionContext
	0, // 4: chain_capabilities.aptos.ViewError.req:type_name -> chain_capabilities.aptos.ViewRequest
	4, // 5: chain_capabilities.aptos.ViewError.execution_context:type_name -> monitoring.ExecutionContext
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_chain_capabilities_aptos_monitoring_view_proto_init() }
func file_chain_capabilities_aptos_monitoring_view_proto_init() {
	if File_chain_capabilities_aptos_monitoring_view_proto != nil {
		return
	}
	file_chain_capabilities_aptos_monitoring_view_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_aptos_monitoring_view_proto_rawDesc), len(file_chain_capabilities_aptos_monitoring_view_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_capabilities_aptos_monitoring_view_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_aptos_monitoring_view_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_aptos_monitoring_view_proto_msgTypes,
	}.Build()
	File_chain_capabilities_aptos_monitoring_view_proto = out.File
	file_chain_capabilities_aptos_monitoring_view_proto_goTypes = nil
	file_chain_capabilities_aptos_monitoring_view_proto_depIdxs = nil
}
