// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: chain_capabilities/aptos/monitoring/write_report.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteReportInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportInitiated) Reset() {
	*x = WriteReportInitiated{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportInitiated) ProtoMessage() {}

func (x *WriteReportInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportInitiated.ProtoReflect.Descriptor instead.
func (*WriteReportInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{0}
}

func (x *WriteReportInitiated) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportSuccess) Reset() {
	*x = WriteReportSuccess{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportSuccess) ProtoMessage() {}

func (x *WriteReportSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportSuccess.ProtoReflect.Descriptor instead.
func (*WriteReportSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{1}
}

func (x *WriteReportSuccess) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	IsUserError      bool                         `protobuf:"varint,4,opt,name=isUserError,proto3" json:"isUserError,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportError) Reset() {
	*x = WriteReportError{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportError) ProtoMessage() {}

func (x *WriteReportError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportError.ProtoReflect.Descriptor instead.
func (*WriteReportError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{2}
}

func (x *WriteReportError) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteReportError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteReportError) GetIsUserError() bool {
	if x != nil {
		return x.IsUserError
	}
	return false
}

func (x *WriteReportError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportTxFeeCalculationError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	TxHash           string                       `protobuf:"bytes,4,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportTxFeeCalculationError) Reset() {
	*x = WriteReportTxFeeCalculationError{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportTxFeeCalculationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportTxFeeCalculationError) ProtoMessage() {}

func (x *WriteReportTxFeeCalculationError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportTxFeeCalculationError.ProtoReflect.Descriptor instead.
func (*WriteReportTxFeeCalculationError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{3}
}

func (x *WriteReportTxFeeCalculationError) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportTxFeeCalculationError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteReportTxFeeCalculationError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteReportTxFeeCalculationError) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *WriteReportTxFeeCalculationError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportDuplicateTx struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	DuplicateTxHash  string                       `protobuf:"bytes,2,opt,name=duplicate_tx_hash,json=duplicateTxHash,proto3" json:"duplicate_tx_hash,omitempty"`
	SuccessfulTxHash string                       `protobuf:"bytes,3,opt,name=successful_tx_hash,json=successfulTxHash,proto3" json:"successful_tx_hash,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportDuplicateTx) Reset() {
	*x = WriteReportDuplicateTx{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportDuplicateTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportDuplicateTx) ProtoMessage() {}

func (x *WriteReportDuplicateTx) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportDuplicateTx.ProtoReflect.Descriptor instead.
func (*WriteReportDuplicateTx) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{4}
}

func (x *WriteReportDuplicateTx) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportDuplicateTx) GetDuplicateTxHash() string {
	if x != nil {
		return x.DuplicateTxHash
	}
	return ""
}

func (x *WriteReportDuplicateTx) GetSuccessfulTxHash() string {
	if x != nil {
		return x.SuccessfulTxHash
	}
	return ""
}

func (x *WriteReportDuplicateTx) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportSuccessfulEarlyReturn struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportSuccessfulEarlyReturn) Reset() {
	*x = WriteReportSuccessfulEarlyReturn{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportSuccessfulEarlyReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportSuccessfulEarlyReturn) ProtoMessage() {}

func (x *WriteReportSuccessfulEarlyReturn) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportSuccessfulEarlyReturn.ProtoReflect.Descriptor instead.
func (*WriteReportSuccessfulEarlyReturn) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{5}
}

func (x *WriteReportSuccessfulEarlyReturn) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      []byte                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	GasConfig     *GasConfig             `protobuf:"bytes,2,opt,name=gas_config,json=gasConfig,proto3,oneof" json:"gas_config,omitempty"`
	Report        *ReportResponse        `protobuf:"bytes,3,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReportRequest) Reset() {
	*x = WriteReportRequest{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportRequest) ProtoMessage() {}

func (x *WriteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportRequest.ProtoReflect.Descriptor instead.
func (*WriteReportRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{6}
}

func (x *WriteReportRequest) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *WriteReportRequest) GetGasConfig() *GasConfig {
	if x != nil {
		return x.GasConfig
	}
	return nil
}

func (x *WriteReportRequest) GetReport() *ReportResponse {
	if x != nil {
		return x.Report
	}
	return nil
}

type GasConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxGasAmount  uint64                 `protobuf:"varint,1,opt,name=max_gas_amount,json=maxGasAmount,proto3" json:"max_gas_amount,omitempty"`
	GasUnitPrice  uint64                 `protobuf:"varint,2,opt,name=gas_unit_price,json=gasUnitPrice,proto3" json:"gas_unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GasConfig) Reset() {
	*x = GasConfig{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasConfig) ProtoMessage() {}

func (x *GasConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasConfig.ProtoReflect.Descriptor instead.
func (*GasConfig) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{7}
}

func (x *GasConfig) GetMaxGasAmount() uint64 {
	if x != nil {
		return x.MaxGasAmount
	}
	return 0
}

func (x *GasConfig) GetGasUnitPrice() uint64 {
	if x != nil {
		return x.GasUnitPrice
	}
	return 0
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest  []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	SeqNr         uint64                 `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	ReportContext []byte                 `protobuf:"bytes,3,opt,name=report_context,json=reportContext,proto3" json:"report_context,omitempty"`
	RawReport     []byte                 `protobuf:"bytes,4,opt,name=raw_report,json=rawReport,proto3" json:"raw_report,omitempty"`
	Sigs          []*AttributedSignature `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResponse) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *ReportResponse) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *ReportResponse) GetReportContext() []byte {
	if x != nil {
		return x.ReportContext
	}
	return nil
}

func (x *ReportResponse) GetRawReport() []byte {
	if x != nil {
		return x.RawReport
	}
	return nil
}

func (x *ReportResponse) GetSigs() []*AttributedSignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type AttributedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	SignerId      uint32                 `protobuf:"varint,2,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedSignature) Reset() {
	*x = AttributedSignature{}
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedSignature) ProtoMessage() {}

func (x *AttributedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedSignature.ProtoReflect.Descriptor instead.
func (*AttributedSignature) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP(), []int{9}
}

func (x *AttributedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AttributedSignature) GetSignerId() uint32 {
	if x != nil {
		return x.SignerId
	}
	return 0
}

var File_chain_capabilities_aptos_monitoring_write_report_proto protoreflect.FileDescriptor

const file_chain_capabilities_aptos_monitoring_write_report_proto_rawDesc = "" +
	"\n" +
	"6chain_capabilities/aptos/monitoring/write_report.proto\x12\x18chain_capabilities.aptos\x1a'libs/monitoring/execution_context.proto\"\xa1\x01\n" +
	"\x14WriteReportInitiated\x12>\n" +
	"\x03req\x18\x01 \x01(\v2,.chain_capabilities.aptos.WriteReportRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x9f\x01\n" +
	"\x12WriteReportSuccess\x12>\n" +
	"\x03req\x18\x01 \x01(\v2,.chain_capabilities.aptos.WriteReportRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xef\x01\n" +
	"\x10WriteReportError\x12>\n" +
	"\x03req\x18\x01 \x01(\v2,.chain_capabilities.aptos.WriteReportRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12 \n" +
	"\visUserError\x18\x04 \x01(\bR\visUserError\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xf6\x01\n" +
	" WriteReportTxFeeCalculationError\x12>\n" +
	"\x03req\x18\x01 \x01(\v2,.chain_capabilities.aptos.WriteReportRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12\x17\n" +
	"\atx_hash\x18\x04 \x01(\tR\x06txHash\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xfd\x01\n" +
	"\x16WriteReportDuplicateTx\x12>\n" +
	"\x03req\x18\x01 \x01(\v2,.chain_capabilities.aptos.WriteReportRequestR\x03req\x12*\n" +
	"\x11duplicate_tx_hash\x18\x02 \x01(\tR\x0fduplicateTxHash\x12,\n" +
	"\x12successful_tx_hash\x18\x03 \x01(\tR\x10successfulTxHash\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"m\n" +
	" WriteReportSuccessfulEarlyReturn\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xca\x01\n" +
	"\x12WriteReportRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\fR\breceiver\x12G\n" +
	"\n" +
	"gas_config\x18\x02 \x01(\v2#.chain_capabilities.aptos.GasConfigH\x00R\tgasConfig\x88\x01\x01\x12@\n" +
	"\x06report\x18\x03 \x01(\v2(.chain_capabilities.aptos.ReportResponseR\x06reportB\r\n" +
	"\v_gas_config\"W\n" +
	"\tGasConfig\x12$\n" +
	"\x0emax_gas_amount\x18\x01 \x01(\x04R\fmaxGasAmount\x12$\n" +
	"\x0egas_unit_price\x18\x02 \x01(\x04R\fgasUnitPrice\"\xd5\x01\n" +
	"\x0eReportResponse\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x04R\x05seqNr\x12%\n" +
	"\x0ereport_context\x18\x03 \x01(\fR\rreportContext\x12\x1d\n" +
	"\n" +
	"raw_report\x18\x04 \x01(\fR\trawReport\x12A\n" +
	"\x04sigs\x18\x05 \x03(\v2-.chain_capabilities.aptos.AttributedSignatureR\x04sigs\"P\n" +
	"\x13AttributedSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigner_id\x18\x02 \x01(\rR\bsignerIdBNZLgithub.com/smartcontractkit/capabilities/chain_capabilities/aptos;monitoringb\x06proto3"

var (
	file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescOnce sync.Once
	file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescData []byte
)

func file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescGZIP() []byte {
	file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_aptos_monitoring_write_report_proto_rawDesc), len(file_chain_capabilities_aptos_monitoring_write_report_proto_rawDesc)))
	})
	return file_chain_capabilities_aptos_monitoring_write_report_proto_rawDescData
}

var file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chain_capabilities_aptos_monitoring_write_report_proto_goTypes = []any{
	(*WriteReportInitiated)(nil),             // 0: chain_capabilities.aptos.WriteReportInitiated
	(*WriteReportSuccess)(nil),               // 1: chain_capabilities.aptos.WriteReportSuccess
	(*WriteReportError)(nil),                 // 2: chain_capabilities.aptos.WriteReportError
	(*WriteReportTxFeeCalculationError)(nil), // 3: chain_capabilities.aptos.WriteReportTxFeeCalculationError
	(*WriteReportDuplicateTx)(nil),           // 4: chain_capabilities.aptos.WriteReportDuplicateTx
	(*WriteReportSuccessfulEarlyReturn)(nil), // 5: chain_capabilities.aptos.WriteReportSuccessfulEarlyReturn
	(*WriteReportRequest)(nil),               // 6: chain_capabilities.aptos.WriteReportRequest
	(*GasConfig)(nil),                        // 7: chain_capabilities.aptos.GasConfig
	(*ReportResponse)(nil),                   // 8: chain_capabilities.aptos.ReportResponse
	(*AttributedSignature)(nil),              // 9: chain_capabilities.aptos.AttributedSignature
	(*monitoring.ExecutionContext)(nil),      // 10: monitoring.ExecutionContext
}
var file_chain_capabilities_aptos_monitoring_write_report_proto_depIdxs = []int32{
	6,  // 0: chain_capabilities.aptos.WriteReportInitiated.req:type_name -> chain_capabilities.aptos.WriteReportRequest
	10, // 1: chain_capabilities.aptos.WriteReportInitiated.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 2: chain_capabilities.aptos.WriteReportSuccess.req:type_name -> chain_capabilities.aptos.WriteReportRequest
	10, // 3: chain_capabilities.aptos.WriteReportSuccess.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 4: chain_capabilities.aptos.WriteReportError.req:type_name -> chain_capabilities.aptos.WriteReportRequest
	10, // 5: chain_capabilities.aptos.WriteReportError.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 6: chain_capabilities.aptos.WriteReportTxFeeCalculationError.req:type_name -> chain_capabilities.aptos.WriteReportRequest
	10, // 7: chain_capabilities.aptos.WriteReportTxFeeCalculationError.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 8: chain_capabilities.aptos.WriteReportDuplicateTx.req:type_name -> chain_capabilities.aptos.WriteReportRequest
	10, // 9: chain_capabilities.aptos.WriteReportDuplicateTx.execution_context:type_name -> monitoring.ExecutionContext
	10, // 10: chain_capabilities.aptos.WriteReportSuccessfulEarlyReturn.execution_context:type_name -> monitoring.ExecutionContext
	7,  // 11: chain_capabilities.aptos.WriteReportRequest.gas_config:type_name -> chain_capabilities.aptos.GasConfig
	8,  // 12: chain_capabilities.aptos.WriteReportRequest.report:type_name -> chain_capabilities.aptos.ReportResponse
	9,  // 13: chain_capabilities.aptos.ReportResponse.sigs:type_name -> chain_capabilities.aptos.AttributedSignature
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_chain_capabilities_aptos_monitoring_write_report_proto_init() }
func file_chain_capabilities_aptos_monitoring_write_report_proto_init() {
	if File_chain_capabilities_aptos_monitoring_write_report_proto != nil {
		return
	}
	file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_aptos_monitoring_write_report_proto_rawDesc), len(file_chain_capabilities_aptos_monitoring_write_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_capabilities_aptos_monitoring_write_report_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_aptos_monitoring_write_report_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_aptos_monitoring_write_report_proto_msgTypes,
	}.Build()
	File_chain_capabilities_aptos_monitoring_write_report_proto = out.File
	file_chain_capabilities_aptos_monitoring_write_report_proto_goTypes = nil
	file_chain_capabilities_aptos_monitoring_write_report_proto_depIdxs = nil
}
