// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package loadtestproxy

import (
	"encoding/json"
	"fmt"
)

type Config map[string]interface{}

type Payload map[string]interface{}

// GRPC capability proxy used for load tests
type ProxyTrigger struct {
	// Config corresponds to the JSON schema field "config".
	Config Config `json:"config" yaml:"config" mapstructure:"config"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs Payload `json:"outputs" yaml:"outputs" mapstructure:"outputs"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ProxyTrigger) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["config"]; raw != nil && !ok {
		return fmt.Errorf("field config in ProxyTrigger: required")
	}
	if _, ok := raw["outputs"]; raw != nil && !ok {
		return fmt.Errorf("field outputs in ProxyTrigger: required")
	}
	type Plain ProxyTrigger
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = ProxyTrigger(plain)
	return nil
}
