// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	evm "github.com/smartcontractkit/chainlink-common/pkg/types/chains/evm"
	mock "github.com/stretchr/testify/mock"
)

// HeaderByNumberProvider is an autogenerated mock type for the HeaderByNumberProvider type
type HeaderByNumberProvider struct {
	mock.Mock
}

type HeaderByNumberProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *HeaderByNumberProvider) EXPECT() *HeaderByNumberProvider_Expecter {
	return &HeaderByNumberProvider_Expecter{mock: &_m.Mock}
}

// HeaderByNumber provides a mock function with given fields: ctx, request
func (_m *HeaderByNumberProvider) HeaderByNumber(ctx context.Context, request evm.HeaderByNumberRequest) (*evm.HeaderByNumberReply, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for HeaderByNumber")
	}

	var r0 *evm.HeaderByNumberReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, evm.HeaderByNumberRequest) (*evm.HeaderByNumberReply, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, evm.HeaderByNumberRequest) *evm.HeaderByNumberReply); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evm.HeaderByNumberReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, evm.HeaderByNumberRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HeaderByNumberProvider_HeaderByNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeaderByNumber'
type HeaderByNumberProvider_HeaderByNumber_Call struct {
	*mock.Call
}

// HeaderByNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - request evm.HeaderByNumberRequest
func (_e *HeaderByNumberProvider_Expecter) HeaderByNumber(ctx interface{}, request interface{}) *HeaderByNumberProvider_HeaderByNumber_Call {
	return &HeaderByNumberProvider_HeaderByNumber_Call{Call: _e.mock.On("HeaderByNumber", ctx, request)}
}

func (_c *HeaderByNumberProvider_HeaderByNumber_Call) Run(run func(ctx context.Context, request evm.HeaderByNumberRequest)) *HeaderByNumberProvider_HeaderByNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(evm.HeaderByNumberRequest))
	})
	return _c
}

func (_c *HeaderByNumberProvider_HeaderByNumber_Call) Return(_a0 *evm.HeaderByNumberReply, _a1 error) *HeaderByNumberProvider_HeaderByNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HeaderByNumberProvider_HeaderByNumber_Call) RunAndReturn(run func(context.Context, evm.HeaderByNumberRequest) (*evm.HeaderByNumberReply, error)) *HeaderByNumberProvider_HeaderByNumber_Call {
	_c.Call.Return(run)
	return _c
}

// NewHeaderByNumberProvider creates a new instance of HeaderByNumberProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHeaderByNumberProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *HeaderByNumberProvider {
	mock := &HeaderByNumberProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
