// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/protoc, DO NOT EDIT.

package pb

import (
	"context"
	"fmt"
	"time"

	"google.golang.org/protobuf/types/known/emptypb"

	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	"github.com/smartcontractkit/chainlink-common/pkg/types/core"
)

// Avoid unused imports if there is configuration type
var _ = emptypb.Empty{}

type ClientCapability interface {
	CallContract(ctx context.Context, metadata capabilities.RequestMetadata, input *CallContractRequest) (*CallContractReply, error)

	FilterLogs(ctx context.Context, metadata capabilities.RequestMetadata, input *FilterLogsRequest) (*FilterLogsReply, error)

	BalanceAt(ctx context.Context, metadata capabilities.RequestMetadata, input *BalanceAtRequest) (*BalanceAtReply, error)

	EstimateGas(ctx context.Context, metadata capabilities.RequestMetadata, input *EstimateGasRequest) (*EstimateGasReply, error)

	GetTransactionByHash(ctx context.Context, metadata capabilities.RequestMetadata, input *GetTransactionByHashRequest) (*GetTransactionByHashReply, error)

	GetTransactionReceipt(ctx context.Context, metadata capabilities.RequestMetadata, input *GetTransactionReceiptRequest) (*GetTransactionReceiptReply, error)

	LatestAndFinalizedHead(ctx context.Context, metadata capabilities.RequestMetadata, input *emptypb.Empty) (*LatestAndFinalizedHeadReply, error)

	RegisterLogTracking(ctx context.Context, metadata capabilities.RequestMetadata, input *RegisterLogTrackingRequest) (*emptypb.Empty, error)

	UnregisterLogTracking(ctx context.Context, metadata capabilities.RequestMetadata, input *UnregisterLogTrackingRequest) (*emptypb.Empty, error)

	RegisterLogTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *FilterLogTriggerRequest) (<-chan capabilities.TriggerAndId[*Log], error)
	UnregisterLogTrigger(ctx context.Context, triggerID string, metadata capabilities.RequestMetadata, input *FilterLogTriggerRequest) error

	WriteReport(ctx context.Context, metadata capabilities.RequestMetadata, input *WriteReportRequest) (*WriteReportReply, error)

	Start(ctx context.Context) error
	Close() error
	HealthReport() map[string]error
	Name() string
	Description() string
	Ready() error
	Initialise(ctx context.Context, config string, telemetryService core.TelemetryService, store core.KeyValueStore, errorLog core.ErrorLog, pipelineRunner core.PipelineRunnerService, relayerSet core.RelayerSet, oracleFactory core.OracleFactory, gatewayConnector core.GatewayConnector) error
}

func NewClientServer(capability ClientCapability) *ClientServer {
	stopCh := make(chan struct{})
	return &ClientServer{
		clientCapability: clientCapability{ClientCapability: capability, stopCh: stopCh},
		stopCh:           stopCh,
	}
}

type ClientServer struct {
	clientCapability
	capabilityRegistry core.CapabilitiesRegistry
	stopCh             chan struct{}
}

func (cs *ClientServer) Initialise(ctx context.Context, config string, telemetryService core.TelemetryService, store core.KeyValueStore, capabilityRegistry core.CapabilitiesRegistry, errorLog core.ErrorLog, pipelineRunner core.PipelineRunnerService, relayerSet core.RelayerSet, oracleFactory core.OracleFactory, gatewayConnector core.GatewayConnector) error {
	if err := cs.ClientCapability.Initialise(ctx, config, telemetryService, store, errorLog, pipelineRunner, relayerSet, oracleFactory, gatewayConnector); err != nil {
		return fmt.Errorf("error when initializing capability: %w", err)
	}

	cs.capabilityRegistry = capabilityRegistry

	if err := capabilityRegistry.Add(ctx, &clientCapability{
		ClientCapability: cs.ClientCapability,
	}); err != nil {
		return fmt.Errorf("error when adding kv store action to the registry: %w", err)
	}

	return nil
}

func (cs *ClientServer) Close() error {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second)
	defer cancel()

	if cs.capabilityRegistry != nil {
		if err := cs.capabilityRegistry.Remove(ctx, "evm@1.0.0"); err != nil {
			return err
		}
	}

	if cs.stopCh != nil {
		close(cs.stopCh)
	}

	return cs.clientCapability.Close()
}

func (cs *ClientServer) Infos(ctx context.Context) ([]capabilities.CapabilityInfo, error) {
	info, err := cs.clientCapability.Info(ctx)
	if err != nil {
		return nil, err
	}
	return []capabilities.CapabilityInfo{info}, nil
}

type clientCapability struct {
	ClientCapability
	stopCh chan struct{}
}

func (c *clientCapability) Info(ctx context.Context) (capabilities.CapabilityInfo, error) {
	// Maybe we do need to split it out, even if the user doesn't see it
	return capabilities.NewCapabilityInfo("evm@1.0.0", capabilities.CapabilityTypeCombined, c.ClientCapability.Description())
}

var _ capabilities.ExecutableAndTriggerCapability = (*clientCapability)(nil)

const ClientID = "evm@1.0.0"

func (c *clientCapability) RegisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) (<-chan capabilities.TriggerResponse, error) {
	switch request.Method {
	case "LogTrigger":
		input := &FilterLogTriggerRequest{}
		return capabilities.RegisterTrigger(ctx, c.stopCh, "evm@1.0.0", request, input, c.ClientCapability.RegisterLogTrigger)
	default:
		return nil, fmt.Errorf("trigger %s not found", request.Method)
	}
}

func (c *clientCapability) UnregisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) error {
	switch request.Method {
	case "LogTrigger":
		input := &FilterLogTriggerRequest{}
		_, err := capabilities.FromValueOrAny(request.Config, request.Payload, input)
		if err != nil {
			return err
		}
		return c.ClientCapability.UnregisterLogTrigger(ctx, request.TriggerID, request.Metadata, input)
	default:
		return fmt.Errorf("method %s not found", request.Method)
	}
}

func (c *clientCapability) RegisterToWorkflow(ctx context.Context, request capabilities.RegisterToWorkflowRequest) error {
	return nil
}

func (c *clientCapability) UnregisterFromWorkflow(ctx context.Context, request capabilities.UnregisterFromWorkflowRequest) error {
	return nil
}

func (c *clientCapability) Execute(ctx context.Context, request capabilities.CapabilityRequest) (capabilities.CapabilityResponse, error) {
	response := capabilities.CapabilityResponse{}
	switch request.Method {
	case "CallContract":
		input := &CallContractRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *CallContractRequest, _ *emptypb.Empty) (*CallContractReply, error) {
			return c.ClientCapability.CallContract(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "FilterLogs":
		input := &FilterLogsRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *FilterLogsRequest, _ *emptypb.Empty) (*FilterLogsReply, error) {
			return c.ClientCapability.FilterLogs(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "BalanceAt":
		input := &BalanceAtRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *BalanceAtRequest, _ *emptypb.Empty) (*BalanceAtReply, error) {
			return c.ClientCapability.BalanceAt(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "EstimateGas":
		input := &EstimateGasRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *EstimateGasRequest, _ *emptypb.Empty) (*EstimateGasReply, error) {
			return c.ClientCapability.EstimateGas(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "GetTransactionByHash":
		input := &GetTransactionByHashRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *GetTransactionByHashRequest, _ *emptypb.Empty) (*GetTransactionByHashReply, error) {
			return c.ClientCapability.GetTransactionByHash(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "GetTransactionReceipt":
		input := &GetTransactionReceiptRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *GetTransactionReceiptRequest, _ *emptypb.Empty) (*GetTransactionReceiptReply, error) {
			return c.ClientCapability.GetTransactionReceipt(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "LatestAndFinalizedHead":
		input := &emptypb.Empty{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *emptypb.Empty, _ *emptypb.Empty) (*LatestAndFinalizedHeadReply, error) {
			return c.ClientCapability.LatestAndFinalizedHead(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "RegisterLogTracking":
		input := &RegisterLogTrackingRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *RegisterLogTrackingRequest, _ *emptypb.Empty) (*emptypb.Empty, error) {
			return c.ClientCapability.RegisterLogTracking(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "UnregisterLogTracking":
		input := &UnregisterLogTrackingRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *UnregisterLogTrackingRequest, _ *emptypb.Empty) (*emptypb.Empty, error) {
			return c.ClientCapability.UnregisterLogTracking(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	case "WriteReport":
		input := &WriteReportRequest{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *WriteReportRequest, _ *emptypb.Empty) (*WriteReportReply, error) {
			return c.ClientCapability.WriteReport(ctx, metadata, input)
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	default:
		return response, fmt.Errorf("method %s not found", request.Method)
	}
}
