// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package loadtestproxytest

import (
	"github.com/smartcontractkit/capabilities/loadtestproxy/loadtestproxy"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/testutils"
)

// ProxyTrigger registers a new capability mock with the runner
func ProxyTrigger(runner *testutils.Runner, fn func() (loadtestproxy.Payload, error)) *testutils.TriggerMock[loadtestproxy.Payload] {
	mock := testutils.MockTrigger[loadtestproxy.Payload]("proxy-trigger@0.0.1", fn)
	runner.MockCapability("proxy-trigger@0.0.1", nil, mock)
	return mock
}
