// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	chain_capabilitiessolana "github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/chain-capabilities/solana"
	chainssolana "github.com/smartcontractkit/chainlink-common/pkg/types/chains/solana"

	context "context"

	mock "github.com/stretchr/testify/mock"

	sdk "github.com/smartcontractkit/chainlink-protos/cre/go/sdk"

	solana "github.com/gagliardetto/solana-go"
)

// CREForwarderClient is an autogenerated mock type for the CREForwarderClient type
type CREForwarderClient struct {
	mock.Mock
}

type CREForwarderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *CREForwarderClient) EXPECT() *CREForwarderClient_Expecter {
	return &CREForwarderClient_Expecter{mock: &_m.Mock}
}

// InvokeOnReport provides a mock function with given fields: ctx, receiver, meta, report, gasConfig
func (_m *CREForwarderClient) InvokeOnReport(ctx context.Context, receiver solana.PublicKey, meta []*chain_capabilitiessolana.AccountMeta, report *sdk.ReportResponse, gasConfig *chain_capabilitiessolana.ComputeConfig) (*chainssolana.SubmitTransactionReply, error) {
	ret := _m.Called(ctx, receiver, meta, report, gasConfig)

	if len(ret) == 0 {
		panic("no return value specified for InvokeOnReport")
	}

	var r0 *chainssolana.SubmitTransactionReply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, []*chain_capabilitiessolana.AccountMeta, *sdk.ReportResponse, *chain_capabilitiessolana.ComputeConfig) (*chainssolana.SubmitTransactionReply, error)); ok {
		return rf(ctx, receiver, meta, report, gasConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, solana.PublicKey, []*chain_capabilitiessolana.AccountMeta, *sdk.ReportResponse, *chain_capabilitiessolana.ComputeConfig) *chainssolana.SubmitTransactionReply); ok {
		r0 = rf(ctx, receiver, meta, report, gasConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chainssolana.SubmitTransactionReply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, solana.PublicKey, []*chain_capabilitiessolana.AccountMeta, *sdk.ReportResponse, *chain_capabilitiessolana.ComputeConfig) error); ok {
		r1 = rf(ctx, receiver, meta, report, gasConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CREForwarderClient_InvokeOnReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeOnReport'
type CREForwarderClient_InvokeOnReport_Call struct {
	*mock.Call
}

// InvokeOnReport is a helper method to define mock.On call
//   - ctx context.Context
//   - receiver solana.PublicKey
//   - meta []*chain_capabilitiessolana.AccountMeta
//   - report *sdk.ReportResponse
//   - gasConfig *chain_capabilitiessolana.ComputeConfig
func (_e *CREForwarderClient_Expecter) InvokeOnReport(ctx interface{}, receiver interface{}, meta interface{}, report interface{}, gasConfig interface{}) *CREForwarderClient_InvokeOnReport_Call {
	return &CREForwarderClient_InvokeOnReport_Call{Call: _e.mock.On("InvokeOnReport", ctx, receiver, meta, report, gasConfig)}
}

func (_c *CREForwarderClient_InvokeOnReport_Call) Run(run func(ctx context.Context, receiver solana.PublicKey, meta []*chain_capabilitiessolana.AccountMeta, report *sdk.ReportResponse, gasConfig *chain_capabilitiessolana.ComputeConfig)) *CREForwarderClient_InvokeOnReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(solana.PublicKey), args[2].([]*chain_capabilitiessolana.AccountMeta), args[3].(*sdk.ReportResponse), args[4].(*chain_capabilitiessolana.ComputeConfig))
	})
	return _c
}

func (_c *CREForwarderClient_InvokeOnReport_Call) Return(_a0 *chainssolana.SubmitTransactionReply, _a1 error) *CREForwarderClient_InvokeOnReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CREForwarderClient_InvokeOnReport_Call) RunAndReturn(run func(context.Context, solana.PublicKey, []*chain_capabilitiessolana.AccountMeta, *sdk.ReportResponse, *chain_capabilitiessolana.ComputeConfig) (*chainssolana.SubmitTransactionReply, error)) *CREForwarderClient_InvokeOnReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewCREForwarderClient creates a new instance of CREForwarderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCREForwarderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *CREForwarderClient {
	mock := &CREForwarderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
