// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	chain_capabilitiesevm "github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/chain-capabilities/evm"

	context "context"

	contracts "github.com/smartcontractkit/chain_capabilities/evm/contracts"

	evm "github.com/smartcontractkit/chainlink-common/pkg/types/chains/evm"

	mock "github.com/stretchr/testify/mock"
)

// KeystoneForwarderClient is an autogenerated mock type for the KeystoneForwarderClient type
type KeystoneForwarderClient struct {
	mock.Mock
}

type KeystoneForwarderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *KeystoneForwarderClient) EXPECT() *KeystoneForwarderClient_Expecter {
	return &KeystoneForwarderClient_Expecter{mock: &_m.Mock}
}

// GetReportProcessedEvents provides a mock function with given fields: ctx, receiver, workflowExecutionID, reportID
func (_m *KeystoneForwarderClient) GetReportProcessedEvents(ctx context.Context, receiver common.Address, workflowExecutionID [32]byte, reportID [2]byte) ([]*evm.Log, error) {
	ret := _m.Called(ctx, receiver, workflowExecutionID, reportID)

	if len(ret) == 0 {
		panic("no return value specified for GetReportProcessedEvents")
	}

	var r0 []*evm.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, [32]byte, [2]byte) ([]*evm.Log, error)); ok {
		return rf(ctx, receiver, workflowExecutionID, reportID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, [32]byte, [2]byte) []*evm.Log); ok {
		r0 = rf(ctx, receiver, workflowExecutionID, reportID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*evm.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, [32]byte, [2]byte) error); ok {
		r1 = rf(ctx, receiver, workflowExecutionID, reportID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeystoneForwarderClient_GetReportProcessedEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReportProcessedEvents'
type KeystoneForwarderClient_GetReportProcessedEvents_Call struct {
	*mock.Call
}

// GetReportProcessedEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - receiver common.Address
//   - workflowExecutionID [32]byte
//   - reportID [2]byte
func (_e *KeystoneForwarderClient_Expecter) GetReportProcessedEvents(ctx interface{}, receiver interface{}, workflowExecutionID interface{}, reportID interface{}) *KeystoneForwarderClient_GetReportProcessedEvents_Call {
	return &KeystoneForwarderClient_GetReportProcessedEvents_Call{Call: _e.mock.On("GetReportProcessedEvents", ctx, receiver, workflowExecutionID, reportID)}
}

func (_c *KeystoneForwarderClient_GetReportProcessedEvents_Call) Run(run func(ctx context.Context, receiver common.Address, workflowExecutionID [32]byte, reportID [2]byte)) *KeystoneForwarderClient_GetReportProcessedEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].([32]byte), args[3].([2]byte))
	})
	return _c
}

func (_c *KeystoneForwarderClient_GetReportProcessedEvents_Call) Return(_a0 []*evm.Log, _a1 error) *KeystoneForwarderClient_GetReportProcessedEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeystoneForwarderClient_GetReportProcessedEvents_Call) RunAndReturn(run func(context.Context, common.Address, [32]byte, [2]byte) ([]*evm.Log, error)) *KeystoneForwarderClient_GetReportProcessedEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransmissionInfo provides a mock function with given fields: ctx, transmissionID
func (_m *KeystoneForwarderClient) GetTransmissionInfo(ctx context.Context, transmissionID contracts.TransmissionID) (contracts.TransmissionInfo, error) {
	ret := _m.Called(ctx, transmissionID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransmissionInfo")
	}

	var r0 contracts.TransmissionInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, contracts.TransmissionID) (contracts.TransmissionInfo, error)); ok {
		return rf(ctx, transmissionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, contracts.TransmissionID) contracts.TransmissionInfo); ok {
		r0 = rf(ctx, transmissionID)
	} else {
		r0 = ret.Get(0).(contracts.TransmissionInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, contracts.TransmissionID) error); ok {
		r1 = rf(ctx, transmissionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeystoneForwarderClient_GetTransmissionInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransmissionInfo'
type KeystoneForwarderClient_GetTransmissionInfo_Call struct {
	*mock.Call
}

// GetTransmissionInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - transmissionID contracts.TransmissionID
func (_e *KeystoneForwarderClient_Expecter) GetTransmissionInfo(ctx interface{}, transmissionID interface{}) *KeystoneForwarderClient_GetTransmissionInfo_Call {
	return &KeystoneForwarderClient_GetTransmissionInfo_Call{Call: _e.mock.On("GetTransmissionInfo", ctx, transmissionID)}
}

func (_c *KeystoneForwarderClient_GetTransmissionInfo_Call) Run(run func(ctx context.Context, transmissionID contracts.TransmissionID)) *KeystoneForwarderClient_GetTransmissionInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(contracts.TransmissionID))
	})
	return _c
}

func (_c *KeystoneForwarderClient_GetTransmissionInfo_Call) Return(_a0 contracts.TransmissionInfo, _a1 error) *KeystoneForwarderClient_GetTransmissionInfo_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeystoneForwarderClient_GetTransmissionInfo_Call) RunAndReturn(run func(context.Context, contracts.TransmissionID) (contracts.TransmissionInfo, error)) *KeystoneForwarderClient_GetTransmissionInfo_Call {
	_c.Call.Return(run)
	return _c
}

// InvokeOnReport provides a mock function with given fields: ctx, receiverAddress, report, gasConfig
func (_m *KeystoneForwarderClient) InvokeOnReport(ctx context.Context, receiverAddress common.Address, report *chain_capabilitiesevm.SignedReport, gasConfig *chain_capabilitiesevm.GasConfig) (*evm.TransactionResult, error) {
	ret := _m.Called(ctx, receiverAddress, report, gasConfig)

	if len(ret) == 0 {
		panic("no return value specified for InvokeOnReport")
	}

	var r0 *evm.TransactionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *chain_capabilitiesevm.SignedReport, *chain_capabilitiesevm.GasConfig) (*evm.TransactionResult, error)); ok {
		return rf(ctx, receiverAddress, report, gasConfig)
	}
	if rf, ok := ret.Get(0).(func(context.Context, common.Address, *chain_capabilitiesevm.SignedReport, *chain_capabilitiesevm.GasConfig) *evm.TransactionResult); ok {
		r0 = rf(ctx, receiverAddress, report, gasConfig)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*evm.TransactionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, common.Address, *chain_capabilitiesevm.SignedReport, *chain_capabilitiesevm.GasConfig) error); ok {
		r1 = rf(ctx, receiverAddress, report, gasConfig)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KeystoneForwarderClient_InvokeOnReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeOnReport'
type KeystoneForwarderClient_InvokeOnReport_Call struct {
	*mock.Call
}

// InvokeOnReport is a helper method to define mock.On call
//   - ctx context.Context
//   - receiverAddress common.Address
//   - report *chain_capabilitiesevm.SignedReport
//   - gasConfig *chain_capabilitiesevm.GasConfig
func (_e *KeystoneForwarderClient_Expecter) InvokeOnReport(ctx interface{}, receiverAddress interface{}, report interface{}, gasConfig interface{}) *KeystoneForwarderClient_InvokeOnReport_Call {
	return &KeystoneForwarderClient_InvokeOnReport_Call{Call: _e.mock.On("InvokeOnReport", ctx, receiverAddress, report, gasConfig)}
}

func (_c *KeystoneForwarderClient_InvokeOnReport_Call) Run(run func(ctx context.Context, receiverAddress common.Address, report *chain_capabilitiesevm.SignedReport, gasConfig *chain_capabilitiesevm.GasConfig)) *KeystoneForwarderClient_InvokeOnReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(common.Address), args[2].(*chain_capabilitiesevm.SignedReport), args[3].(*chain_capabilitiesevm.GasConfig))
	})
	return _c
}

func (_c *KeystoneForwarderClient_InvokeOnReport_Call) Return(_a0 *evm.TransactionResult, _a1 error) *KeystoneForwarderClient_InvokeOnReport_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KeystoneForwarderClient_InvokeOnReport_Call) RunAndReturn(run func(context.Context, common.Address, *chain_capabilitiesevm.SignedReport, *chain_capabilitiesevm.GasConfig) (*evm.TransactionResult, error)) *KeystoneForwarderClient_InvokeOnReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewKeystoneForwarderClient creates a new instance of KeystoneForwarderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeystoneForwarderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeystoneForwarderClient {
	mock := &KeystoneForwarderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
