dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
fail-on-missing: true
packages:
  github.com/smartcontractkit/capabilities/chain_capabilities/evm/consensus/poller:
    interfaces:
      ObservationsStore:

