dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
fail-on-missing: true
packages:
  github.com/smartcontractkit/capabilities/chain_capabilities/evm/actions:
    interfaces:
      ConsensusHandler:
  github.com/smartcontractkit/capabilities/chain_capabilities/evm/height:
    interfaces:
      HeaderProvider:
  github.com/smartcontractkit/chainlink-common/pkg/beholder:
    config:
      dir: ../monitoring/mocks
    interfaces:
      ProtoEmitter:
  github.com/smartcontractkit/chainlink-common/pkg/logger:
    config:
      dir: ../monitoring/mocks
    interfaces:
      Logger:
  github.com/smartcontractkit/capabilities/chain_capabilities/evm/internal/contracts:
    interfaces:
      CREForwarderClient:
        
