// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package kvcaptest

import (
	"github.com/smartcontractkit/capabilities/kvstore/kvcap"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/testutils"
)

// WriteTarget registers a new capability mock with the runner
func WriteTarget(runner *testutils.Runner, fn func(input kvcap.WriteInputs) error) *testutils.TargetMock[kvcap.WriteInputs] {
	mock := testutils.MockTarget[kvcap.WriteInputs]("kv-store-target@1.0.0", fn)
	runner.MockCapability("kv-store-target@1.0.0", nil, mock)
	return mock
}
