dir: "{{ .InterfaceDir }}/mocks"
mockname: "{{ .InterfaceName }}"
outpkg: mocks
filename: "{{ .InterfaceName | snakecase }}.go"
fail-on-missing: true
resolve-type-alias: false
packages:
  github.com/smartcontractkit/capabilities/chain_capabilities/stellar/height:
    interfaces:
      LedgerProvider:
