feed_id: "0x616c65785f746573745f300000000000"
feed_description: "PoR Feed With Read-Fetch-Write and Params (config file)"
cron_trigger_interval: 60
endpoint_timeout_milliseconds: 5000
balance_reader: "0x93c4bB995e7B5a726c8ef1bED9EA92e300F18eb4"
