// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	types "github.com/smartcontractkit/capabilities/chain_capabilities/evm/consensus/types"
	mock "github.com/stretchr/testify/mock"
)

// Poller is an autogenerated mock type for the Poller type
type Poller struct {
	mock.Mock
}

type Poller_Expecter struct {
	mock *mock.Mock
}

func (_m *Poller) EXPECT() *Poller_Expecter {
	return &Poller_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function with given fields: ctx, request
func (_m *Poller) Enqueue(ctx context.Context, request types.ObservableRequest) {
	_m.Called(ctx, request)
}

// Poller_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type Poller_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - request types.ObservableRequest
func (_e *Poller_Expecter) Enqueue(ctx interface{}, request interface{}) *Poller_Enqueue_Call {
	return &Poller_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, request)}
}

func (_c *Poller_Enqueue_Call) Run(run func(ctx context.Context, request types.ObservableRequest)) *Poller_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.ObservableRequest))
	})
	return _c
}

func (_c *Poller_Enqueue_Call) Return() *Poller_Enqueue_Call {
	_c.Call.Return()
	return _c
}

func (_c *Poller_Enqueue_Call) RunAndReturn(run func(context.Context, types.ObservableRequest)) *Poller_Enqueue_Call {
	_c.Run(run)
	return _c
}

// NewPoller creates a new instance of Poller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPoller(t interface {
	mock.TestingT
	Cleanup(func())
}) *Poller {
	mock := &Poller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
