// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: chain_capabilities/evm/monitoring/log_trigger.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        [][]byte               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // list of possible values for any topic, in [32]byte fix-sized array format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicValues) Reset() {
	*x = TopicValues{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicValues) ProtoMessage() {}

func (x *TopicValues) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicValues.ProtoReflect.Descriptor instead.
func (*TopicValues) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *TopicValues) GetValues() [][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

type FilterLogTriggerRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Addresses [][]byte               `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"` // list of addresses to include in evm address [20]byte fix-sized array format, at least one address is required
	// TopicValues is a fixed 4 length array of possible values for any topic where:
	// a) the first element is an array of the event signatures (keccak256 of the event name and indexed args types), it has to have at least one value
	// b) the second element is an array of possible values for the first indexed argument, can be empty
	// c) the third element is an array of possible values for the second indexed argument, can be empty
	// d) the fourth element is an array of possible values for the third indexed argument, can be empty
	Topics        []*TopicValues `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Confidence    int64          `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"` // optional, defaults to "SAFE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterLogTriggerRequest) Reset() {
	*x = FilterLogTriggerRequest{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterLogTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterLogTriggerRequest) ProtoMessage() {}

func (x *FilterLogTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterLogTriggerRequest.ProtoReflect.Descriptor instead.
func (*FilterLogTriggerRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *FilterLogTriggerRequest) GetAddresses() [][]byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *FilterLogTriggerRequest) GetTopics() []*TopicValues {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *FilterLogTriggerRequest) GetConfidence() int64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type LogTriggerInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *FilterLogTriggerRequest     `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogTriggerInitiated) Reset() {
	*x = LogTriggerInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTriggerInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTriggerInitiated) ProtoMessage() {}

func (x *LogTriggerInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTriggerInitiated.ProtoReflect.Descriptor instead.
func (*LogTriggerInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{2}
}

func (x *LogTriggerInitiated) GetReq() *FilterLogTriggerRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *LogTriggerInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type LogTriggerSuccess struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	TriggerID         string                       `protobuf:"bytes,1,opt,name=triggerID,proto3" json:"triggerID,omitempty"`
	Req               *FilterLogTriggerRequest     `protobuf:"bytes,2,opt,name=req,proto3" json:"req,omitempty"`
	LogCount          int32                        `protobuf:"varint,3,opt,name=log_count,json=logCount,proto3" json:"log_count,omitempty"`
	LatestOffsetBlock int64                        `protobuf:"varint,4,opt,name=latestOffsetBlock,proto3" json:"latestOffsetBlock,omitempty"`
	ExecutionContext  *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogTriggerSuccess) Reset() {
	*x = LogTriggerSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTriggerSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTriggerSuccess) ProtoMessage() {}

func (x *LogTriggerSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTriggerSuccess.ProtoReflect.Descriptor instead.
func (*LogTriggerSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{3}
}

func (x *LogTriggerSuccess) GetTriggerID() string {
	if x != nil {
		return x.TriggerID
	}
	return ""
}

func (x *LogTriggerSuccess) GetReq() *FilterLogTriggerRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *LogTriggerSuccess) GetLogCount() int32 {
	if x != nil {
		return x.LogCount
	}
	return 0
}

func (x *LogTriggerSuccess) GetLatestOffsetBlock() int64 {
	if x != nil {
		return x.LatestOffsetBlock
	}
	return 0
}

func (x *LogTriggerSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type LogTriggerError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	TriggerID        string                       `protobuf:"bytes,1,opt,name=triggerID,proto3" json:"triggerID,omitempty"`
	Summary          string                       `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogTriggerError) Reset() {
	*x = LogTriggerError{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTriggerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTriggerError) ProtoMessage() {}

func (x *LogTriggerError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTriggerError.ProtoReflect.Descriptor instead.
func (*LogTriggerError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{4}
}

func (x *LogTriggerError) GetTriggerID() string {
	if x != nil {
		return x.TriggerID
	}
	return ""
}

func (x *LogTriggerError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LogTriggerError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *LogTriggerError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type LogTriggerEventDroppedError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	TriggerID        string                       `protobuf:"bytes,1,opt,name=triggerID,proto3" json:"triggerID,omitempty"`
	TxHash           string                       `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHash        string                       `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	LogIndex         int64                        `protobuf:"varint,4,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Summary          string                       `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	IsLimitError     bool                         `protobuf:"varint,7,opt,name=isLimitError,proto3" json:"isLimitError,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogTriggerEventDroppedError) Reset() {
	*x = LogTriggerEventDroppedError{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTriggerEventDroppedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTriggerEventDroppedError) ProtoMessage() {}

func (x *LogTriggerEventDroppedError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTriggerEventDroppedError.ProtoReflect.Descriptor instead.
func (*LogTriggerEventDroppedError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{5}
}

func (x *LogTriggerEventDroppedError) GetTriggerID() string {
	if x != nil {
		return x.TriggerID
	}
	return ""
}

func (x *LogTriggerEventDroppedError) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *LogTriggerEventDroppedError) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *LogTriggerEventDroppedError) GetLogIndex() int64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *LogTriggerEventDroppedError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LogTriggerEventDroppedError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *LogTriggerEventDroppedError) GetIsLimitError() bool {
	if x != nil {
		return x.IsLimitError
	}
	return false
}

func (x *LogTriggerEventDroppedError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type LogTriggerCleanUpError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Summary          string                       `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogTriggerCleanUpError) Reset() {
	*x = LogTriggerCleanUpError{}
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogTriggerCleanUpError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogTriggerCleanUpError) ProtoMessage() {}

func (x *LogTriggerCleanUpError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogTriggerCleanUpError.ProtoReflect.Descriptor instead.
func (*LogTriggerCleanUpError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP(), []int{6}
}

func (x *LogTriggerCleanUpError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *LogTriggerCleanUpError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *LogTriggerCleanUpError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_chain_capabilities_evm_monitoring_log_trigger_proto protoreflect.FileDescriptor

const file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDesc = "" +
	"\n" +
	"3chain_capabilities/evm/monitoring/log_trigger.proto\x12\x16chain_capabilities.evm\x1a'libs/monitoring/execution_context.proto\"%\n" +
	"\vTopicValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\fR\x06values\"\x94\x01\n" +
	"\x17FilterLogTriggerRequest\x12\x1c\n" +
	"\taddresses\x18\x01 \x03(\fR\taddresses\x12;\n" +
	"\x06topics\x18\x02 \x03(\v2#.chain_capabilities.evm.TopicValuesR\x06topics\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x03R\n" +
	"confidence\"\xa3\x01\n" +
	"\x13LogTriggerInitiated\x12A\n" +
	"\x03req\x18\x01 \x01(\v2/.chain_capabilities.evm.FilterLogTriggerRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x8a\x02\n" +
	"\x11LogTriggerSuccess\x12\x1c\n" +
	"\ttriggerID\x18\x01 \x01(\tR\ttriggerID\x12A\n" +
	"\x03req\x18\x02 \x01(\v2/.chain_capabilities.evm.FilterLogTriggerRequestR\x03req\x12\x1b\n" +
	"\tlog_count\x18\x03 \x01(\x05R\blogCount\x12,\n" +
	"\x11latestOffsetBlock\x18\x04 \x01(\x03R\x11latestOffsetBlock\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xaa\x01\n" +
	"\x0fLogTriggerError\x12\x1c\n" +
	"\ttriggerID\x18\x01 \x01(\tR\ttriggerID\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x06 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xaf\x02\n" +
	"\x1bLogTriggerEventDroppedError\x12\x1c\n" +
	"\ttriggerID\x18\x01 \x01(\tR\ttriggerID\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12\x1b\n" +
	"\tlog_index\x18\x04 \x01(\x03R\blogIndex\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x06 \x01(\tR\x05cause\x12\"\n" +
	"\fisLimitError\x18\a \x01(\bR\fisLimitError\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x93\x01\n" +
	"\x16LogTriggerCleanUpError\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x06 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContextBLZJgithub.com/smartcontractkit/capabilities/chain_capabilities/evm;monitoringb\x06proto3"

var (
	file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescOnce sync.Once
	file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescData []byte
)

func file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescGZIP() []byte {
	file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDesc), len(file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDesc)))
	})
	return file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDescData
}

var file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chain_capabilities_evm_monitoring_log_trigger_proto_goTypes = []any{
	(*TopicValues)(nil),                 // 0: chain_capabilities.evm.TopicValues
	(*FilterLogTriggerRequest)(nil),     // 1: chain_capabilities.evm.FilterLogTriggerRequest
	(*LogTriggerInitiated)(nil),         // 2: chain_capabilities.evm.LogTriggerInitiated
	(*LogTriggerSuccess)(nil),           // 3: chain_capabilities.evm.LogTriggerSuccess
	(*LogTriggerError)(nil),             // 4: chain_capabilities.evm.LogTriggerError
	(*LogTriggerEventDroppedError)(nil), // 5: chain_capabilities.evm.LogTriggerEventDroppedError
	(*LogTriggerCleanUpError)(nil),      // 6: chain_capabilities.evm.LogTriggerCleanUpError
	(*monitoring.ExecutionContext)(nil), // 7: monitoring.ExecutionContext
}
var file_chain_capabilities_evm_monitoring_log_trigger_proto_depIdxs = []int32{
	0, // 0: chain_capabilities.evm.FilterLogTriggerRequest.topics:type_name -> chain_capabilities.evm.TopicValues
	1, // 1: chain_capabilities.evm.LogTriggerInitiated.req:type_name -> chain_capabilities.evm.FilterLogTriggerRequest
	7, // 2: chain_capabilities.evm.LogTriggerInitiated.execution_context:type_name -> monitoring.ExecutionContext
	1, // 3: chain_capabilities.evm.LogTriggerSuccess.req:type_name -> chain_capabilities.evm.FilterLogTriggerRequest
	7, // 4: chain_capabilities.evm.LogTriggerSuccess.execution_context:type_name -> monitoring.ExecutionContext
	7, // 5: chain_capabilities.evm.LogTriggerError.execution_context:type_name -> monitoring.ExecutionContext
	7, // 6: chain_capabilities.evm.LogTriggerEventDroppedError.execution_context:type_name -> monitoring.ExecutionContext
	7, // 7: chain_capabilities.evm.LogTriggerCleanUpError.execution_context:type_name -> monitoring.ExecutionContext
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_chain_capabilities_evm_monitoring_log_trigger_proto_init() }
func file_chain_capabilities_evm_monitoring_log_trigger_proto_init() {
	if File_chain_capabilities_evm_monitoring_log_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDesc), len(file_chain_capabilities_evm_monitoring_log_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_capabilities_evm_monitoring_log_trigger_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_evm_monitoring_log_trigger_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_evm_monitoring_log_trigger_proto_msgTypes,
	}.Build()
	File_chain_capabilities_evm_monitoring_log_trigger_proto = out.File
	file_chain_capabilities_evm_monitoring_log_trigger_proto_goTypes = nil
	file_chain_capabilities_evm_monitoring_log_trigger_proto_depIdxs = nil
}
