// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: log_trigger.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	evm "github.com/smartcontractkit/chainlink-common/pkg/capabilities/v2/chain-capabilities/evm"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *evm.FilterLogTriggerRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TriggerInitiated) Reset() {
	*x = TriggerInitiated{}
	mi := &file_log_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerInitiated) ProtoMessage() {}

func (x *TriggerInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_log_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerInitiated.ProtoReflect.Descriptor instead.
func (*TriggerInitiated) Descriptor() ([]byte, []int) {
	return file_log_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerInitiated) GetReq() *evm.FilterLogTriggerRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *TriggerInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type TriggerEventDroppedError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	TriggerID        string                       `protobuf:"bytes,1,opt,name=triggerID,proto3" json:"triggerID,omitempty"`
	TxHash           string                       `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	BlockHash        string                       `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	LogIndex         int64                        `protobuf:"varint,4,opt,name=log_index,json=logIndex,proto3" json:"log_index,omitempty"`
	Summary          string                       `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TriggerEventDroppedError) Reset() {
	*x = TriggerEventDroppedError{}
	mi := &file_log_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventDroppedError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventDroppedError) ProtoMessage() {}

func (x *TriggerEventDroppedError) ProtoReflect() protoreflect.Message {
	mi := &file_log_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventDroppedError.ProtoReflect.Descriptor instead.
func (*TriggerEventDroppedError) Descriptor() ([]byte, []int) {
	return file_log_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerEventDroppedError) GetTriggerID() string {
	if x != nil {
		return x.TriggerID
	}
	return ""
}

func (x *TriggerEventDroppedError) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TriggerEventDroppedError) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *TriggerEventDroppedError) GetLogIndex() int64 {
	if x != nil {
		return x.LogIndex
	}
	return 0
}

func (x *TriggerEventDroppedError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *TriggerEventDroppedError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *TriggerEventDroppedError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_log_trigger_proto protoreflect.FileDescriptor

const file_log_trigger_proto_rawDesc = "" +
	"\n" +
	"\x11log_trigger.proto\x12\x16chain_capabilities.evm\x1a0capabilities/blockchain/evm/v1alpha/client.proto\x1a'libs/monitoring/execution_context.proto\"\xad\x01\n" +
	"\x10TriggerInitiated\x12N\n" +
	"\x03req\x18\x01 \x01(\v2<.capabilities.blockchain.evm.v1alpha.FilterLogTriggerRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x88\x02\n" +
	"\x18TriggerEventDroppedError\x12\x1c\n" +
	"\ttriggerID\x18\x01 \x01(\tR\ttriggerID\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12\x1b\n" +
	"\tlog_index\x18\x04 \x01(\x03R\blogIndex\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x06 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContextBLZJgithub.com/smartcontractkit/capabilities/chain_capabilities/evm;monitoringb\x06proto3"

var (
	file_log_trigger_proto_rawDescOnce sync.Once
	file_log_trigger_proto_rawDescData []byte
)

func file_log_trigger_proto_rawDescGZIP() []byte {
	file_log_trigger_proto_rawDescOnce.Do(func() {
		file_log_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_log_trigger_proto_rawDesc), len(file_log_trigger_proto_rawDesc)))
	})
	return file_log_trigger_proto_rawDescData
}

var file_log_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_log_trigger_proto_goTypes = []any{
	(*TriggerInitiated)(nil),            // 0: chain_capabilities.evm.TriggerInitiated
	(*TriggerEventDroppedError)(nil),    // 1: chain_capabilities.evm.TriggerEventDroppedError
	(*evm.FilterLogTriggerRequest)(nil), // 2: capabilities.blockchain.evm.v1alpha.FilterLogTriggerRequest
	(*monitoring.ExecutionContext)(nil), // 3: monitoring.ExecutionContext
}
var file_log_trigger_proto_depIdxs = []int32{
	2, // 0: chain_capabilities.evm.TriggerInitiated.req:type_name -> capabilities.blockchain.evm.v1alpha.FilterLogTriggerRequest
	3, // 1: chain_capabilities.evm.TriggerInitiated.execution_context:type_name -> monitoring.ExecutionContext
	3, // 2: chain_capabilities.evm.TriggerEventDroppedError.execution_context:type_name -> monitoring.ExecutionContext
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_log_trigger_proto_init() }
func file_log_trigger_proto_init() {
	if File_log_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_log_trigger_proto_rawDesc), len(file_log_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_log_trigger_proto_goTypes,
		DependencyIndexes: file_log_trigger_proto_depIdxs,
		MessageInfos:      file_log_trigger_proto_msgTypes,
	}.Build()
	File_log_trigger_proto = out.File
	file_log_trigger_proto_goTypes = nil
	file_log_trigger_proto_depIdxs = nil
}
