// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: chain_capabilities/evm/monitoring/read_actions.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallContractRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber     int64                  `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	ContractAddress string                 `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CallContractRequest) Reset() {
	*x = CallContractRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractRequest) ProtoMessage() {}

func (x *CallContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractRequest.ProtoReflect.Descriptor instead.
func (*CallContractRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{0}
}

func (x *CallContractRequest) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *CallContractRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

type CallContractInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *CallContractRequest         `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallContractInitiated) Reset() {
	*x = CallContractInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractInitiated) ProtoMessage() {}

func (x *CallContractInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractInitiated.ProtoReflect.Descriptor instead.
func (*CallContractInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{1}
}

func (x *CallContractInitiated) GetReq() *CallContractRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *CallContractInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type CallContractSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *CallContractRequest         `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallContractSuccess) Reset() {
	*x = CallContractSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractSuccess) ProtoMessage() {}

func (x *CallContractSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractSuccess.ProtoReflect.Descriptor instead.
func (*CallContractSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{2}
}

func (x *CallContractSuccess) GetReq() *CallContractRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *CallContractSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type CallContractError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *CallContractRequest         `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CallContractError) Reset() {
	*x = CallContractError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractError) ProtoMessage() {}

func (x *CallContractError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractError.ProtoReflect.Descriptor instead.
func (*CallContractError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{3}
}

func (x *CallContractError) GetReq() *CallContractRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *CallContractError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CallContractError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *CallContractError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type Topics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         []string               `protobuf:"bytes,1,rep,name=topic,proto3" json:"topic,omitempty"` // in [32]byte fix-sized array format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topics) Reset() {
	*x = Topics{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topics) ProtoMessage() {}

func (x *Topics) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topics.ProtoReflect.Descriptor instead.
func (*Topics) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{4}
}

func (x *Topics) GetTopic() []string {
	if x != nil {
		return x.Topic
	}
	return nil
}

type FilterLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromBlock     int64                  `protobuf:"varint,1,opt,name=from_block,json=fromBlock,proto3" json:"from_block,omitempty"`
	ToBlock       int64                  `protobuf:"varint,2,opt,name=to_block,json=toBlock,proto3" json:"to_block,omitempty"`
	BlockHash     string                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"` // exact block (cant use from/to), in [32]byte fix-sized array format
	Addresses     []string               `protobuf:"bytes,4,rep,name=addresses,proto3" json:"addresses,omitempty"`                  // contract(s) to filter logs from in evm address [20]byte fix-sized array format
	Topics        []*Topics              `protobuf:"bytes,5,rep,name=topics,proto3" json:"topics,omitempty"`                        // filter log by event signature and indexed args
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterLogsRequest) Reset() {
	*x = FilterLogsRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterLogsRequest) ProtoMessage() {}

func (x *FilterLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterLogsRequest.ProtoReflect.Descriptor instead.
func (*FilterLogsRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{5}
}

func (x *FilterLogsRequest) GetFromBlock() int64 {
	if x != nil {
		return x.FromBlock
	}
	return 0
}

func (x *FilterLogsRequest) GetToBlock() int64 {
	if x != nil {
		return x.ToBlock
	}
	return 0
}

func (x *FilterLogsRequest) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *FilterLogsRequest) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *FilterLogsRequest) GetTopics() []*Topics {
	if x != nil {
		return x.Topics
	}
	return nil
}

type FilterLogsInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *FilterLogsRequest           `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FilterLogsInitiated) Reset() {
	*x = FilterLogsInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterLogsInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterLogsInitiated) ProtoMessage() {}

func (x *FilterLogsInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterLogsInitiated.ProtoReflect.Descriptor instead.
func (*FilterLogsInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{6}
}

func (x *FilterLogsInitiated) GetReq() *FilterLogsRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *FilterLogsInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type FilterLogsSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *FilterLogsRequest           `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	LogCount         int32                        `protobuf:"varint,2,opt,name=log_count,json=logCount,proto3" json:"log_count,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FilterLogsSuccess) Reset() {
	*x = FilterLogsSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterLogsSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterLogsSuccess) ProtoMessage() {}

func (x *FilterLogsSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterLogsSuccess.ProtoReflect.Descriptor instead.
func (*FilterLogsSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{7}
}

func (x *FilterLogsSuccess) GetReq() *FilterLogsRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *FilterLogsSuccess) GetLogCount() int32 {
	if x != nil {
		return x.LogCount
	}
	return 0
}

func (x *FilterLogsSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type FilterLogsError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *FilterLogsRequest           `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FilterLogsError) Reset() {
	*x = FilterLogsError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterLogsError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterLogsError) ProtoMessage() {}

func (x *FilterLogsError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterLogsError.ProtoReflect.Descriptor instead.
func (*FilterLogsError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{8}
}

func (x *FilterLogsError) GetReq() *FilterLogsRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *FilterLogsError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FilterLogsError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *FilterLogsError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type BalanceAtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	BlockNumber   int64                  `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceAtRequest) Reset() {
	*x = BalanceAtRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceAtRequest) ProtoMessage() {}

func (x *BalanceAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceAtRequest.ProtoReflect.Descriptor instead.
func (*BalanceAtRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{9}
}

func (x *BalanceAtRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BalanceAtRequest) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type BalanceAtInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *BalanceAtRequest            `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceAtInitiated) Reset() {
	*x = BalanceAtInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceAtInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceAtInitiated) ProtoMessage() {}

func (x *BalanceAtInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceAtInitiated.ProtoReflect.Descriptor instead.
func (*BalanceAtInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceAtInitiated) GetReq() *BalanceAtRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *BalanceAtInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type BalanceAtSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *BalanceAtRequest            `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Balance          string                       `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceAtSuccess) Reset() {
	*x = BalanceAtSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceAtSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceAtSuccess) ProtoMessage() {}

func (x *BalanceAtSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceAtSuccess.ProtoReflect.Descriptor instead.
func (*BalanceAtSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{11}
}

func (x *BalanceAtSuccess) GetReq() *BalanceAtRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *BalanceAtSuccess) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *BalanceAtSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type BalanceAtError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *BalanceAtRequest            `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BalanceAtError) Reset() {
	*x = BalanceAtError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceAtError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceAtError) ProtoMessage() {}

func (x *BalanceAtError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceAtError.ProtoReflect.Descriptor instead.
func (*BalanceAtError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{12}
}

func (x *BalanceAtError) GetReq() *BalanceAtRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *BalanceAtError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *BalanceAtError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *BalanceAtError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type EstimateGasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateGasRequest) Reset() {
	*x = EstimateGasRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasRequest) ProtoMessage() {}

func (x *EstimateGasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasRequest.ProtoReflect.Descriptor instead.
func (*EstimateGasRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{13}
}

func (x *EstimateGasRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EstimateGasRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EstimateGasRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type EstimateGasInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *EstimateGasRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EstimateGasInitiated) Reset() {
	*x = EstimateGasInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasInitiated) ProtoMessage() {}

func (x *EstimateGasInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasInitiated.ProtoReflect.Descriptor instead.
func (*EstimateGasInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{14}
}

func (x *EstimateGasInitiated) GetReq() *EstimateGasRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *EstimateGasInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type EstimateGasSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *EstimateGasRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Gas              int64                        `protobuf:"varint,2,opt,name=gas,proto3" json:"gas,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EstimateGasSuccess) Reset() {
	*x = EstimateGasSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasSuccess) ProtoMessage() {}

func (x *EstimateGasSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasSuccess.ProtoReflect.Descriptor instead.
func (*EstimateGasSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{15}
}

func (x *EstimateGasSuccess) GetReq() *EstimateGasRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *EstimateGasSuccess) GetGas() int64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *EstimateGasSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type EstimateGasError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *EstimateGasRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EstimateGasError) Reset() {
	*x = EstimateGasError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateGasError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateGasError) ProtoMessage() {}

func (x *EstimateGasError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateGasError.ProtoReflect.Descriptor instead.
func (*EstimateGasError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{16}
}

func (x *EstimateGasError) GetReq() *EstimateGasRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *EstimateGasError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *EstimateGasError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *EstimateGasError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type Receipt struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            uint64                 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	TxHash            string                 `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ContractAddress   string                 `protobuf:"bytes,3,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	GasUsed           uint64                 `protobuf:"varint,4,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	BlockHash         string                 `protobuf:"bytes,5,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockNumber       uint64                 `protobuf:"varint,6,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TransactionIndex  uint64                 `protobuf:"varint,7,opt,name=transaction_index,json=transactionIndex,proto3" json:"transaction_index,omitempty"`
	EffectiveGasPrice uint64                 `protobuf:"varint,8,opt,name=effective_gas_price,json=effectiveGasPrice,proto3" json:"effective_gas_price,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{17}
}

func (x *Receipt) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Receipt) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Receipt) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *Receipt) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *Receipt) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *Receipt) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *Receipt) GetTransactionIndex() uint64 {
	if x != nil {
		return x.TransactionIndex
	}
	return 0
}

func (x *Receipt) GetEffectiveGasPrice() uint64 {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return 0
}

type GetTransactionByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionByHashRequest) Reset() {
	*x = GetTransactionByHashRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashRequest) ProtoMessage() {}

func (x *GetTransactionByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{18}
}

func (x *GetTransactionByHashRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetTransactionByHashInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *GetTransactionByHashRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionByHashInitiated) Reset() {
	*x = GetTransactionByHashInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashInitiated) ProtoMessage() {}

func (x *GetTransactionByHashInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashInitiated.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{19}
}

func (x *GetTransactionByHashInitiated) GetReq() *GetTransactionByHashRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetTransactionByHashInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type TransactionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	TxNonce       uint64                 `protobuf:"varint,2,opt,name=tx_nonce,json=txNonce,proto3" json:"tx_nonce,omitempty"`
	Gas           uint64                 `protobuf:"varint,3,opt,name=gas,proto3" json:"gas,omitempty"`
	GasPrice      uint64                 `protobuf:"varint,4,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Value         uint64                 `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionData) Reset() {
	*x = TransactionData{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionData) ProtoMessage() {}

func (x *TransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionData.ProtoReflect.Descriptor instead.
func (*TransactionData) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{20}
}

func (x *TransactionData) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionData) GetTxNonce() uint64 {
	if x != nil {
		return x.TxNonce
	}
	return 0
}

func (x *TransactionData) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *TransactionData) GetGasPrice() uint64 {
	if x != nil {
		return x.GasPrice
	}
	return 0
}

func (x *TransactionData) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetTransactionByHashSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *GetTransactionByHashRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Transaction      *TransactionData             `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionByHashSuccess) Reset() {
	*x = GetTransactionByHashSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashSuccess) ProtoMessage() {}

func (x *GetTransactionByHashSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashSuccess.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{21}
}

func (x *GetTransactionByHashSuccess) GetReq() *GetTransactionByHashRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetTransactionByHashSuccess) GetTransaction() *TransactionData {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *GetTransactionByHashSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type GetTransactionByHashError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *GetTransactionByHashRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionByHashError) Reset() {
	*x = GetTransactionByHashError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionByHashError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionByHashError) ProtoMessage() {}

func (x *GetTransactionByHashError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionByHashError.ProtoReflect.Descriptor instead.
func (*GetTransactionByHashError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{22}
}

func (x *GetTransactionByHashError) GetReq() *GetTransactionByHashRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetTransactionByHashError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetTransactionByHashError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *GetTransactionByHashError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type GetTransactionReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionReceiptRequest) Reset() {
	*x = GetTransactionReceiptRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptRequest) ProtoMessage() {}

func (x *GetTransactionReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{23}
}

func (x *GetTransactionReceiptRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetTransactionReceiptInitiated struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Req              *GetTransactionReceiptRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext  `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionReceiptInitiated) Reset() {
	*x = GetTransactionReceiptInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptInitiated) ProtoMessage() {}

func (x *GetTransactionReceiptInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptInitiated.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{24}
}

func (x *GetTransactionReceiptInitiated) GetReq() *GetTransactionReceiptRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetTransactionReceiptInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type GetTransactionReceiptSuccess struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Req              *GetTransactionReceiptRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Receipt          *Receipt                      `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	ExecutionContext *monitoring.ExecutionContext  `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionReceiptSuccess) Reset() {
	*x = GetTransactionReceiptSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptSuccess) ProtoMessage() {}

func (x *GetTransactionReceiptSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptSuccess.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{25}
}

func (x *GetTransactionReceiptSuccess) GetReq() *GetTransactionReceiptRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetTransactionReceiptSuccess) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *GetTransactionReceiptSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type GetTransactionReceiptError struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	Req              *GetTransactionReceiptRequest `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                        `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                        `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext  `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionReceiptError) Reset() {
	*x = GetTransactionReceiptError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptError) ProtoMessage() {}

func (x *GetTransactionReceiptError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptError.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{26}
}

func (x *GetTransactionReceiptError) GetReq() *GetTransactionReceiptRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *GetTransactionReceiptError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetTransactionReceiptError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *GetTransactionReceiptError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type HeaderByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   int64                  `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderByNumberRequest) Reset() {
	*x = HeaderByNumberRequest{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderByNumberRequest) ProtoMessage() {}

func (x *HeaderByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderByNumberRequest.ProtoReflect.Descriptor instead.
func (*HeaderByNumberRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{27}
}

func (x *HeaderByNumberRequest) GetBlockNumber() int64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type HeaderByNumberInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *HeaderByNumberRequest       `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeaderByNumberInitiated) Reset() {
	*x = HeaderByNumberInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderByNumberInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderByNumberInitiated) ProtoMessage() {}

func (x *HeaderByNumberInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderByNumberInitiated.ProtoReflect.Descriptor instead.
func (*HeaderByNumberInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{28}
}

func (x *HeaderByNumberInitiated) GetReq() *HeaderByNumberRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *HeaderByNumberInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type BlockData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BlockHash      string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight    string                 `protobuf:"bytes,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	BlockTimestamp uint64                 `protobuf:"varint,3,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BlockData) Reset() {
	*x = BlockData{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockData) ProtoMessage() {}

func (x *BlockData) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockData.ProtoReflect.Descriptor instead.
func (*BlockData) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{29}
}

func (x *BlockData) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *BlockData) GetBlockHeight() string {
	if x != nil {
		return x.BlockHeight
	}
	return ""
}

func (x *BlockData) GetBlockTimestamp() uint64 {
	if x != nil {
		return x.BlockTimestamp
	}
	return 0
}

type HeaderByNumberSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *HeaderByNumberRequest       `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Header           *BlockData                   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeaderByNumberSuccess) Reset() {
	*x = HeaderByNumberSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderByNumberSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderByNumberSuccess) ProtoMessage() {}

func (x *HeaderByNumberSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderByNumberSuccess.ProtoReflect.Descriptor instead.
func (*HeaderByNumberSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{30}
}

func (x *HeaderByNumberSuccess) GetReq() *HeaderByNumberRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *HeaderByNumberSuccess) GetHeader() *BlockData {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HeaderByNumberSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type HeaderByNumberError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *HeaderByNumberRequest       `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeaderByNumberError) Reset() {
	*x = HeaderByNumberError{}
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderByNumberError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderByNumberError) ProtoMessage() {}

func (x *HeaderByNumberError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderByNumberError.ProtoReflect.Descriptor instead.
func (*HeaderByNumberError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP(), []int{31}
}

func (x *HeaderByNumberError) GetReq() *HeaderByNumberRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *HeaderByNumberError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *HeaderByNumberError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *HeaderByNumberError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

var File_chain_capabilities_evm_monitoring_read_actions_proto protoreflect.FileDescriptor

const file_chain_capabilities_evm_monitoring_read_actions_proto_rawDesc = "" +
	"\n" +
	"4chain_capabilities/evm/monitoring/read_actions.proto\x12\x16chain_capabilities.evm\x1a'libs/monitoring/execution_context.proto\"c\n" +
	"\x13CallContractRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x03R\vblockNumber\x12)\n" +
	"\x10contract_address\x18\x02 \x01(\tR\x0fcontractAddress\"\xa1\x01\n" +
	"\x15CallContractInitiated\x12=\n" +
	"\x03req\x18\x01 \x01(\v2+.chain_capabilities.evm.CallContractRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x9f\x01\n" +
	"\x13CallContractSuccess\x12=\n" +
	"\x03req\x18\x01 \x01(\v2+.chain_capabilities.evm.CallContractRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xcd\x01\n" +
	"\x11CallContractError\x12=\n" +
	"\x03req\x18\x01 \x01(\v2+.chain_capabilities.evm.CallContractRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x1e\n" +
	"\x06Topics\x12\x14\n" +
	"\x05topic\x18\x01 \x03(\tR\x05topic\"\xc2\x01\n" +
	"\x11FilterLogsRequest\x12\x1d\n" +
	"\n" +
	"from_block\x18\x01 \x01(\x03R\tfromBlock\x12\x19\n" +
	"\bto_block\x18\x02 \x01(\x03R\atoBlock\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\tR\tblockHash\x12\x1c\n" +
	"\taddresses\x18\x04 \x03(\tR\taddresses\x126\n" +
	"\x06topics\x18\x05 \x03(\v2\x1e.chain_capabilities.evm.TopicsR\x06topics\"\x9d\x01\n" +
	"\x13FilterLogsInitiated\x12;\n" +
	"\x03req\x18\x01 \x01(\v2).chain_capabilities.evm.FilterLogsRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xb8\x01\n" +
	"\x11FilterLogsSuccess\x12;\n" +
	"\x03req\x18\x01 \x01(\v2).chain_capabilities.evm.FilterLogsRequestR\x03req\x12\x1b\n" +
	"\tlog_count\x18\x02 \x01(\x05R\blogCount\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xc9\x01\n" +
	"\x0fFilterLogsError\x12;\n" +
	"\x03req\x18\x01 \x01(\v2).chain_capabilities.evm.FilterLogsRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"O\n" +
	"\x10BalanceAtRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x03R\vblockNumber\"\x9b\x01\n" +
	"\x12BalanceAtInitiated\x12:\n" +
	"\x03req\x18\x01 \x01(\v2(.chain_capabilities.evm.BalanceAtRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xb3\x01\n" +
	"\x10BalanceAtSuccess\x12:\n" +
	"\x03req\x18\x01 \x01(\v2(.chain_capabilities.evm.BalanceAtRequestR\x03req\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xc7\x01\n" +
	"\x0eBalanceAtError\x12:\n" +
	"\x03req\x18\x01 \x01(\v2(.chain_capabilities.evm.BalanceAtRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"L\n" +
	"\x12EstimateGasRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\x9f\x01\n" +
	"\x14EstimateGasInitiated\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.EstimateGasRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xaf\x01\n" +
	"\x12EstimateGasSuccess\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.EstimateGasRequestR\x03req\x12\x10\n" +
	"\x03gas\x18\x02 \x01(\x03R\x03gas\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xcb\x01\n" +
	"\x10EstimateGasError\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.EstimateGasRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x9f\x02\n" +
	"\aReceipt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x04R\x06status\x12\x17\n" +
	"\atx_hash\x18\x02 \x01(\tR\x06txHash\x12)\n" +
	"\x10contract_address\x18\x03 \x01(\tR\x0fcontractAddress\x12\x19\n" +
	"\bgas_used\x18\x04 \x01(\x04R\agasUsed\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x05 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_number\x18\x06 \x01(\x04R\vblockNumber\x12+\n" +
	"\x11transaction_index\x18\a \x01(\x04R\x10transactionIndex\x12.\n" +
	"\x13effective_gas_price\x18\b \x01(\x04R\x11effectiveGasPrice\"1\n" +
	"\x1bGetTransactionByHashRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xb1\x01\n" +
	"\x1dGetTransactionByHashInitiated\x12E\n" +
	"\x03req\x18\x01 \x01(\v23.chain_capabilities.evm.GetTransactionByHashRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x8a\x01\n" +
	"\x0fTransactionData\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\btx_nonce\x18\x02 \x01(\x04R\atxNonce\x12\x10\n" +
	"\x03gas\x18\x03 \x01(\x04R\x03gas\x12\x1b\n" +
	"\tgas_price\x18\x04 \x01(\x04R\bgasPrice\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x04R\x05value\"\xfa\x01\n" +
	"\x1bGetTransactionByHashSuccess\x12E\n" +
	"\x03req\x18\x01 \x01(\v23.chain_capabilities.evm.GetTransactionByHashRequestR\x03req\x12I\n" +
	"\vtransaction\x18\x02 \x01(\v2'.chain_capabilities.evm.TransactionDataR\vtransaction\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xdd\x01\n" +
	"\x19GetTransactionByHashError\x12E\n" +
	"\x03req\x18\x01 \x01(\v23.chain_capabilities.evm.GetTransactionByHashRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"2\n" +
	"\x1cGetTransactionReceiptRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\xb3\x01\n" +
	"\x1eGetTransactionReceiptInitiated\x12F\n" +
	"\x03req\x18\x01 \x01(\v24.chain_capabilities.evm.GetTransactionReceiptRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xec\x01\n" +
	"\x1cGetTransactionReceiptSuccess\x12F\n" +
	"\x03req\x18\x01 \x01(\v24.chain_capabilities.evm.GetTransactionReceiptRequestR\x03req\x129\n" +
	"\areceipt\x18\x02 \x01(\v2\x1f.chain_capabilities.evm.ReceiptR\areceipt\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xdf\x01\n" +
	"\x1aGetTransactionReceiptError\x12F\n" +
	"\x03req\x18\x01 \x01(\v24.chain_capabilities.evm.GetTransactionReceiptRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\":\n" +
	"\x15HeaderByNumberRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x03R\vblockNumber\"\xa5\x01\n" +
	"\x17HeaderByNumberInitiated\x12?\n" +
	"\x03req\x18\x01 \x01(\v2-.chain_capabilities.evm.HeaderByNumberRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"v\n" +
	"\tBlockData\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_height\x18\x02 \x01(\tR\vblockHeight\x12'\n" +
	"\x0fblock_timestamp\x18\x03 \x01(\x04R\x0eblockTimestamp\"\xde\x01\n" +
	"\x15HeaderByNumberSuccess\x12?\n" +
	"\x03req\x18\x01 \x01(\v2-.chain_capabilities.evm.HeaderByNumberRequestR\x03req\x129\n" +
	"\x06header\x18\x02 \x01(\v2!.chain_capabilities.evm.BlockDataR\x06header\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xd1\x01\n" +
	"\x13HeaderByNumberError\x12?\n" +
	"\x03req\x18\x01 \x01(\v2-.chain_capabilities.evm.HeaderByNumberRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContextBLZJgithub.com/smartcontractkit/capabilities/chain_capabilities/evm;monitoringb\x06proto3"

var (
	file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescOnce sync.Once
	file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescData []byte
)

func file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescGZIP() []byte {
	file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_evm_monitoring_read_actions_proto_rawDesc), len(file_chain_capabilities_evm_monitoring_read_actions_proto_rawDesc)))
	})
	return file_chain_capabilities_evm_monitoring_read_actions_proto_rawDescData
}

var file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_chain_capabilities_evm_monitoring_read_actions_proto_goTypes = []any{
	(*CallContractRequest)(nil),            // 0: chain_capabilities.evm.CallContractRequest
	(*CallContractInitiated)(nil),          // 1: chain_capabilities.evm.CallContractInitiated
	(*CallContractSuccess)(nil),            // 2: chain_capabilities.evm.CallContractSuccess
	(*CallContractError)(nil),              // 3: chain_capabilities.evm.CallContractError
	(*Topics)(nil),                         // 4: chain_capabilities.evm.Topics
	(*FilterLogsRequest)(nil),              // 5: chain_capabilities.evm.FilterLogsRequest
	(*FilterLogsInitiated)(nil),            // 6: chain_capabilities.evm.FilterLogsInitiated
	(*FilterLogsSuccess)(nil),              // 7: chain_capabilities.evm.FilterLogsSuccess
	(*FilterLogsError)(nil),                // 8: chain_capabilities.evm.FilterLogsError
	(*BalanceAtRequest)(nil),               // 9: chain_capabilities.evm.BalanceAtRequest
	(*BalanceAtInitiated)(nil),             // 10: chain_capabilities.evm.BalanceAtInitiated
	(*BalanceAtSuccess)(nil),               // 11: chain_capabilities.evm.BalanceAtSuccess
	(*BalanceAtError)(nil),                 // 12: chain_capabilities.evm.BalanceAtError
	(*EstimateGasRequest)(nil),             // 13: chain_capabilities.evm.EstimateGasRequest
	(*EstimateGasInitiated)(nil),           // 14: chain_capabilities.evm.EstimateGasInitiated
	(*EstimateGasSuccess)(nil),             // 15: chain_capabilities.evm.EstimateGasSuccess
	(*EstimateGasError)(nil),               // 16: chain_capabilities.evm.EstimateGasError
	(*Receipt)(nil),                        // 17: chain_capabilities.evm.Receipt
	(*GetTransactionByHashRequest)(nil),    // 18: chain_capabilities.evm.GetTransactionByHashRequest
	(*GetTransactionByHashInitiated)(nil),  // 19: chain_capabilities.evm.GetTransactionByHashInitiated
	(*TransactionData)(nil),                // 20: chain_capabilities.evm.TransactionData
	(*GetTransactionByHashSuccess)(nil),    // 21: chain_capabilities.evm.GetTransactionByHashSuccess
	(*GetTransactionByHashError)(nil),      // 22: chain_capabilities.evm.GetTransactionByHashError
	(*GetTransactionReceiptRequest)(nil),   // 23: chain_capabilities.evm.GetTransactionReceiptRequest
	(*GetTransactionReceiptInitiated)(nil), // 24: chain_capabilities.evm.GetTransactionReceiptInitiated
	(*GetTransactionReceiptSuccess)(nil),   // 25: chain_capabilities.evm.GetTransactionReceiptSuccess
	(*GetTransactionReceiptError)(nil),     // 26: chain_capabilities.evm.GetTransactionReceiptError
	(*HeaderByNumberRequest)(nil),          // 27: chain_capabilities.evm.HeaderByNumberRequest
	(*HeaderByNumberInitiated)(nil),        // 28: chain_capabilities.evm.HeaderByNumberInitiated
	(*BlockData)(nil),                      // 29: chain_capabilities.evm.BlockData
	(*HeaderByNumberSuccess)(nil),          // 30: chain_capabilities.evm.HeaderByNumberSuccess
	(*HeaderByNumberError)(nil),            // 31: chain_capabilities.evm.HeaderByNumberError
	(*monitoring.ExecutionContext)(nil),    // 32: monitoring.ExecutionContext
}
var file_chain_capabilities_evm_monitoring_read_actions_proto_depIdxs = []int32{
	0,  // 0: chain_capabilities.evm.CallContractInitiated.req:type_name -> chain_capabilities.evm.CallContractRequest
	32, // 1: chain_capabilities.evm.CallContractInitiated.execution_context:type_name -> monitoring.ExecutionContext
	0,  // 2: chain_capabilities.evm.CallContractSuccess.req:type_name -> chain_capabilities.evm.CallContractRequest
	32, // 3: chain_capabilities.evm.CallContractSuccess.execution_context:type_name -> monitoring.ExecutionContext
	0,  // 4: chain_capabilities.evm.CallContractError.req:type_name -> chain_capabilities.evm.CallContractRequest
	32, // 5: chain_capabilities.evm.CallContractError.execution_context:type_name -> monitoring.ExecutionContext
	4,  // 6: chain_capabilities.evm.FilterLogsRequest.topics:type_name -> chain_capabilities.evm.Topics
	5,  // 7: chain_capabilities.evm.FilterLogsInitiated.req:type_name -> chain_capabilities.evm.FilterLogsRequest
	32, // 8: chain_capabilities.evm.FilterLogsInitiated.execution_context:type_name -> monitoring.ExecutionContext
	5,  // 9: chain_capabilities.evm.FilterLogsSuccess.req:type_name -> chain_capabilities.evm.FilterLogsRequest
	32, // 10: chain_capabilities.evm.FilterLogsSuccess.execution_context:type_name -> monitoring.ExecutionContext
	5,  // 11: chain_capabilities.evm.FilterLogsError.req:type_name -> chain_capabilities.evm.FilterLogsRequest
	32, // 12: chain_capabilities.evm.FilterLogsError.execution_context:type_name -> monitoring.ExecutionContext
	9,  // 13: chain_capabilities.evm.BalanceAtInitiated.req:type_name -> chain_capabilities.evm.BalanceAtRequest
	32, // 14: chain_capabilities.evm.BalanceAtInitiated.execution_context:type_name -> monitoring.ExecutionContext
	9,  // 15: chain_capabilities.evm.BalanceAtSuccess.req:type_name -> chain_capabilities.evm.BalanceAtRequest
	32, // 16: chain_capabilities.evm.BalanceAtSuccess.execution_context:type_name -> monitoring.ExecutionContext
	9,  // 17: chain_capabilities.evm.BalanceAtError.req:type_name -> chain_capabilities.evm.BalanceAtRequest
	32, // 18: chain_capabilities.evm.BalanceAtError.execution_context:type_name -> monitoring.ExecutionContext
	13, // 19: chain_capabilities.evm.EstimateGasInitiated.req:type_name -> chain_capabilities.evm.EstimateGasRequest
	32, // 20: chain_capabilities.evm.EstimateGasInitiated.execution_context:type_name -> monitoring.ExecutionContext
	13, // 21: chain_capabilities.evm.EstimateGasSuccess.req:type_name -> chain_capabilities.evm.EstimateGasRequest
	32, // 22: chain_capabilities.evm.EstimateGasSuccess.execution_context:type_name -> monitoring.ExecutionContext
	13, // 23: chain_capabilities.evm.EstimateGasError.req:type_name -> chain_capabilities.evm.EstimateGasRequest
	32, // 24: chain_capabilities.evm.EstimateGasError.execution_context:type_name -> monitoring.ExecutionContext
	18, // 25: chain_capabilities.evm.GetTransactionByHashInitiated.req:type_name -> chain_capabilities.evm.GetTransactionByHashRequest
	32, // 26: chain_capabilities.evm.GetTransactionByHashInitiated.execution_context:type_name -> monitoring.ExecutionContext
	18, // 27: chain_capabilities.evm.GetTransactionByHashSuccess.req:type_name -> chain_capabilities.evm.GetTransactionByHashRequest
	20, // 28: chain_capabilities.evm.GetTransactionByHashSuccess.transaction:type_name -> chain_capabilities.evm.TransactionData
	32, // 29: chain_capabilities.evm.GetTransactionByHashSuccess.execution_context:type_name -> monitoring.ExecutionContext
	18, // 30: chain_capabilities.evm.GetTransactionByHashError.req:type_name -> chain_capabilities.evm.GetTransactionByHashRequest
	32, // 31: chain_capabilities.evm.GetTransactionByHashError.execution_context:type_name -> monitoring.ExecutionContext
	23, // 32: chain_capabilities.evm.GetTransactionReceiptInitiated.req:type_name -> chain_capabilities.evm.GetTransactionReceiptRequest
	32, // 33: chain_capabilities.evm.GetTransactionReceiptInitiated.execution_context:type_name -> monitoring.ExecutionContext
	23, // 34: chain_capabilities.evm.GetTransactionReceiptSuccess.req:type_name -> chain_capabilities.evm.GetTransactionReceiptRequest
	17, // 35: chain_capabilities.evm.GetTransactionReceiptSuccess.receipt:type_name -> chain_capabilities.evm.Receipt
	32, // 36: chain_capabilities.evm.GetTransactionReceiptSuccess.execution_context:type_name -> monitoring.ExecutionContext
	23, // 37: chain_capabilities.evm.GetTransactionReceiptError.req:type_name -> chain_capabilities.evm.GetTransactionReceiptRequest
	32, // 38: chain_capabilities.evm.GetTransactionReceiptError.execution_context:type_name -> monitoring.ExecutionContext
	27, // 39: chain_capabilities.evm.HeaderByNumberInitiated.req:type_name -> chain_capabilities.evm.HeaderByNumberRequest
	32, // 40: chain_capabilities.evm.HeaderByNumberInitiated.execution_context:type_name -> monitoring.ExecutionContext
	27, // 41: chain_capabilities.evm.HeaderByNumberSuccess.req:type_name -> chain_capabilities.evm.HeaderByNumberRequest
	29, // 42: chain_capabilities.evm.HeaderByNumberSuccess.header:type_name -> chain_capabilities.evm.BlockData
	32, // 43: chain_capabilities.evm.HeaderByNumberSuccess.execution_context:type_name -> monitoring.ExecutionContext
	27, // 44: chain_capabilities.evm.HeaderByNumberError.req:type_name -> chain_capabilities.evm.HeaderByNumberRequest
	32, // 45: chain_capabilities.evm.HeaderByNumberError.execution_context:type_name -> monitoring.ExecutionContext
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_chain_capabilities_evm_monitoring_read_actions_proto_init() }
func file_chain_capabilities_evm_monitoring_read_actions_proto_init() {
	if File_chain_capabilities_evm_monitoring_read_actions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_evm_monitoring_read_actions_proto_rawDesc), len(file_chain_capabilities_evm_monitoring_read_actions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_capabilities_evm_monitoring_read_actions_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_evm_monitoring_read_actions_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_evm_monitoring_read_actions_proto_msgTypes,
	}.Build()
	File_chain_capabilities_evm_monitoring_read_actions_proto = out.File
	file_chain_capabilities_evm_monitoring_read_actions_proto_goTypes = nil
	file_chain_capabilities_evm_monitoring_read_actions_proto_depIdxs = nil
}
