// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: chain_capabilities/evm/monitoring/write_report.proto

package monitoring

import (
	monitoring "github.com/smartcontractkit/capabilities/libs/monitoring"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteReportInitiated struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportInitiated) Reset() {
	*x = WriteReportInitiated{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportInitiated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportInitiated) ProtoMessage() {}

func (x *WriteReportInitiated) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportInitiated.ProtoReflect.Descriptor instead.
func (*WriteReportInitiated) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{0}
}

func (x *WriteReportInitiated) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportInitiated) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportSuccess struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	LogCount         int32                        `protobuf:"varint,2,opt,name=log_count,json=logCount,proto3" json:"log_count,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportSuccess) Reset() {
	*x = WriteReportSuccess{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportSuccess) ProtoMessage() {}

func (x *WriteReportSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportSuccess.ProtoReflect.Descriptor instead.
func (*WriteReportSuccess) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{1}
}

func (x *WriteReportSuccess) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportSuccess) GetLogCount() int32 {
	if x != nil {
		return x.LogCount
	}
	return 0
}

func (x *WriteReportSuccess) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	IsUserError      bool                         `protobuf:"varint,4,opt,name=isUserError,proto3" json:"isUserError,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportError) Reset() {
	*x = WriteReportError{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportError) ProtoMessage() {}

func (x *WriteReportError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportError.ProtoReflect.Descriptor instead.
func (*WriteReportError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{2}
}

func (x *WriteReportError) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteReportError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteReportError) GetIsUserError() bool {
	if x != nil {
		return x.IsUserError
	}
	return false
}

func (x *WriteReportError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportTxFeeCalculationError struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Req              *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary          string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause            string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	TxIdempotencyKey string                       `protobuf:"bytes,4,opt,name=tx_idempotency_key,json=txIdempotencyKey,proto3" json:"tx_idempotency_key,omitempty"`
	ExecutionContext *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WriteReportTxFeeCalculationError) Reset() {
	*x = WriteReportTxFeeCalculationError{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportTxFeeCalculationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportTxFeeCalculationError) ProtoMessage() {}

func (x *WriteReportTxFeeCalculationError) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportTxFeeCalculationError.ProtoReflect.Descriptor instead.
func (*WriteReportTxFeeCalculationError) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{3}
}

func (x *WriteReportTxFeeCalculationError) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportTxFeeCalculationError) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteReportTxFeeCalculationError) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteReportTxFeeCalculationError) GetTxIdempotencyKey() string {
	if x != nil {
		return x.TxIdempotencyKey
	}
	return ""
}

func (x *WriteReportTxFeeCalculationError) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportInvalidTransmissionState struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Req               *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Summary           string                       `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Cause             string                       `protobuf:"bytes,3,opt,name=cause,proto3" json:"cause,omitempty"`
	TransmissionState uint32                       `protobuf:"varint,4,opt,name=transmission_state,json=transmissionState,proto3" json:"transmission_state,omitempty"`
	InvalidReceiver   bool                         `protobuf:"varint,5,opt,name=invalid_receiver,json=invalidReceiver,proto3" json:"invalid_receiver,omitempty"`
	Success           bool                         `protobuf:"varint,6,opt,name=success,proto3" json:"success,omitempty"`
	TransmissionId    string                       `protobuf:"bytes,7,opt,name=transmission_id,json=transmissionId,proto3" json:"transmission_id,omitempty"`
	Transmitter       string                       `protobuf:"bytes,8,opt,name=transmitter,proto3" json:"transmitter,omitempty"`
	ExecutionContext  *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WriteReportInvalidTransmissionState) Reset() {
	*x = WriteReportInvalidTransmissionState{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportInvalidTransmissionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportInvalidTransmissionState) ProtoMessage() {}

func (x *WriteReportInvalidTransmissionState) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportInvalidTransmissionState.ProtoReflect.Descriptor instead.
func (*WriteReportInvalidTransmissionState) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{4}
}

func (x *WriteReportInvalidTransmissionState) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportInvalidTransmissionState) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WriteReportInvalidTransmissionState) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *WriteReportInvalidTransmissionState) GetTransmissionState() uint32 {
	if x != nil {
		return x.TransmissionState
	}
	return 0
}

func (x *WriteReportInvalidTransmissionState) GetInvalidReceiver() bool {
	if x != nil {
		return x.InvalidReceiver
	}
	return false
}

func (x *WriteReportInvalidTransmissionState) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteReportInvalidTransmissionState) GetTransmissionId() string {
	if x != nil {
		return x.TransmissionId
	}
	return ""
}

func (x *WriteReportInvalidTransmissionState) GetTransmitter() string {
	if x != nil {
		return x.Transmitter
	}
	return ""
}

func (x *WriteReportInvalidTransmissionState) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportDuplicateTx struct {
	state                       protoimpl.MessageState       `protogen:"open.v1"`
	Req                         *WriteReportRequest          `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	DuplicateTransmissionTxHash string                       `protobuf:"bytes,2,opt,name=duplicate_transmission_tx_hash,json=duplicateTransmissionTxHash,proto3" json:"duplicate_transmission_tx_hash,omitempty"`
	TransmissionTxHash          string                       `protobuf:"bytes,3,opt,name=transmission_tx_hash,json=transmissionTxHash,proto3" json:"transmission_tx_hash,omitempty"`
	ExecutionContext            *monitoring.ExecutionContext `protobuf:"bytes,20,opt,name=execution_context,json=executionContext,proto3" json:"execution_context,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *WriteReportDuplicateTx) Reset() {
	*x = WriteReportDuplicateTx{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportDuplicateTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportDuplicateTx) ProtoMessage() {}

func (x *WriteReportDuplicateTx) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportDuplicateTx.ProtoReflect.Descriptor instead.
func (*WriteReportDuplicateTx) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{5}
}

func (x *WriteReportDuplicateTx) GetReq() *WriteReportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *WriteReportDuplicateTx) GetDuplicateTransmissionTxHash() string {
	if x != nil {
		return x.DuplicateTransmissionTxHash
	}
	return ""
}

func (x *WriteReportDuplicateTx) GetTransmissionTxHash() string {
	if x != nil {
		return x.TransmissionTxHash
	}
	return ""
}

func (x *WriteReportDuplicateTx) GetExecutionContext() *monitoring.ExecutionContext {
	if x != nil {
		return x.ExecutionContext
	}
	return nil
}

type WriteReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      []byte                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Report        *ReportResponse        `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	GasConfig     *GasConfig             `protobuf:"bytes,3,opt,name=gas_config,json=gasConfig,proto3,oneof" json:"gas_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReportRequest) Reset() {
	*x = WriteReportRequest{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReportRequest) ProtoMessage() {}

func (x *WriteReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReportRequest.ProtoReflect.Descriptor instead.
func (*WriteReportRequest) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{6}
}

func (x *WriteReportRequest) GetReceiver() []byte {
	if x != nil {
		return x.Receiver
	}
	return nil
}

func (x *WriteReportRequest) GetReport() *ReportResponse {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *WriteReportRequest) GetGasConfig() *GasConfig {
	if x != nil {
		return x.GasConfig
	}
	return nil
}

type GasConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GasLimit      uint64                 `protobuf:"varint,1,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GasConfig) Reset() {
	*x = GasConfig{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GasConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GasConfig) ProtoMessage() {}

func (x *GasConfig) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GasConfig.ProtoReflect.Descriptor instead.
func (*GasConfig) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{7}
}

func (x *GasConfig) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigDigest  []byte                 `protobuf:"bytes,1,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	SeqNr         uint64                 `protobuf:"varint,2,opt,name=seq_nr,json=seqNr,proto3" json:"seq_nr,omitempty"`
	ReportContext []byte                 `protobuf:"bytes,3,opt,name=report_context,json=reportContext,proto3" json:"report_context,omitempty"` // combination of seq_nr and config_digest
	RawReport     []byte                 `protobuf:"bytes,4,opt,name=raw_report,json=rawReport,proto3" json:"raw_report,omitempty"`
	Sigs          []*AttributedSignature `protobuf:"bytes,5,rep,name=sigs,proto3" json:"sigs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{8}
}

func (x *ReportResponse) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

func (x *ReportResponse) GetSeqNr() uint64 {
	if x != nil {
		return x.SeqNr
	}
	return 0
}

func (x *ReportResponse) GetReportContext() []byte {
	if x != nil {
		return x.ReportContext
	}
	return nil
}

func (x *ReportResponse) GetRawReport() []byte {
	if x != nil {
		return x.RawReport
	}
	return nil
}

func (x *ReportResponse) GetSigs() []*AttributedSignature {
	if x != nil {
		return x.Sigs
	}
	return nil
}

type AttributedSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	SignerId      uint32                 `protobuf:"varint,2,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributedSignature) Reset() {
	*x = AttributedSignature{}
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributedSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedSignature) ProtoMessage() {}

func (x *AttributedSignature) ProtoReflect() protoreflect.Message {
	mi := &file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedSignature.ProtoReflect.Descriptor instead.
func (*AttributedSignature) Descriptor() ([]byte, []int) {
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP(), []int{9}
}

func (x *AttributedSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AttributedSignature) GetSignerId() uint32 {
	if x != nil {
		return x.SignerId
	}
	return 0
}

var File_chain_capabilities_evm_monitoring_write_report_proto protoreflect.FileDescriptor

const file_chain_capabilities_evm_monitoring_write_report_proto_rawDesc = "" +
	"\n" +
	"4chain_capabilities/evm/monitoring/write_report.proto\x12\x16chain_capabilities.evm\x1a'libs/monitoring/execution_context.proto\"\x9f\x01\n" +
	"\x14WriteReportInitiated\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.WriteReportRequestR\x03req\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xba\x01\n" +
	"\x12WriteReportSuccess\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.WriteReportRequestR\x03req\x12\x1b\n" +
	"\tlog_count\x18\x02 \x01(\x05R\blogCount\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xed\x01\n" +
	"\x10WriteReportError\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.WriteReportRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12 \n" +
	"\visUserError\x18\x04 \x01(\bR\visUserError\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x89\x02\n" +
	" WriteReportTxFeeCalculationError\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.WriteReportRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12,\n" +
	"\x12tx_idempotency_key\x18\x04 \x01(\tR\x10txIdempotencyKey\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x9d\x03\n" +
	"#WriteReportInvalidTransmissionState\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.WriteReportRequestR\x03req\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05cause\x18\x03 \x01(\tR\x05cause\x12-\n" +
	"\x12transmission_state\x18\x04 \x01(\rR\x11transmissionState\x12)\n" +
	"\x10invalid_receiver\x18\x05 \x01(\bR\x0finvalidReceiver\x12\x18\n" +
	"\asuccess\x18\x06 \x01(\bR\asuccess\x12'\n" +
	"\x0ftransmission_id\x18\a \x01(\tR\x0etransmissionId\x12 \n" +
	"\vtransmitter\x18\b \x01(\tR\vtransmitter\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\x98\x02\n" +
	"\x16WriteReportDuplicateTx\x12<\n" +
	"\x03req\x18\x01 \x01(\v2*.chain_capabilities.evm.WriteReportRequestR\x03req\x12C\n" +
	"\x1eduplicate_transmission_tx_hash\x18\x02 \x01(\tR\x1bduplicateTransmissionTxHash\x120\n" +
	"\x14transmission_tx_hash\x18\x03 \x01(\tR\x12transmissionTxHash\x12I\n" +
	"\x11execution_context\x18\x14 \x01(\v2\x1c.monitoring.ExecutionContextR\x10executionContext\"\xc6\x01\n" +
	"\x12WriteReportRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\fR\breceiver\x12>\n" +
	"\x06report\x18\x02 \x01(\v2&.chain_capabilities.evm.ReportResponseR\x06report\x12E\n" +
	"\n" +
	"gas_config\x18\x03 \x01(\v2!.chain_capabilities.evm.GasConfigH\x00R\tgasConfig\x88\x01\x01B\r\n" +
	"\v_gas_config\"(\n" +
	"\tGasConfig\x12\x1b\n" +
	"\tgas_limit\x18\x01 \x01(\x04R\bgasLimit\"\xd3\x01\n" +
	"\x0eReportResponse\x12#\n" +
	"\rconfig_digest\x18\x01 \x01(\fR\fconfigDigest\x12\x15\n" +
	"\x06seq_nr\x18\x02 \x01(\x04R\x05seqNr\x12%\n" +
	"\x0ereport_context\x18\x03 \x01(\fR\rreportContext\x12\x1d\n" +
	"\n" +
	"raw_report\x18\x04 \x01(\fR\trawReport\x12?\n" +
	"\x04sigs\x18\x05 \x03(\v2+.chain_capabilities.evm.AttributedSignatureR\x04sigs\"P\n" +
	"\x13AttributedSignature\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigner_id\x18\x02 \x01(\rR\bsignerIdBLZJgithub.com/smartcontractkit/capabilities/chain_capabilities/evm;monitoringb\x06proto3"

var (
	file_chain_capabilities_evm_monitoring_write_report_proto_rawDescOnce sync.Once
	file_chain_capabilities_evm_monitoring_write_report_proto_rawDescData []byte
)

func file_chain_capabilities_evm_monitoring_write_report_proto_rawDescGZIP() []byte {
	file_chain_capabilities_evm_monitoring_write_report_proto_rawDescOnce.Do(func() {
		file_chain_capabilities_evm_monitoring_write_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chain_capabilities_evm_monitoring_write_report_proto_rawDesc), len(file_chain_capabilities_evm_monitoring_write_report_proto_rawDesc)))
	})
	return file_chain_capabilities_evm_monitoring_write_report_proto_rawDescData
}

var file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_chain_capabilities_evm_monitoring_write_report_proto_goTypes = []any{
	(*WriteReportInitiated)(nil),                // 0: chain_capabilities.evm.WriteReportInitiated
	(*WriteReportSuccess)(nil),                  // 1: chain_capabilities.evm.WriteReportSuccess
	(*WriteReportError)(nil),                    // 2: chain_capabilities.evm.WriteReportError
	(*WriteReportTxFeeCalculationError)(nil),    // 3: chain_capabilities.evm.WriteReportTxFeeCalculationError
	(*WriteReportInvalidTransmissionState)(nil), // 4: chain_capabilities.evm.WriteReportInvalidTransmissionState
	(*WriteReportDuplicateTx)(nil),              // 5: chain_capabilities.evm.WriteReportDuplicateTx
	(*WriteReportRequest)(nil),                  // 6: chain_capabilities.evm.WriteReportRequest
	(*GasConfig)(nil),                           // 7: chain_capabilities.evm.GasConfig
	(*ReportResponse)(nil),                      // 8: chain_capabilities.evm.ReportResponse
	(*AttributedSignature)(nil),                 // 9: chain_capabilities.evm.AttributedSignature
	(*monitoring.ExecutionContext)(nil),         // 10: monitoring.ExecutionContext
}
var file_chain_capabilities_evm_monitoring_write_report_proto_depIdxs = []int32{
	6,  // 0: chain_capabilities.evm.WriteReportInitiated.req:type_name -> chain_capabilities.evm.WriteReportRequest
	10, // 1: chain_capabilities.evm.WriteReportInitiated.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 2: chain_capabilities.evm.WriteReportSuccess.req:type_name -> chain_capabilities.evm.WriteReportRequest
	10, // 3: chain_capabilities.evm.WriteReportSuccess.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 4: chain_capabilities.evm.WriteReportError.req:type_name -> chain_capabilities.evm.WriteReportRequest
	10, // 5: chain_capabilities.evm.WriteReportError.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 6: chain_capabilities.evm.WriteReportTxFeeCalculationError.req:type_name -> chain_capabilities.evm.WriteReportRequest
	10, // 7: chain_capabilities.evm.WriteReportTxFeeCalculationError.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 8: chain_capabilities.evm.WriteReportInvalidTransmissionState.req:type_name -> chain_capabilities.evm.WriteReportRequest
	10, // 9: chain_capabilities.evm.WriteReportInvalidTransmissionState.execution_context:type_name -> monitoring.ExecutionContext
	6,  // 10: chain_capabilities.evm.WriteReportDuplicateTx.req:type_name -> chain_capabilities.evm.WriteReportRequest
	10, // 11: chain_capabilities.evm.WriteReportDuplicateTx.execution_context:type_name -> monitoring.ExecutionContext
	8,  // 12: chain_capabilities.evm.WriteReportRequest.report:type_name -> chain_capabilities.evm.ReportResponse
	7,  // 13: chain_capabilities.evm.WriteReportRequest.gas_config:type_name -> chain_capabilities.evm.GasConfig
	9,  // 14: chain_capabilities.evm.ReportResponse.sigs:type_name -> chain_capabilities.evm.AttributedSignature
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_chain_capabilities_evm_monitoring_write_report_proto_init() }
func file_chain_capabilities_evm_monitoring_write_report_proto_init() {
	if File_chain_capabilities_evm_monitoring_write_report_proto != nil {
		return
	}
	file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chain_capabilities_evm_monitoring_write_report_proto_rawDesc), len(file_chain_capabilities_evm_monitoring_write_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chain_capabilities_evm_monitoring_write_report_proto_goTypes,
		DependencyIndexes: file_chain_capabilities_evm_monitoring_write_report_proto_depIdxs,
		MessageInfos:      file_chain_capabilities_evm_monitoring_write_report_proto_msgTypes,
	}.Build()
	File_chain_capabilities_evm_monitoring_write_report_proto = out.File
	file_chain_capabilities_evm_monitoring_write_report_proto_goTypes = nil
	file_chain_capabilities_evm_monitoring_write_report_proto_depIdxs = nil
}
