// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	evm "github.com/smartcontractkit/chainlink-common/pkg/chains/evm"
	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/capabilities/chain_capabilities/evm/consensus/types"
)

// RequestsStore is an autogenerated mock type for the RequestsStore type
type RequestsStore struct {
	mock.Mock
}

type RequestsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestsStore) EXPECT() *RequestsStore_Expecter {
	return &RequestsStore_Expecter{mock: &_m.Mock}
}

// CompleteRequest provides a mock function with given fields: id, report
func (_m *RequestsStore) CompleteRequest(id string, report *evm.RequestReport) error {
	ret := _m.Called(id, report)

	if len(ret) == 0 {
		panic("no return value specified for CompleteRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *evm.RequestReport) error); ok {
		r0 = rf(id, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestsStore_CompleteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteRequest'
type RequestsStore_CompleteRequest_Call struct {
	*mock.Call
}

// CompleteRequest is a helper method to define mock.On call
//   - id string
//   - report *evm.RequestReport
func (_e *RequestsStore_Expecter) CompleteRequest(id interface{}, report interface{}) *RequestsStore_CompleteRequest_Call {
	return &RequestsStore_CompleteRequest_Call{Call: _e.mock.On("CompleteRequest", id, report)}
}

func (_c *RequestsStore_CompleteRequest_Call) Run(run func(id string, report *evm.RequestReport)) *RequestsStore_CompleteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*evm.RequestReport))
	})
	return _c
}

func (_c *RequestsStore_CompleteRequest_Call) Return(_a0 error) *RequestsStore_CompleteRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestsStore_CompleteRequest_Call) RunAndReturn(run func(string, *evm.RequestReport) error) *RequestsStore_CompleteRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function with given fields: id
func (_m *RequestsStore) GetRequest(id string) (types.Request, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 types.Request
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (types.Request, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) types.Request); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// RequestsStore_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type RequestsStore_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - id string
func (_e *RequestsStore_Expecter) GetRequest(id interface{}) *RequestsStore_GetRequest_Call {
	return &RequestsStore_GetRequest_Call{Call: _e.mock.On("GetRequest", id)}
}

func (_c *RequestsStore_GetRequest_Call) Run(run func(id string)) *RequestsStore_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RequestsStore_GetRequest_Call) Return(_a0 types.Request, _a1 bool) *RequestsStore_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RequestsStore_GetRequest_Call) RunAndReturn(run func(string) (types.Request, bool)) *RequestsStore_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestIDs provides a mock function with given fields: batchSize
func (_m *RequestsStore) GetRequestIDs(batchSize int) ([]string, error) {
	ret := _m.Called(batchSize)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return rf(batchSize)
	}
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(batchSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(batchSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestsStore_GetRequestIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestIDs'
type RequestsStore_GetRequestIDs_Call struct {
	*mock.Call
}

// GetRequestIDs is a helper method to define mock.On call
//   - batchSize int
func (_e *RequestsStore_Expecter) GetRequestIDs(batchSize interface{}) *RequestsStore_GetRequestIDs_Call {
	return &RequestsStore_GetRequestIDs_Call{Call: _e.mock.On("GetRequestIDs", batchSize)}
}

func (_c *RequestsStore_GetRequestIDs_Call) Run(run func(batchSize int)) *RequestsStore_GetRequestIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RequestsStore_GetRequestIDs_Call) Return(_a0 []string, _a1 error) *RequestsStore_GetRequestIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RequestsStore_GetRequestIDs_Call) RunAndReturn(run func(int) ([]string, error)) *RequestsStore_GetRequestIDs_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAttempted provides a mock function with given fields: id
func (_m *RequestsStore) MarkAttempted(id string) {
	_m.Called(id)
}

// RequestsStore_MarkAttempted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAttempted'
type RequestsStore_MarkAttempted_Call struct {
	*mock.Call
}

// MarkAttempted is a helper method to define mock.On call
//   - id string
func (_e *RequestsStore_Expecter) MarkAttempted(id interface{}) *RequestsStore_MarkAttempted_Call {
	return &RequestsStore_MarkAttempted_Call{Call: _e.mock.On("MarkAttempted", id)}
}

func (_c *RequestsStore_MarkAttempted_Call) Run(run func(id string)) *RequestsStore_MarkAttempted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RequestsStore_MarkAttempted_Call) Return() *RequestsStore_MarkAttempted_Call {
	_c.Call.Return()
	return _c
}

func (_c *RequestsStore_MarkAttempted_Call) RunAndReturn(run func(string)) *RequestsStore_MarkAttempted_Call {
	_c.Run(run)
	return _c
}

// NewRequestsStore creates a new instance of RequestsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestsStore {
	mock := &RequestsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
