dir: "{{ .InterfaceDir }}"
mockname: "{{ .InterfaceName }}_mock"
outpkg: actions
inpackage: true
filename: "test_{{ .InterfaceName | snakecase }}_mock.go"
fail-on-missing: true
packages:
  github.com/smartcontractkit/capabilities/chain_capabilities/solana/actions:
    interfaces:
      TransmissionInfoProvider:
      CREForwarderClient:
        
