// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ocr.proto

package types

import (
	pb "github.com/smartcontractkit/chainlink-common/pkg/values/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_REQUEST_TYPE_UNKNOWN               RequestType = 0
	RequestType_REQUEST_TYPE_EVENTUALLY_CONSISTENT RequestType = 1
	RequestType_REQUEST_TYPE_LOCKABLE_TO_BLOCK     RequestType = 2
	RequestType_REQUEST_TYPE_AGGREGATABLE          RequestType = 3
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_TYPE_UNKNOWN",
		1: "REQUEST_TYPE_EVENTUALLY_CONSISTENT",
		2: "REQUEST_TYPE_LOCKABLE_TO_BLOCK",
		3: "REQUEST_TYPE_AGGREGATABLE",
	}
	RequestType_value = map[string]int32{
		"REQUEST_TYPE_UNKNOWN":               0,
		"REQUEST_TYPE_EVENTUALLY_CONSISTENT": 1,
		"REQUEST_TYPE_LOCKABLE_TO_BLOCK":     2,
		"REQUEST_TYPE_AGGREGATABLE":          3,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_ocr_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_ocr_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{0}
}

type ChainHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latest        int64                  `protobuf:"varint,1,opt,name=latest,proto3" json:"latest,omitempty"`
	Safe          int64                  `protobuf:"varint,2,opt,name=safe,proto3" json:"safe,omitempty"`
	Finalized     int64                  `protobuf:"varint,3,opt,name=finalized,proto3" json:"finalized,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainHeight) Reset() {
	*x = ChainHeight{}
	mi := &file_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainHeight) ProtoMessage() {}

func (x *ChainHeight) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainHeight.ProtoReflect.Descriptor instead.
func (*ChainHeight) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *ChainHeight) GetLatest() int64 {
	if x != nil {
		return x.Latest
	}
	return 0
}

func (x *ChainHeight) GetSafe() int64 {
	if x != nil {
		return x.Safe
	}
	return 0
}

func (x *ChainHeight) GetFinalized() int64 {
	if x != nil {
		return x.Finalized
	}
	return 0
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestIDs    []string               `protobuf:"bytes,1,rep,name=requestIDs,proto3" json:"requestIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *Query) GetRequestIDs() []string {
	if x != nil {
		return x.RequestIDs
	}
	return nil
}

type AggregatableObservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Value         *pb.Decimal            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatableObservation) Reset() {
	*x = AggregatableObservation{}
	mi := &file_ocr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatableObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatableObservation) ProtoMessage() {}

func (x *AggregatableObservation) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatableObservation.ProtoReflect.Descriptor instead.
func (*AggregatableObservation) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{2}
}

func (x *AggregatableObservation) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AggregatableObservation) GetValue() *pb.Decimal {
	if x != nil {
		return x.Value
	}
	return nil
}

type RequestObservation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Observation:
	//
	//	*RequestObservation_LockableToBlock
	//	*RequestObservation_EventuallyConsistent
	//	*RequestObservation_Aggregatable
	Observation   isRequestObservation_Observation `protobuf_oneof:"observation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestObservation) Reset() {
	*x = RequestObservation{}
	mi := &file_ocr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestObservation) ProtoMessage() {}

func (x *RequestObservation) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestObservation.ProtoReflect.Descriptor instead.
func (*RequestObservation) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{3}
}

func (x *RequestObservation) GetObservation() isRequestObservation_Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *RequestObservation) GetLockableToBlock() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Observation.(*RequestObservation_LockableToBlock); ok {
			return x.LockableToBlock
		}
	}
	return nil
}

func (x *RequestObservation) GetEventuallyConsistent() []byte {
	if x != nil {
		if x, ok := x.Observation.(*RequestObservation_EventuallyConsistent); ok {
			return x.EventuallyConsistent
		}
	}
	return nil
}

func (x *RequestObservation) GetAggregatable() *AggregatableObservation {
	if x != nil {
		if x, ok := x.Observation.(*RequestObservation_Aggregatable); ok {
			return x.Aggregatable
		}
	}
	return nil
}

type isRequestObservation_Observation interface {
	isRequestObservation_Observation()
}

type RequestObservation_LockableToBlock struct {
	LockableToBlock *emptypb.Empty `protobuf:"bytes,1,opt,name=lockableToBlock,proto3,oneof"`
}

type RequestObservation_EventuallyConsistent struct {
	EventuallyConsistent []byte `protobuf:"bytes,2,opt,name=eventuallyConsistent,proto3,oneof"`
}

type RequestObservation_Aggregatable struct {
	Aggregatable *AggregatableObservation `protobuf:"bytes,3,opt,name=aggregatable,proto3,oneof"`
}

func (*RequestObservation_LockableToBlock) isRequestObservation_Observation() {}

func (*RequestObservation_EventuallyConsistent) isRequestObservation_Observation() {}

func (*RequestObservation_Aggregatable) isRequestObservation_Observation() {}

type Observation struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ChainHeight   *ChainHeight                   `protobuf:"bytes,1,opt,name=chainHeight,proto3" json:"chainHeight,omitempty"`
	Observations  map[string]*RequestObservation `protobuf:"bytes,2,rep,name=observations,proto3" json:"observations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_ocr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{4}
}

func (x *Observation) GetChainHeight() *ChainHeight {
	if x != nil {
		return x.ChainHeight
	}
	return nil
}

func (x *Observation) GetObservations() map[string]*RequestObservation {
	if x != nil {
		return x.Observations
	}
	return nil
}

type RequestOutcome struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestID string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*RequestOutcome_LockableToBlock
	//	*RequestOutcome_EventuallyConsistent
	//	*RequestOutcome_Aggregatable
	Outcome       isRequestOutcome_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOutcome) Reset() {
	*x = RequestOutcome{}
	mi := &file_ocr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOutcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOutcome) ProtoMessage() {}

func (x *RequestOutcome) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOutcome.ProtoReflect.Descriptor instead.
func (*RequestOutcome) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{5}
}

func (x *RequestOutcome) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *RequestOutcome) GetOutcome() isRequestOutcome_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *RequestOutcome) GetLockableToBlock() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Outcome.(*RequestOutcome_LockableToBlock); ok {
			return x.LockableToBlock
		}
	}
	return nil
}

func (x *RequestOutcome) GetEventuallyConsistent() []byte {
	if x != nil {
		if x, ok := x.Outcome.(*RequestOutcome_EventuallyConsistent); ok {
			return x.EventuallyConsistent
		}
	}
	return nil
}

func (x *RequestOutcome) GetAggregatable() *pb.Decimal {
	if x != nil {
		if x, ok := x.Outcome.(*RequestOutcome_Aggregatable); ok {
			return x.Aggregatable
		}
	}
	return nil
}

type isRequestOutcome_Outcome interface {
	isRequestOutcome_Outcome()
}

type RequestOutcome_LockableToBlock struct {
	LockableToBlock *emptypb.Empty `protobuf:"bytes,2,opt,name=lockableToBlock,proto3,oneof"`
}

type RequestOutcome_EventuallyConsistent struct {
	EventuallyConsistent []byte `protobuf:"bytes,3,opt,name=eventuallyConsistent,proto3,oneof"`
}

type RequestOutcome_Aggregatable struct {
	Aggregatable *pb.Decimal `protobuf:"bytes,4,opt,name=aggregatable,proto3,oneof"`
}

func (*RequestOutcome_LockableToBlock) isRequestOutcome_Outcome() {}

func (*RequestOutcome_EventuallyConsistent) isRequestOutcome_Outcome() {}

func (*RequestOutcome_Aggregatable) isRequestOutcome_Outcome() {}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainHeight   *ChainHeight           `protobuf:"bytes,1,opt,name=chainHeight,proto3" json:"chainHeight,omitempty"`
	Outcomes      []*RequestOutcome      `protobuf:"bytes,2,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_ocr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{6}
}

func (x *Outcome) GetChainHeight() *ChainHeight {
	if x != nil {
		return x.ChainHeight
	}
	return nil
}

func (x *Outcome) GetOutcomes() []*RequestOutcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

type RequestReport struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestID string                 `protobuf:"bytes,1,opt,name=requestID,proto3" json:"requestID,omitempty"`
	// Types that are valid to be assigned to Report:
	//
	//	*RequestReport_LockableToBlock
	//	*RequestReport_EventuallyConsistent
	//	*RequestReport_Aggregatable
	Report        isRequestReport_Report `protobuf_oneof:"report"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestReport) Reset() {
	*x = RequestReport{}
	mi := &file_ocr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestReport) ProtoMessage() {}

func (x *RequestReport) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestReport.ProtoReflect.Descriptor instead.
func (*RequestReport) Descriptor() ([]byte, []int) {
	return file_ocr_proto_rawDescGZIP(), []int{7}
}

func (x *RequestReport) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *RequestReport) GetReport() isRequestReport_Report {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *RequestReport) GetLockableToBlock() *ChainHeight {
	if x != nil {
		if x, ok := x.Report.(*RequestReport_LockableToBlock); ok {
			return x.LockableToBlock
		}
	}
	return nil
}

func (x *RequestReport) GetEventuallyConsistent() []byte {
	if x != nil {
		if x, ok := x.Report.(*RequestReport_EventuallyConsistent); ok {
			return x.EventuallyConsistent
		}
	}
	return nil
}

func (x *RequestReport) GetAggregatable() *pb.Decimal {
	if x != nil {
		if x, ok := x.Report.(*RequestReport_Aggregatable); ok {
			return x.Aggregatable
		}
	}
	return nil
}

type isRequestReport_Report interface {
	isRequestReport_Report()
}

type RequestReport_LockableToBlock struct {
	LockableToBlock *ChainHeight `protobuf:"bytes,2,opt,name=lockableToBlock,proto3,oneof"`
}

type RequestReport_EventuallyConsistent struct {
	EventuallyConsistent []byte `protobuf:"bytes,3,opt,name=eventuallyConsistent,proto3,oneof"`
}

type RequestReport_Aggregatable struct {
	Aggregatable *pb.Decimal `protobuf:"bytes,4,opt,name=aggregatable,proto3,oneof"`
}

func (*RequestReport_LockableToBlock) isRequestReport_Report() {}

func (*RequestReport_EventuallyConsistent) isRequestReport_Report() {}

func (*RequestReport_Aggregatable) isRequestReport_Report() {}

var File_ocr_proto protoreflect.FileDescriptor

const file_ocr_proto_rawDesc = "" +
	"\n" +
	"\tocr.proto\x12\x1cchain_capabilities.evm.types\x1a\x1bgoogle/protobuf/empty.proto\x1a\x16values/v1/values.proto\"W\n" +
	"\vChainHeight\x12\x16\n" +
	"\x06latest\x18\x01 \x01(\x03R\x06latest\x12\x12\n" +
	"\x04safe\x18\x02 \x01(\x03R\x04safe\x12\x1c\n" +
	"\tfinalized\x18\x03 \x01(\x03R\tfinalized\"'\n" +
	"\x05Query\x12\x1e\n" +
	"\n" +
	"requestIDs\x18\x01 \x03(\tR\n" +
	"requestIDs\"[\n" +
	"\x17AggregatableObservation\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.values.v1.DecimalR\x05value\"\xfa\x01\n" +
	"\x12RequestObservation\x12B\n" +
	"\x0flockableToBlock\x18\x01 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x0flockableToBlock\x124\n" +
	"\x14eventuallyConsistent\x18\x02 \x01(\fH\x00R\x14eventuallyConsistent\x12[\n" +
	"\faggregatable\x18\x03 \x01(\v25.chain_capabilities.evm.types.AggregatableObservationH\x00R\faggregatableB\r\n" +
	"\vobservation\"\xae\x02\n" +
	"\vObservation\x12K\n" +
	"\vchainHeight\x18\x01 \x01(\v2).chain_capabilities.evm.types.ChainHeightR\vchainHeight\x12_\n" +
	"\fobservations\x18\x02 \x03(\v2;.chain_capabilities.evm.types.Observation.ObservationsEntryR\fobservations\x1aq\n" +
	"\x11ObservationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12F\n" +
	"\x05value\x18\x02 \x01(\v20.chain_capabilities.evm.types.RequestObservationR\x05value:\x028\x01\"\xed\x01\n" +
	"\x0eRequestOutcome\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12B\n" +
	"\x0flockableToBlock\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x0flockableToBlock\x124\n" +
	"\x14eventuallyConsistent\x18\x03 \x01(\fH\x00R\x14eventuallyConsistent\x128\n" +
	"\faggregatable\x18\x04 \x01(\v2\x12.values.v1.DecimalH\x00R\faggregatableB\t\n" +
	"\aoutcome\"\xa0\x01\n" +
	"\aOutcome\x12K\n" +
	"\vchainHeight\x18\x01 \x01(\v2).chain_capabilities.evm.types.ChainHeightR\vchainHeight\x12H\n" +
	"\boutcomes\x18\x02 \x03(\v2,.chain_capabilities.evm.types.RequestOutcomeR\boutcomes\"\xfe\x01\n" +
	"\rRequestReport\x12\x1c\n" +
	"\trequestID\x18\x01 \x01(\tR\trequestID\x12U\n" +
	"\x0flockableToBlock\x18\x02 \x01(\v2).chain_capabilities.evm.types.ChainHeightH\x00R\x0flockableToBlock\x124\n" +
	"\x14eventuallyConsistent\x18\x03 \x01(\fH\x00R\x14eventuallyConsistent\x128\n" +
	"\faggregatable\x18\x04 \x01(\v2\x12.values.v1.DecimalH\x00R\faggregatableB\b\n" +
	"\x06report*\x92\x01\n" +
	"\vRequestType\x12\x18\n" +
	"\x14REQUEST_TYPE_UNKNOWN\x10\x00\x12&\n" +
	"\"REQUEST_TYPE_EVENTUALLY_CONSISTENT\x10\x01\x12\"\n" +
	"\x1eREQUEST_TYPE_LOCKABLE_TO_BLOCK\x10\x02\x12\x1d\n" +
	"\x19REQUEST_TYPE_AGGREGATABLE\x10\x03BQZOgithub.com/smartcontractkit/capabilities/chain_capabilities/evm/consensus/typesb\x06proto3"

var (
	file_ocr_proto_rawDescOnce sync.Once
	file_ocr_proto_rawDescData []byte
)

func file_ocr_proto_rawDescGZIP() []byte {
	file_ocr_proto_rawDescOnce.Do(func() {
		file_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocr_proto_rawDesc), len(file_ocr_proto_rawDesc)))
	})
	return file_ocr_proto_rawDescData
}

var file_ocr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ocr_proto_goTypes = []any{
	(RequestType)(0),                // 0: chain_capabilities.evm.types.RequestType
	(*ChainHeight)(nil),             // 1: chain_capabilities.evm.types.ChainHeight
	(*Query)(nil),                   // 2: chain_capabilities.evm.types.Query
	(*AggregatableObservation)(nil), // 3: chain_capabilities.evm.types.AggregatableObservation
	(*RequestObservation)(nil),      // 4: chain_capabilities.evm.types.RequestObservation
	(*Observation)(nil),             // 5: chain_capabilities.evm.types.Observation
	(*RequestOutcome)(nil),          // 6: chain_capabilities.evm.types.RequestOutcome
	(*Outcome)(nil),                 // 7: chain_capabilities.evm.types.Outcome
	(*RequestReport)(nil),           // 8: chain_capabilities.evm.types.RequestReport
	nil,                             // 9: chain_capabilities.evm.types.Observation.ObservationsEntry
	(*pb.Decimal)(nil),              // 10: values.v1.Decimal
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_ocr_proto_depIdxs = []int32{
	10, // 0: chain_capabilities.evm.types.AggregatableObservation.value:type_name -> values.v1.Decimal
	11, // 1: chain_capabilities.evm.types.RequestObservation.lockableToBlock:type_name -> google.protobuf.Empty
	3,  // 2: chain_capabilities.evm.types.RequestObservation.aggregatable:type_name -> chain_capabilities.evm.types.AggregatableObservation
	1,  // 3: chain_capabilities.evm.types.Observation.chainHeight:type_name -> chain_capabilities.evm.types.ChainHeight
	9,  // 4: chain_capabilities.evm.types.Observation.observations:type_name -> chain_capabilities.evm.types.Observation.ObservationsEntry
	11, // 5: chain_capabilities.evm.types.RequestOutcome.lockableToBlock:type_name -> google.protobuf.Empty
	10, // 6: chain_capabilities.evm.types.RequestOutcome.aggregatable:type_name -> values.v1.Decimal
	1,  // 7: chain_capabilities.evm.types.Outcome.chainHeight:type_name -> chain_capabilities.evm.types.ChainHeight
	6,  // 8: chain_capabilities.evm.types.Outcome.outcomes:type_name -> chain_capabilities.evm.types.RequestOutcome
	1,  // 9: chain_capabilities.evm.types.RequestReport.lockableToBlock:type_name -> chain_capabilities.evm.types.ChainHeight
	10, // 10: chain_capabilities.evm.types.RequestReport.aggregatable:type_name -> values.v1.Decimal
	4,  // 11: chain_capabilities.evm.types.Observation.ObservationsEntry.value:type_name -> chain_capabilities.evm.types.RequestObservation
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_ocr_proto_init() }
func file_ocr_proto_init() {
	if File_ocr_proto != nil {
		return
	}
	file_ocr_proto_msgTypes[3].OneofWrappers = []any{
		(*RequestObservation_LockableToBlock)(nil),
		(*RequestObservation_EventuallyConsistent)(nil),
		(*RequestObservation_Aggregatable)(nil),
	}
	file_ocr_proto_msgTypes[5].OneofWrappers = []any{
		(*RequestOutcome_LockableToBlock)(nil),
		(*RequestOutcome_EventuallyConsistent)(nil),
		(*RequestOutcome_Aggregatable)(nil),
	}
	file_ocr_proto_msgTypes[7].OneofWrappers = []any{
		(*RequestReport_LockableToBlock)(nil),
		(*RequestReport_EventuallyConsistent)(nil),
		(*RequestReport_Aggregatable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocr_proto_rawDesc), len(file_ocr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocr_proto_goTypes,
		DependencyIndexes: file_ocr_proto_depIdxs,
		EnumInfos:         file_ocr_proto_enumTypes,
		MessageInfos:      file_ocr_proto_msgTypes,
	}.Build()
	File_ocr_proto = out.File
	file_ocr_proto_goTypes = nil
	file_ocr_proto_depIdxs = nil
}
