// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package decryptercap

import (
	"encoding/json"
	"fmt"
)

// A test action that decrypts a payload
type Action struct {
	// Config corresponds to the JSON schema field "config".
	Config ActionConfig `json:"config,omitempty" yaml:"config,omitempty" mapstructure:"config,omitempty"`

	// Inputs corresponds to the JSON schema field "inputs".
	Inputs DecryptInputs `json:"inputs" yaml:"inputs" mapstructure:"inputs"`

	// Outputs corresponds to the JSON schema field "outputs".
	Outputs DecryptOutputs `json:"outputs" yaml:"outputs" mapstructure:"outputs"`
}

type ActionConfig map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Action) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["inputs"]; raw != nil && !ok {
		return fmt.Errorf("field inputs in Action: required")
	}
	if _, ok := raw["outputs"]; raw != nil && !ok {
		return fmt.Errorf("field outputs in Action: required")
	}
	type Plain Action
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = Action(plain)
	return nil
}

type DecryptInputs struct {
	// Ciphertexts corresponds to the JSON schema field "ciphertexts".
	Ciphertexts [][]uint8 `json:"ciphertexts" yaml:"ciphertexts" mapstructure:"ciphertexts"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DecryptInputs) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["ciphertexts"]; raw != nil && !ok {
		return fmt.Errorf("field ciphertexts in DecryptInputs: required")
	}
	type Plain DecryptInputs
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = DecryptInputs(plain)
	return nil
}

// Outputs of the Decrypter Action.
type DecryptOutputs struct {
	// AccountID corresponds to the JSON schema field "accountID".
	AccountID string `json:"accountID" yaml:"accountID" mapstructure:"accountID"`

	// Plaintext corresponds to the JSON schema field "plaintext".
	Plaintext []uint8 `json:"plaintext" yaml:"plaintext" mapstructure:"plaintext"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DecryptOutputs) UnmarshalJSON(b []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(b, &raw); err != nil {
		return err
	}
	if _, ok := raw["accountID"]; raw != nil && !ok {
		return fmt.Errorf("field accountID in DecryptOutputs: required")
	}
	if _, ok := raw["plaintext"]; raw != nil && !ok {
		return fmt.Errorf("field plaintext in DecryptOutputs: required")
	}
	type Plain DecryptOutputs
	var plain Plain
	if err := json.Unmarshal(b, &plain); err != nil {
		return err
	}
	*j = DecryptOutputs(plain)
	return nil
}
