// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/smartcontractkit/chainlink-common/pkg/capabilities/cli, DO NOT EDIT.

package readcontractcaptest

import (
	"github.com/smartcontractkit/capabilities/readcontract/readcontractcap"
	"github.com/smartcontractkit/chainlink-common/pkg/workflows/sdk/testutils"
)

// Action registers a new capability mock with the runner
// if another mock is registered for the same capability with for a step, it will take priority for that step.
func Action(runner *testutils.Runner, fn func(input readcontractcap.Input) (readcontractcap.Output, error)) *testutils.Mock[readcontractcap.Input, readcontractcap.Output] {
	mock := testutils.MockCapability[readcontractcap.Input, readcontractcap.Output]("read-contract@1.0.0", fn)
	runner.MockCapability("read-contract@1.0.0", nil, mock)
	return mock
}

// ActionForStep registers a new capability mock with the runner, but only for a given step.
// if another mock was registered for the same capability without a step, this mock will take priority for that step.
func ActionForStep(runner *testutils.Runner, step string, mockFn func(input readcontractcap.Input) (readcontractcap.Output, error)) *testutils.Mock[readcontractcap.Input, readcontractcap.Output] {
	fn := mockFn
	mock := testutils.MockCapability[readcontractcap.Input, readcontractcap.Output]("read-contract@1.0.0", fn)
	runner.MockCapability("read-contract@1.0.0", &step, mock)
	return mock
}
