// Code generated by github.com/smartcontractkit/capabilities/libs/standalone/gen, DO NOT EDIT.

package standalone

import (
	"context"

	"github.com/smartcontractkit/chainlink-common/pkg/services"
)

// Run1 bootstraps the services built from 1 dependency.
// fn receives the context, the StandaloneConfig, and the 1 dependency, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run1[T0 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0]) []services.Service,
	bootDep0 BootstrapDependency[T0],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0)
	}, bootDep0)
}

// Run2 bootstraps the services built from 2 dependencies.
// fn receives the context, the StandaloneConfig, and the 2 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run2[T0 any, T1 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1)
	}, bootDep0, bootDep1)
}

// Run3 bootstraps the services built from 3 dependencies.
// fn receives the context, the StandaloneConfig, and the 3 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run3[T0 any, T1 any, T2 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2)
	}, bootDep0, bootDep1, bootDep2)
}

// Run4 bootstraps the services built from 4 dependencies.
// fn receives the context, the StandaloneConfig, and the 4 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run4[T0 any, T1 any, T2 any, T3 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3)
	}, bootDep0, bootDep1, bootDep2, bootDep3)
}

// Run5 bootstraps the services built from 5 dependencies.
// fn receives the context, the StandaloneConfig, and the 5 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run5[T0 any, T1 any, T2 any, T3 any, T4 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3], dep4 Dependency[T4]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
	bootDep4 BootstrapDependency[T4],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	dep4 := &dependency[T4]{bd: bootDep4, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3, dep4)
	}, bootDep0, bootDep1, bootDep2, bootDep3, bootDep4)
}

// Run6 bootstraps the services built from 6 dependencies.
// fn receives the context, the StandaloneConfig, and the 6 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run6[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3], dep4 Dependency[T4], dep5 Dependency[T5]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
	bootDep4 BootstrapDependency[T4],
	bootDep5 BootstrapDependency[T5],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	dep4 := &dependency[T4]{bd: bootDep4, bs: bs}

	dep5 := &dependency[T5]{bd: bootDep5, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3, dep4, dep5)
	}, bootDep0, bootDep1, bootDep2, bootDep3, bootDep4, bootDep5)
}

// Run7 bootstraps the services built from 7 dependencies.
// fn receives the context, the StandaloneConfig, and the 7 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run7[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any, T6 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3], dep4 Dependency[T4], dep5 Dependency[T5], dep6 Dependency[T6]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
	bootDep4 BootstrapDependency[T4],
	bootDep5 BootstrapDependency[T5],
	bootDep6 BootstrapDependency[T6],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	dep4 := &dependency[T4]{bd: bootDep4, bs: bs}

	dep5 := &dependency[T5]{bd: bootDep5, bs: bs}

	dep6 := &dependency[T6]{bd: bootDep6, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3, dep4, dep5, dep6)
	}, bootDep0, bootDep1, bootDep2, bootDep3, bootDep4, bootDep5, bootDep6)
}

// Run8 bootstraps the services built from 8 dependencies.
// fn receives the context, the StandaloneConfig, and the 8 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run8[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3], dep4 Dependency[T4], dep5 Dependency[T5], dep6 Dependency[T6], dep7 Dependency[T7]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
	bootDep4 BootstrapDependency[T4],
	bootDep5 BootstrapDependency[T5],
	bootDep6 BootstrapDependency[T6],
	bootDep7 BootstrapDependency[T7],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	dep4 := &dependency[T4]{bd: bootDep4, bs: bs}

	dep5 := &dependency[T5]{bd: bootDep5, bs: bs}

	dep6 := &dependency[T6]{bd: bootDep6, bs: bs}

	dep7 := &dependency[T7]{bd: bootDep7, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3, dep4, dep5, dep6, dep7)
	}, bootDep0, bootDep1, bootDep2, bootDep3, bootDep4, bootDep5, bootDep6, bootDep7)
}

// Run9 bootstraps the services built from 9 dependencies.
// fn receives the context, the StandaloneConfig, and the 9 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run9[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3], dep4 Dependency[T4], dep5 Dependency[T5], dep6 Dependency[T6], dep7 Dependency[T7], dep8 Dependency[T8]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
	bootDep4 BootstrapDependency[T4],
	bootDep5 BootstrapDependency[T5],
	bootDep6 BootstrapDependency[T6],
	bootDep7 BootstrapDependency[T7],
	bootDep8 BootstrapDependency[T8],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	dep4 := &dependency[T4]{bd: bootDep4, bs: bs}

	dep5 := &dependency[T5]{bd: bootDep5, bs: bs}

	dep6 := &dependency[T6]{bd: bootDep6, bs: bs}

	dep7 := &dependency[T7]{bd: bootDep7, bs: bs}

	dep8 := &dependency[T8]{bd: bootDep8, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3, dep4, dep5, dep6, dep7, dep8)
	}, bootDep0, bootDep1, bootDep2, bootDep3, bootDep4, bootDep5, bootDep6, bootDep7, bootDep8)
}

// Run10 bootstraps the services built from 10 dependencies.
// fn receives the context, the StandaloneConfig, and the 10 dependencies, and returns the services to run.
// The dependencies are wrapped into a factory that only needs the context, which is handed to bootstrap.
// The returned services are started together and their health is aggregated by the bootstrapper.
func Run10[T0 any, T1 any, T2 any, T3 any, T4 any, T5 any, T6 any, T7 any, T8 any, T9 any](
	bs *Bootstrapper,
	fn func(ctx context.Context, cfg *StandaloneConfig, dep0 Dependency[T0], dep1 Dependency[T1], dep2 Dependency[T2], dep3 Dependency[T3], dep4 Dependency[T4], dep5 Dependency[T5], dep6 Dependency[T6], dep7 Dependency[T7], dep8 Dependency[T8], dep9 Dependency[T9]) []services.Service,
	bootDep0 BootstrapDependency[T0],
	bootDep1 BootstrapDependency[T1],
	bootDep2 BootstrapDependency[T2],
	bootDep3 BootstrapDependency[T3],
	bootDep4 BootstrapDependency[T4],
	bootDep5 BootstrapDependency[T5],
	bootDep6 BootstrapDependency[T6],
	bootDep7 BootstrapDependency[T7],
	bootDep8 BootstrapDependency[T8],
	bootDep9 BootstrapDependency[T9],
) error {

	dep0 := &dependency[T0]{bd: bootDep0, bs: bs}

	dep1 := &dependency[T1]{bd: bootDep1, bs: bs}

	dep2 := &dependency[T2]{bd: bootDep2, bs: bs}

	dep3 := &dependency[T3]{bd: bootDep3, bs: bs}

	dep4 := &dependency[T4]{bd: bootDep4, bs: bs}

	dep5 := &dependency[T5]{bd: bootDep5, bs: bs}

	dep6 := &dependency[T6]{bd: bootDep6, bs: bs}

	dep7 := &dependency[T7]{bd: bootDep7, bs: bs}

	dep8 := &dependency[T8]{bd: bootDep8, bs: bs}

	dep9 := &dependency[T9]{bd: bootDep9, bs: bs}

	return bs.run(func(ctx context.Context) []services.Service {
		return fn(ctx, bs.config, dep0, dep1, dep2, dep3, dep4, dep5, dep6, dep7, dep8, dep9)
	}, bootDep0, bootDep1, bootDep2, bootDep3, bootDep4, bootDep5, bootDep6, bootDep7, bootDep8, bootDep9)
}
