// Code generated by github.com/smartcontractkit/capabilities/libs/standalone/protohelpers/protoc, DO NOT EDIT.

package protos

import (
	"context"
	"fmt"

	"google.golang.org/protobuf/types/known/emptypb"

	"google.golang.org/protobuf/reflect/protoreflect"

	"github.com/smartcontractkit/chainlink-common/pkg/capabilities"
	caperrors "github.com/smartcontractkit/chainlink-common/pkg/capabilities/errors"
)

// Avoid unused imports if there is configuration type
var _ = emptypb.Empty{}

// ClientCapability is what a capability implements to be served as http-actions@1.0.0-alpha.
//
// It carries no Initialise: a capability is given what it needs when it is
// built, and everything a host does to it - registering it, serving it,
// announcing it, taking it back out - belongs to the bootstrapper that hosts it
// rather than to the capability or to this server.
type ClientCapability interface {
	SendRequest(ctx context.Context, metadata capabilities.RequestMetadata, input *Request) (*capabilities.ResponseAndMetadata[*Response], caperrors.Error)

	Start(ctx context.Context) error
	Close() error
	HealthReport() map[string]error
	Name() string
	Description() string
	Ready() error
}

func NewClientServer(capability ClientCapability) *ClientServer {
	stopCh := make(chan struct{})
	return &ClientServer{
		clientCapability: clientCapability{ClientCapability: capability, stopCh: stopCh},
		stopCh:           stopCh,
	}
}

// ClientServer serves the capability: it turns the untyped requests a host
// delivers into calls on the typed methods above, and is itself the
// capabilities.ExecutableAndTriggerCapability a host registers and serves.
type ClientServer struct {
	clientCapability
	stopCh chan struct{}
}

// Close stops answering registered triggers, then closes the capability.
//
// Nothing is deregistered here. What put this capability in a registry, and
// announced it to a node, is the host - so taking it back out is the host's too,
// and doing it from both would race a shutdown against itself.
func (c *ClientServer) Close() error {
	if c.stopCh != nil {
		close(c.stopCh)
	}

	return c.clientCapability.Close()
}

type clientCapability struct {
	ClientCapability
	stopCh chan struct{}
}

func (c *clientCapability) Info(ctx context.Context) (capabilities.CapabilityInfo, error) {
	return capabilities.NewCapabilityInfo("http-actions@1.0.0-alpha", capabilities.CapabilityTypeCombined, c.ClientCapability.Description())
}

var _ capabilities.ExecutableAndTriggerCapability = (*clientCapability)(nil)

const ClientID = "http-actions@1.0.0-alpha"

// Service is the proto service this server was generated from.
//
// Taken from the file descriptor rather than rebuilt, so it is the same
// descriptor the messages were generated against: whatever reads it sees the
// methods, and their input and output types, exactly as the proto declares them.
func (c *clientCapability) Service() protoreflect.ServiceDescriptor {
	return File_capabilities_networking_http_v1alpha_client_proto.Services().ByName("Client")
}

func (c *clientCapability) RegisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) (<-chan capabilities.TriggerResponse, error) {
	return nil, fmt.Errorf("trigger %s not found", request.Method)
}

func (c *clientCapability) UnregisterTrigger(ctx context.Context, request capabilities.TriggerRegistrationRequest) error {
	return fmt.Errorf("trigger %s not found", request.Method)
}

func (c *clientCapability) AckEvent(ctx context.Context, triggerId string, eventId string, method string) error {
	return fmt.Errorf("trigger %s not found", method)
}

func (c *clientCapability) RegisterToWorkflow(ctx context.Context, request capabilities.RegisterToWorkflowRequest) error {
	return nil
}

func (c *clientCapability) UnregisterFromWorkflow(ctx context.Context, request capabilities.UnregisterFromWorkflowRequest) error {
	return nil
}

func (c *clientCapability) Execute(ctx context.Context, request capabilities.CapabilityRequest) (capabilities.CapabilityResponse, error) {
	response := capabilities.CapabilityResponse{}
	ctx = request.Metadata.ContextWithCRE(ctx)
	switch request.Method {
	case "SendRequest":
		input := &Request{}
		config := &emptypb.Empty{}
		wrapped := func(ctx context.Context, metadata capabilities.RequestMetadata, input *Request, _ *emptypb.Empty) (*Response, capabilities.ResponseMetadata, *capabilities.OCRAttestation, error) {
			output, err := c.ClientCapability.SendRequest(ctx, metadata, input)
			if err != nil {
				return nil, capabilities.ResponseMetadata{}, nil, err
			}
			if output == nil {
				return nil, capabilities.ResponseMetadata{}, nil, fmt.Errorf("output and error is nil for method SendRequest(..) (if output is nil error must be present)")
			}
			return output.Response, output.ResponseMetadata, output.OCRAttestation, err
		}
		return capabilities.Execute(ctx, request, input, config, wrapped)
	default:
		return response, fmt.Errorf("method %s not found", request.Method)
	}
}
