name: CI

on: [push]

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  affected-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npx nx init

      - name: Get affected projects
        id: get-affected
        run: ./nx show projects --affected --json ${{ fromJSON('["--base=origin/main", "--base=origin/main~1"]')[github.ref == 'refs/heads/main'] }}
        # run: echo "AFFECTED_PROJECTS=$(nx show projects --affected --json)" >> $GITHUB_ENV

  lint:
    needs: affected-projects
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     projects: "$env.AFFECTED_PROJECTS"
    steps:
      - run: echo "The value of MY_ENV_VAR is $MY_ENV_VAR"
      # - run: |
      #     echo "Linting project ${{ item }}"
