name: go

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  GOPRIVATE: github.com/smartcontractkit/capabilities
  GO_VERSION: 1.25.3

jobs:
  test:
    runs-on: runs-on=${{ github.run_id }}/runner=8cpu-linux-arm64/spot=false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          # IMPORTANT: Cache bust any time go.sum changes
          cache-dependency-path: "**/*.sum"

      - name: Support private Go modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/support-private-gomods.sh

      - name: Install protoc-gen-go grpc
        shell: bash
        run: |
          go install github.com/jmank88/gomods@v0.1.6
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo "gobuildcache=$(go env GOCACHE)" >> $GITHUB_OUTPUT

      - name: Tidy
        run: |
          gomods tidy
      - name: Ensure no diff
        run: |
          git diff
          git diff --stat --exit-code

      - name: Test
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}
        run: gomods -go test -race ./... GOWORK=off

      - name: Build
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}
        run: gomods -go build .
