name: Go

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  GOPRIVATE: github.com/smartcontractkit/capabilities
  GO_VERSION: 1.25.3

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_URL: postgresql://postgres:postgres@localhost:5432/chainlink_test?sslmode=disable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          # IMPORTANT: Cache bust any time go.sum changes
          cache-dependency-path: "**/*.sum"

      - name: Support private Go modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/support-private-gomods.sh

      - name: Install protoc-gen-go grpc
        shell: bash
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.7
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
          go install github.com/jmank88/gomods@v0.1.6
          echo "gomodcache=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
          echo "gobuildcache=$(go env GOCACHE)" >> $GITHUB_OUTPUT

      - name: Install protoc
        shell: bash
        run: |
          PROTOC_VERSION=29.3
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-x86_64.zip
          unzip protoc-${PROTOC_VERSION}-linux-x86_64.zip -d protoc3
          sudo mv protoc3/bin/* /usr/local/bin/
          sudo mv protoc3/include/* /usr/local/include/
          rm -rf protoc3 protoc-${PROTOC_VERSION}-linux-x86_64.zip

      - name: Run All Go Tests
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}
        run: gomods -go test ./... GOWORK=off
