// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/smartcontractkit/capabilities/libs/chainconsensus/types"
)

// RequestsHandler is an autogenerated mock type for the RequestsHandler type
type RequestsHandler struct {
	mock.Mock
}

type RequestsHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestsHandler) EXPECT() *RequestsHandler_Expecter {
	return &RequestsHandler_Expecter{mock: &_m.Mock}
}

// CompleteHashableRequest provides a mock function with given fields: id, report
func (_m *RequestsHandler) CompleteHashableRequest(id string, report *types.HashableRequestReport) error {
	ret := _m.Called(id, report)

	if len(ret) == 0 {
		panic("no return value specified for CompleteHashableRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *types.HashableRequestReport) error); ok {
		r0 = rf(id, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestsHandler_CompleteHashableRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteHashableRequest'
type RequestsHandler_CompleteHashableRequest_Call struct {
	*mock.Call
}

// CompleteHashableRequest is a helper method to define mock.On call
//   - id string
//   - report *types.HashableRequestReport
func (_e *RequestsHandler_Expecter) CompleteHashableRequest(id interface{}, report interface{}) *RequestsHandler_CompleteHashableRequest_Call {
	return &RequestsHandler_CompleteHashableRequest_Call{Call: _e.mock.On("CompleteHashableRequest", id, report)}
}

func (_c *RequestsHandler_CompleteHashableRequest_Call) Run(run func(id string, report *types.HashableRequestReport)) *RequestsHandler_CompleteHashableRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*types.HashableRequestReport))
	})
	return _c
}

func (_c *RequestsHandler_CompleteHashableRequest_Call) Return(_a0 error) *RequestsHandler_CompleteHashableRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestsHandler_CompleteHashableRequest_Call) RunAndReturn(run func(string, *types.HashableRequestReport) error) *RequestsHandler_CompleteHashableRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteProtoRequest provides a mock function with given fields: id, report
func (_m *RequestsHandler) CompleteProtoRequest(id string, report *types.RequestReport) error {
	ret := _m.Called(id, report)

	if len(ret) == 0 {
		panic("no return value specified for CompleteProtoRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *types.RequestReport) error); ok {
		r0 = rf(id, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestsHandler_CompleteProtoRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteProtoRequest'
type RequestsHandler_CompleteProtoRequest_Call struct {
	*mock.Call
}

// CompleteProtoRequest is a helper method to define mock.On call
//   - id string
//   - report *types.RequestReport
func (_e *RequestsHandler_Expecter) CompleteProtoRequest(id interface{}, report interface{}) *RequestsHandler_CompleteProtoRequest_Call {
	return &RequestsHandler_CompleteProtoRequest_Call{Call: _e.mock.On("CompleteProtoRequest", id, report)}
}

func (_c *RequestsHandler_CompleteProtoRequest_Call) Run(run func(id string, report *types.RequestReport)) *RequestsHandler_CompleteProtoRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*types.RequestReport))
	})
	return _c
}

func (_c *RequestsHandler_CompleteProtoRequest_Call) Return(_a0 error) *RequestsHandler_CompleteProtoRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RequestsHandler_CompleteProtoRequest_Call) RunAndReturn(run func(string, *types.RequestReport) error) *RequestsHandler_CompleteProtoRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequest provides a mock function with given fields: id
func (_m *RequestsHandler) GetRequest(id string) (types.Request, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequest")
	}

	var r0 types.Request
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (types.Request, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) types.Request); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// RequestsHandler_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type RequestsHandler_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//   - id string
func (_e *RequestsHandler_Expecter) GetRequest(id interface{}) *RequestsHandler_GetRequest_Call {
	return &RequestsHandler_GetRequest_Call{Call: _e.mock.On("GetRequest", id)}
}

func (_c *RequestsHandler_GetRequest_Call) Run(run func(id string)) *RequestsHandler_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RequestsHandler_GetRequest_Call) Return(_a0 types.Request, _a1 bool) *RequestsHandler_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RequestsHandler_GetRequest_Call) RunAndReturn(run func(string) (types.Request, bool)) *RequestsHandler_GetRequest_Call {
	_c.Call.Return(run)
	return _c
}

// GetRequestIDs provides a mock function with given fields: batchSize
func (_m *RequestsHandler) GetRequestIDs(batchSize int) ([]string, error) {
	ret := _m.Called(batchSize)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestIDs")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]string, error)); ok {
		return rf(batchSize)
	}
	if rf, ok := ret.Get(0).(func(int) []string); ok {
		r0 = rf(batchSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(batchSize)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestsHandler_GetRequestIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequestIDs'
type RequestsHandler_GetRequestIDs_Call struct {
	*mock.Call
}

// GetRequestIDs is a helper method to define mock.On call
//   - batchSize int
func (_e *RequestsHandler_Expecter) GetRequestIDs(batchSize interface{}) *RequestsHandler_GetRequestIDs_Call {
	return &RequestsHandler_GetRequestIDs_Call{Call: _e.mock.On("GetRequestIDs", batchSize)}
}

func (_c *RequestsHandler_GetRequestIDs_Call) Run(run func(batchSize int)) *RequestsHandler_GetRequestIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *RequestsHandler_GetRequestIDs_Call) Return(_a0 []string, _a1 error) *RequestsHandler_GetRequestIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RequestsHandler_GetRequestIDs_Call) RunAndReturn(run func(int) ([]string, error)) *RequestsHandler_GetRequestIDs_Call {
	_c.Call.Return(run)
	return _c
}

// NewRequestsHandler creates a new instance of RequestsHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestsHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestsHandler {
	mock := &RequestsHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
